// Generated by @zmdb/compiler from src/config/index.ts. Do not edit.
//
// The validators, compiled. Every check below was emitted from a type in src/config/index.ts's
// witness module by `@zmdb/compiler`, so there is no schema to walk at runtime and
// nothing to look up: the shape is the control flow.
//
// This half is the types: the signatures the compiler reads when the source imports the
// module next door. Nothing here is checked against the implementation, and nothing needs
// to be — the witness makes the same claims against the runtime API, and *that* is checked.
import type { ZmdbConfigData } from './contract.js';

export declare function zmdbAssertZmdbConfigData(value: unknown): ZmdbConfigData;
