/*zmdb:imports*/
// Generated by @zmdb/compiler from src/config/index.ts. Checked, not edited.
//
// One wrapper per validation call src/config/index.ts used to make, written against the runtime
// API so that the compiler still sees each type argument. That is the point of the file: it
// is what the project compiler reads on the next run to regenerate the compiled module, and it is
// what turns a renamed or deleted type into a build error here instead of a validator that
// silently checks a shape nobody declares.
//
// Editing it by hand does nothing. An entry disappears when the source stops referring to
// its export name, so deleting a call in the source is how you delete a validator; there's
// no bookkeeping to keep in step.

import type { ZmdbConfigData } from './contract.js';
import { assert } from '@zmdb/aot-validator/utilities';
/*zmdb:/imports*/

/*zmdb:begin:zmdbAssertZmdbConfigData*/
export function zmdbAssertZmdbConfigData(value: unknown): ZmdbConfigData {
  return assert<ZmdbConfigData>(value);
}
/*zmdb:end:zmdbAssertZmdbConfigData*/
