import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { loadArchitectureSync } from '../scripts/architecture/index.mjs';
import { PRODUCT_CATALOG } from '../scripts/product/catalog.mjs';
import { INTEGRATIONS } from './integrations.mjs';
import { PRODUCT_JOURNEY } from './navigation-plan.mjs';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

export const REQUIRED_FRAMEWORKS = Object.freeze([
  'React',
  'Angular',
  'Vue',
  'Svelte',
  'Solid',
  'React Native',
  'Next.js',
  'Nuxt',
  'SvelteKit',
]);

const VALID_INTEGRATION_STATUSES = new Set(['built-in', 'optional', 'documented', 'not-planned']);
const PACKAGE_REFERENCE_MARKER = 'product-catalog package-reference';
const INTEGRATION_MARKER = 'integrations framework-integrations';
const ARCHITECTURE_POLICY_MARKER = 'architecture policy-graph';

const GENERATED_DOCUMENTS = Object.freeze([
  Object.freeze({
    path: 'docs-site/content/package-reference.md',
    marker: PACKAGE_REFERENCE_MARKER,
    render: renderPackageReference,
  }),
  Object.freeze({
    path: 'docs-site/content/framework-integrations.md',
    marker: INTEGRATION_MARKER,
    render: renderIntegrations,
  }),
  Object.freeze({
    path: 'ARCHITECTURE.md',
    marker: ARCHITECTURE_POLICY_MARKER,
    render: renderArchitecturePolicy,
    requiresArchitecture: true,
  }),
  Object.freeze({
    path: 'docs-site/content/architecture.md',
    marker: ARCHITECTURE_POLICY_MARKER,
    render: renderArchitecturePolicy,
    requiresArchitecture: true,
  }),
]);

const GOVERNANCE_DOCUMENTATION = Object.freeze({
  'ARCHITECTURE.md': Object.freeze([
    'node docs-site/generated.mjs',
    'yarn verify:product-catalog',
    'yarn verify:architecture-zones',
    'yarn verify:runtime-reachability',
    'yarn verify:package-metadata',
    'yarn verify:release-governance',
    'yarn verify:docs-generated',
  ]),
  'docs-site/content/architecture.md': Object.freeze([
    'node docs-site/generated.mjs',
    'node scripts/release/bump.mjs "$RELEASE_VERSION"',
    'node scripts/release/plan.mjs --publish-tsv',
    'yarn verify:architecture-zones',
    'yarn verify:runtime-reachability',
    'yarn verify:package-metadata',
    'yarn verify:release-governance',
    'yarn verify:docs-generated',
    'git tag "v$RELEASE_VERSION"',
  ]),
  'PUBLISHING.md': Object.freeze([
    'node docs-site/generated.mjs',
    'node scripts/release/bump.mjs "$RELEASE_VERSION"',
    'node scripts/release/plan.mjs --publish-tsv',
    'yarn verify:product-catalog',
    'yarn verify:architecture-zones',
    'yarn verify:runtime-reachability',
    'yarn verify:package-metadata',
    'yarn verify:release-governance',
    'yarn verify:docs-generated',
    'git tag "v$RELEASE_VERSION"',
  ]),
});

function markerTokens(marker) {
  return {
    start: `<!-- generated: ${marker} -->`,
    end: `<!-- /generated: ${marker} -->`,
  };
}

function markerCount(source, marker) {
  return source.split(marker).length - 1;
}

function locateGeneratedRegion(source, startMarker, endMarker) {
  const problems = [];
  const startCount = markerCount(source, startMarker);
  const endCount = markerCount(source, endMarker);
  if (startCount !== 1 || endCount !== 1) {
    problems.push(`generated marker counts must be 1/1, received ${String(startCount)}/${String(endCount)}`);
    return { problems };
  }

  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker);
  if (end < start) {
    problems.push('generated markers are reversed');
    return { problems };
  }
  return {
    start: start + startMarker.length,
    end,
    problems,
  };
}

function generatedBody(expected) {
  return `\n\n${expected.trimEnd()}\n\n`;
}

export function compareGeneratedRegion(source, startMarker, endMarker, expected) {
  const located = locateGeneratedRegion(source, startMarker, endMarker);
  if (located.problems.length > 0) return located.problems;
  if (located.start === undefined || located.end === undefined) {
    return ['generated marker positions are unavailable'];
  }
  return source.slice(located.start, located.end) === generatedBody(expected)
    ? []
    : ['generated bytes disagree with canonical sources'];
}

export function replaceGeneratedRegion(source, startMarker, endMarker, expected) {
  const located = locateGeneratedRegion(source, startMarker, endMarker);
  if (located.problems.length > 0) {
    throw new Error(located.problems.join('; '));
  }
  if (located.start === undefined || located.end === undefined) {
    throw new Error('generated marker positions are unavailable');
  }
  return `${source.slice(0, located.start)}${generatedBody(expected)}${source.slice(located.end)}`;
}

function escapeCell(value) {
  return String(value).replaceAll('|', '\\|').replaceAll(/\r?\n/g, '<br>');
}

function renderMarkdownTable(headers, rows) {
  const escapedHeaders = headers.map(escapeCell);
  const escapedRows = rows.map(row => row.map(escapeCell));
  const widths = escapedHeaders.map((header, index) => {
    return Math.max(3, header.length, ...escapedRows.map(row => row[index]?.length ?? 0));
  });
  const line = cells => `| ${cells.map((cell, index) => cell.padEnd(widths[index])).join(' | ')} |`;
  return `${[
    line(escapedHeaders),
    `| ${widths.map(width => '-'.repeat(width)).join(' | ')} |`,
    ...escapedRows.map(line),
  ].join('\n')}\n`;
}

function wrapParagraph(value, width = 200) {
  const words = String(value).trim().split(/\s+/);
  const lines = [];
  let line = '';
  for (const word of words) {
    if (line.length === 0) {
      line = word;
    } else if (line.length + word.length + 1 <= width) {
      line += ` ${word}`;
    } else {
      lines.push(line);
      line = word;
    }
  }
  if (line.length > 0) lines.push(line);
  return lines.join('\n');
}

function optionalityLabel(optionality) {
  if (optionality?.kind === 'required') return 'required';
  if (optionality?.kind === 'tooling') return 'tooling';
  if (optionality?.kind === 'integration') return `integration: ${optionality.technology}`;
  if (optionality?.kind === 'capability') return `capability: ${optionality.capability}`;
  if (optionality?.kind === 'provider') {
    return `provider: ${optionality.capability} / ${optionality.technology}`;
  }
  return 'invalid';
}

function consumerLabel(consumer) {
  if (typeof consumer?.fixture === 'string') return consumer.fixture;
  if (typeof consumer?.reason === 'string') return consumer.reason;
  return 'missing';
}

function manifestValue(value) {
  if (typeof value === 'string') return value;
  return JSON.stringify(value, Object.keys(value ?? {}).toSorted());
}

function shellArgument(value) {
  if (/^[A-Za-z0-9@_./:+^~-]+$/.test(value)) return value;
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function manifestEntries(value) {
  return typeof value === 'object' && value !== null
    ? Object.entries(value).toSorted(([left], [right]) => left.localeCompare(right))
    : [];
}

function optionalPeerEntries(manifest) {
  return manifestEntries(manifest.peerDependencies).filter(([name]) => {
    const meta = manifest.peerDependenciesMeta?.[name];
    return typeof meta === 'object' && meta !== null && meta.optional === true;
  });
}

function requiredPeerEntries(manifest) {
  const optional = new Set(optionalPeerEntries(manifest).map(([name]) => name));
  return manifestEntries(manifest.peerDependencies).filter(([name]) => !optional.has(name));
}

function listMap(lines, label, entries) {
  if (entries.length === 0) {
    lines.push(`- **${label}:** None.`);
    return;
  }
  lines.push(`- **${label}:**`);
  for (const [name, value] of entries) lines.push(`  - \`${name}\` → \`${manifestValue(value)}\``);
}

function listValues(lines, label, values) {
  if (values.length === 0) {
    lines.push(`- **${label}:** None.`);
    return;
  }
  lines.push(`- **${label}:**`);
  for (const value of values) lines.push(`  - \`${value}\``);
}

function packageManifest(manifests, directory) {
  return manifests.get(directory)?.manifest ?? {};
}

function installCommand(row, manifest, productManifest) {
  const version = typeof manifest.version === 'string' ? manifest.version : 'missing';
  if (row.optionality?.kind === 'tooling') {
    return `npm add --save-dev ${String(manifest.name ?? row.npmName)}@${version}`;
  }
  if (row.optionality?.kind === 'integration' || row.optionality?.kind === 'provider') {
    const peers = requiredPeerEntries(manifest).map(([name, range]) =>
      shellArgument(`${name}@${manifestValue(range)}`),
    );
    return `npm add ${[`${String(manifest.name ?? row.npmName)}@${version}`, ...peers].join(' ')}`;
  }
  if (row.optionality?.kind === 'capability') {
    return `npm add ${String(manifest.name ?? row.npmName)}@${version}`;
  }
  const productVersion = typeof productManifest.version === 'string' ? productManifest.version : 'missing';
  const productDependencies = productManifest.dependencies ?? {};
  if (row.npmName === 'zmdb' || Object.hasOwn(productDependencies, row.npmName)) {
    return `npm add zmdb@${productVersion}`;
  }
  return `npm add ${String(manifest.name ?? row.npmName)}@${version}`;
}

export function renderPackageReferenceRows(rows, manifests) {
  const productManifest = packageManifest(
    manifests,
    rows.find(row => row.npmName === 'zmdb')?.directory ?? 'packages/zmdb',
  );
  const packages = [...rows]
    .toSorted((left, right) => left.npmName.localeCompare(right.npmName))
    .map(row => ({ row, manifest: packageManifest(manifests, row.directory) }));

  const summary = renderMarkdownTable(
    ['Package', 'Version', 'Role', 'Install mode', 'Installation', 'Description', 'Documentation'],
    packages.map(({ row, manifest }) => [
      manifest.name ?? row.npmName,
      manifest.version ?? 'missing',
      row.role,
      optionalityLabel(row.optionality),
      `\`${installCommand(row, manifest, productManifest)}\``,
      manifest.description ?? 'missing',
      row.docsOwner,
    ]),
  );

  const details = packages.map(({ row, manifest }) => {
    const lines = [
      `### \`${String(manifest.name ?? row.npmName)}\``,
      '',
      wrapParagraph(manifest.description ?? 'No package description is present in the manifest.'),
      '',
    ];
    listMap(lines, 'Exports', manifestEntries(manifest.exports));
    listMap(lines, 'Dependencies', manifestEntries(manifest.dependencies));
    listMap(lines, 'Optional dependencies', manifestEntries(manifest.optionalDependencies));
    listMap(lines, 'Optional peers', optionalPeerEntries(manifest));
    listMap(lines, 'Required peers', requiredPeerEntries(manifest));
    listMap(lines, 'Engines', manifestEntries(manifest.engines));
    lines.push(`- **License:** \`${String(manifest.license ?? 'missing')}\``);
    listValues(lines, 'Facade exposure', [...(row.facade?.root ?? []), ...(row.facade?.subpaths ?? [])]);
    lines.push(`- **External proof:** ${consumerLabel(row.consumer)}`);
    return lines.join('\n');
  });

  return `${summary}\n${details.join('\n\n')}\n`;
}

export function renderIntegrationRows(records) {
  const rows = [...records]
    .toSorted((left, right) => left.capability.localeCompare(right.capability))
    .map(record => [
      record.capability,
      record.status,
      record.package ?? '—',
      (record.peers ?? []).join('<br>') || '—',
      `[${record.docs}](./${record.docs}.html)`,
      (record.evidence ?? []).map(path => `\`${path}\``).join('<br>'),
    ]);
  return renderMarkdownTable(
    ['Framework', 'Status', 'Public package', 'Framework peers', 'Documentation', 'Repository evidence'],
    rows,
  );
}

function codeList(values) {
  return values.length === 0 ? 'none' : values.map(value => `\`${value}\``).join('<br>');
}

export function renderArchitecturePolicy(_rows, _manifests, _records, architecture) {
  const byId = new Map(architecture.packages.map(packageRecord => [packageRecord.id, packageRecord]));
  const packages = [...architecture.packages].toSorted(
    (left, right) => left.policy.ring - right.policy.ring || left.npmName.localeCompare(right.npmName),
  );
  const edgeCount = packages.reduce(
    (count, packageRecord) => count + packageRecord.policy.allowedWorkspaceDependencies.length,
    0,
  );
  const maximumRing = Math.max(...packages.map(packageRecord => packageRecord.policy.ring));
  const graph = renderMarkdownTable(
    ['Ring', 'Zone', 'Package', 'Direct workspace dependencies'],
    packages.map(packageRecord => [
      String(packageRecord.policy.ring),
      packageRecord.policy.zone,
      `\`${packageRecord.npmName}\``,
      codeList(
        packageRecord.policy.allowedWorkspaceDependencies.map(
          dependency => byId.get(dependency)?.npmName ?? `missing:${dependency}`,
        ),
      ),
    ]),
  );

  const reachability = [];
  for (const packageRecord of packages) {
    for (const dependency of packageRecord.policy.allowedRuntimeDependencies) {
      reachability.push([
        `\`${packageRecord.npmName}\``,
        'ordinary runtime dependency',
        `\`${dependency}\``,
        'ordinary runtime entries',
      ]);
    }
    if (packageRecord.policy.toolingEntries.length > 0) {
      reachability.push([
        `\`${packageRecord.npmName}\``,
        'tooling boundary',
        'tooling-only code',
        codeList(packageRecord.policy.toolingEntries),
      ]);
    }
    for (const [peer, selectors] of Object.entries(packageRecord.policy.optionalPeerEntries).toSorted(
      ([left], [right]) => left.localeCompare(right),
    )) {
      const peers =
        typeof packageRecord.manifest.peerDependencies === 'object' && packageRecord.manifest.peerDependencies !== null
          ? packageRecord.manifest.peerDependencies
          : {};
      const range = typeof peers[peer] === 'string' ? `@${peers[peer]}` : '';
      reachability.push([`\`${packageRecord.npmName}\``, 'optional peer', `\`${peer}${range}\``, codeList(selectors)]);
    }
  }

  return [
    `Measured from \`scripts/product/catalog.mjs\`, \`scripts/architecture/policy.mjs\`, and the admitted manifests: **${String(packages.length)} catalog packages**, **${String(edgeCount)} direct workspace edges**, and canonical rings **0–${String(maximumRing)}**.`,
    '',
    graph.trimEnd(),
    '',
    'Entry-specific runtime, tooling, and optional-peer reachability assignments:',
    '',
    renderMarkdownTable(
      ['Package', 'Reachability class', 'Allowed target', 'Entry selector(s)'],
      reachability,
    ).trimEnd(),
    '',
    'The tables are regenerated by `node docs-site/generated.mjs` and checked without writing by `yarn verify:docs-generated`.',
    '',
  ].join('\n');
}

function validEvidencePath(path) {
  if (path.startsWith('fixtures/')) return true;
  if (path.endsWith('/SPEC.md')) return true;
  if (/\.(?:spec|type-test)\.ts$/.test(path)) return true;
  return /^packages\/[^/]+\/src\/.+\.[cm]?[jt]s$/.test(path);
}

export function verifyIntegrationRecords(rows, records, options = {}) {
  const problems = [];
  const packages = new Map(rows.map(row => [row.npmName, row]));
  const manifests = options.manifests;
  const pageSlugs = options.pageSlugs;
  const root = options.root;
  const requiredCapabilities = options.requiredCapabilities;
  const seen = new Map();

  for (const record of records) {
    seen.set(record.capability, (seen.get(record.capability) ?? 0) + 1);
    if (!VALID_INTEGRATION_STATUSES.has(record.status)) {
      problems.push(`integration ${record.capability} has invalid status ${record.status}`);
    }
    if (record.package !== null && !packages.has(record.package)) {
      problems.push(`integration ${record.capability} names uncatalogued package ${record.package}`);
    }
    if (record.status === 'not-planned' && record.package !== null) {
      problems.push(`not-planned integration ${record.capability} must not name a package`);
    }
    if (record.status !== 'not-planned' && record.package === null) {
      problems.push(`${record.status} integration ${record.capability} must name a package`);
    }
    if (record.peers !== undefined) {
      const owner = record.package === null ? undefined : packages.get(record.package);
      if (record.status !== 'optional') {
        problems.push(`integration ${record.capability} names peers outside optional status`);
      } else if (owner?.optionality?.kind !== 'integration' && owner?.optionality?.kind !== 'provider') {
        problems.push(`integration ${record.capability} names peers on a non-integration/provider package`);
      }
      if (
        !Array.isArray(record.peers) ||
        record.peers.length === 0 ||
        record.peers.some(peer => typeof peer !== 'string' || peer.length === 0)
      ) {
        problems.push(`integration ${record.capability} peers must be a non-empty string array`);
      } else {
        const duplicates = record.peers.filter((peer, index) => record.peers.indexOf(peer) !== index);
        if (duplicates.length > 0) {
          problems.push(`integration ${record.capability} repeats peers ${[...new Set(duplicates)].join(', ')}`);
        }
        if (manifests !== undefined && record.package !== null) {
          const manifest = packageManifest(manifests, owner?.directory ?? '');
          for (const peer of record.peers) {
            if (manifest.peerDependencies?.[peer] === undefined) {
              problems.push(`integration ${record.capability} peer ${peer} is absent from ${record.package}`);
            }
          }
        }
      }
    } else if (record.status === 'optional') {
      problems.push(`optional integration ${record.capability} must name its framework peers`);
    }
    if (pageSlugs !== undefined && !pageSlugs.has(record.docs)) {
      problems.push(`integration ${record.capability} docs owner ${record.docs} is not a canonical page`);
    }
    if (!Array.isArray(record.evidence) || record.evidence.length === 0) {
      problems.push(`integration ${record.capability} has no repository evidence`);
    } else {
      for (const path of record.evidence) {
        if (
          typeof path !== 'string' ||
          path.startsWith('/') ||
          path.includes('..') ||
          /(?:^|\/)(?:drafts?|handover|roadmap)(?:\/|$)/i.test(path)
        ) {
          problems.push(`integration ${record.capability} has invalid evidence path ${String(path)}`);
        } else if (!validEvidencePath(path)) {
          problems.push(
            `integration ${record.capability} evidence ${path} is not a test, fixture, public source, or specification`,
          );
        } else if (root !== undefined && !existsSync(join(root, path))) {
          problems.push(`integration ${record.capability} evidence ${path} does not exist`);
        }
      }
    }
  }

  for (const [capability, count] of seen) {
    if (count !== 1) problems.push(`integration capability ${capability} appears ${String(count)} times`);
  }
  if (requiredCapabilities !== undefined) {
    const required = new Set(requiredCapabilities);
    for (const capability of required) {
      if (!seen.has(capability)) problems.push(`required integration capability ${capability} is missing`);
    }
    for (const capability of seen.keys()) {
      if (!required.has(capability)) problems.push(`unexpected integration capability ${capability}`);
    }
  }
  return problems.toSorted();
}

function manifestInventory(root) {
  const manifests = new Map();
  const packages = join(root, 'packages');
  if (!existsSync(packages)) return manifests;
  for (const entry of readdirSync(packages, { withFileTypes: true }).toSorted((left, right) =>
    left.name.localeCompare(right.name),
  )) {
    if (!entry.isDirectory()) continue;
    const directory = `packages/${entry.name}`;
    const path = join(root, directory, 'package.json');
    if (!existsSync(path)) continue;
    manifests.set(directory, {
      directory,
      path,
      manifest: JSON.parse(readFileSync(path, 'utf8')),
    });
  }
  return manifests;
}

function verifyManifestOwnership(rows, manifests) {
  const problems = [];
  for (const row of rows) {
    const entry = manifests.get(row.directory);
    if (entry === undefined) {
      problems.push(`catalog package directory ${row.directory} has no manifest`);
      continue;
    }
    const manifest = entry.manifest;
    if (manifest.name !== row.npmName) {
      problems.push(`catalog ${row.directory} names ${row.npmName}, manifest names ${String(manifest.name)}`);
    }
    for (const field of ['name', 'version', 'description', 'license']) {
      if (typeof manifest[field] !== 'string' || manifest[field].length === 0) {
        problems.push(`manifest ${row.directory}/package.json has no ${field}`);
      }
    }
    if (
      typeof manifest.exports !== 'object' ||
      manifest.exports === null ||
      Object.keys(manifest.exports).length === 0
    ) {
      problems.push(`manifest ${row.directory}/package.json has no exports`);
    }
    if (
      typeof manifest.engines !== 'object' ||
      manifest.engines === null ||
      Object.keys(manifest.engines).length === 0
    ) {
      problems.push(`manifest ${row.directory}/package.json has no engines`);
    }
  }
  for (const directory of manifests.keys()) {
    if (!rows.some(row => row.directory === directory)) {
      problems.push(`official package manifest ${directory}/package.json has no catalog row`);
    }
  }
  return problems.toSorted();
}

function verifyGovernanceDocumentation(root) {
  const problems = [];
  for (const [path, tokens] of Object.entries(GOVERNANCE_DOCUMENTATION)) {
    const absolute = join(root, path);
    if (!existsSync(absolute)) {
      problems.push(`${path}: executable governance documentation is missing`);
      continue;
    }
    const source = readFileSync(absolute, 'utf8');
    for (const token of tokens) {
      if (!source.includes(token)) problems.push(`${path}: executable governance command is missing: ${token}`);
    }
  }

  const architecturePath = 'docs-site/content/architecture.md';
  const architecture = join(root, architecturePath);
  if (existsSync(architecture)) {
    const source = readFileSync(architecture, 'utf8');
    if (/twenty-nine focused packages|The dependency spine is:/i.test(source)) {
      problems.push(`${architecturePath}: stale hand-maintained package count or dependency spine remains`);
    }
  }

  const publishingPath = 'PUBLISHING.md';
  const publishing = join(root, publishingPath);
  if (existsSync(publishing)) {
    const source = readFileSync(publishing, 'utf8');
    if (/\bpackages=\(/.test(source) || /\bfor\s+p\s+in\b/.test(source)) {
      problems.push(`${publishingPath}: release documentation carries a handwritten package inventory`);
    }
  }

  const overviewPath = 'docs-README.md';
  const overview = join(root, overviewPath);
  if (existsSync(overview) && /independently versionable packages/i.test(readFileSync(overview, 'utf8'))) {
    problems.push(`${overviewPath}: packages are falsely described as independently versionable`);
  }
  return problems.toSorted();
}

function renderPackageReference(rows, manifests) {
  return renderPackageReferenceRows(rows, manifests);
}

function renderIntegrations(_rows, _manifests, records) {
  return renderIntegrationRows(records);
}

function generationPlan(root) {
  const manifests = manifestInventory(root);
  const pageSlugs = new Set(PRODUCT_JOURNEY.flatMap(group => group.pages));
  const problems = [
    ...verifyManifestOwnership(PRODUCT_CATALOG, manifests),
    ...verifyIntegrationRecords(PRODUCT_CATALOG, INTEGRATIONS, {
      manifests,
      pageSlugs,
      requiredCapabilities: REQUIRED_FRAMEWORKS,
      root,
    }),
    ...verifyGovernanceDocumentation(root),
  ].toSorted();
  let architecture;
  try {
    architecture = loadArchitectureSync(root);
  } catch (error) {
    problems.push(`architecture policy could not be loaded: ${error instanceof Error ? error.message : String(error)}`);
  }
  return {
    problems: problems.toSorted(),
    outputs: GENERATED_DOCUMENTS.flatMap(document => {
      if (document.requiresArchitecture === true && architecture === undefined) return [];
      return [
        {
          ...document,
          expected: document.render(PRODUCT_CATALOG, manifests, INTEGRATIONS, architecture),
        },
      ];
    }),
  };
}

function formatProblems(problems) {
  return problems.map(problem => `[ERROR] ${problem}`).join('\n');
}

export function generateDocumentation(root = ROOT) {
  const plan = generationPlan(root);
  if (plan.problems.length > 0) throw new Error(formatProblems(plan.problems));

  const changed = [];
  for (const output of plan.outputs) {
    const path = join(root, output.path);
    const source = readFileSync(path, 'utf8');
    const { start, end } = markerTokens(output.marker);
    const next = replaceGeneratedRegion(source, start, end, output.expected);
    if (next === source) continue;
    writeFileSync(path, next);
    changed.push(output.path);
  }
  return {
    architectureDocuments: GENERATED_DOCUMENTS.filter(document => document.requiresArchitecture === true).length,
    changed,
    integrations: INTEGRATIONS.length,
    packages: PRODUCT_CATALOG.length,
  };
}

export function checkGeneratedDocumentation(root = ROOT) {
  const plan = generationPlan(root);
  const problems = [...plan.problems];
  for (const output of plan.outputs) {
    const path = join(root, output.path);
    if (!existsSync(path)) {
      problems.push(`${output.path}: generated document is missing`);
      continue;
    }
    const source = readFileSync(path, 'utf8');
    const { start, end } = markerTokens(output.marker);
    const compared = compareGeneratedRegion(source, start, end, output.expected);
    for (const problem of compared) {
      problems.push(
        `${output.path}: ${
          problem === 'generated bytes disagree with canonical sources' ? 'generated content is stale' : problem
        }`,
      );
    }
  }
  return {
    architectureDocuments: GENERATED_DOCUMENTS.filter(document => document.requiresArchitecture === true).length,
    integrations: INTEGRATIONS.length,
    packages: PRODUCT_CATALOG.length,
    problems: [...new Set(problems)].toSorted(),
  };
}

const invoked = process.argv[1];
if (invoked !== undefined && import.meta.url === pathToFileURL(resolve(invoked)).href) {
  if (process.argv.slice(2).some(argument => argument !== '--check')) {
    console.error('usage: node docs-site/generated.mjs [--check]');
    process.exitCode = 2;
  } else if (process.argv.includes('--check')) {
    const report = checkGeneratedDocumentation(ROOT);
    if (report.problems.length > 0) {
      console.error(formatProblems(report.problems));
      process.exitCode = 1;
    } else {
      console.log(
        `Generated documentation verified: ${String(report.packages)} packages, ${String(report.integrations)} framework integrations, and ${String(report.architectureDocuments)} architecture policy views.`,
      );
    }
  } else {
    const report = generateDocumentation(ROOT);
    console.log(
      `Generated documentation refreshed: ${String(report.packages)} packages, ${String(report.integrations)} framework integrations, ${String(report.architectureDocuments)} architecture policy views, ${String(report.changed.length)} changed files.`,
    );
  }
}
