// Frozen target for issue #713. This file is data, not the navigation
// implementation: #715 applies it to pages.mjs, manifest.mjs and the renderer.

export const DOCUMENTATION_BASELINE = {
  measuredOn: '2026-09-05',
  current: {
    groups: 26,
    pages: 276,
    statuses: {
      supported: 261,
      todo: 2,
      wontfix: 13,
    },
    graphqlPages: 12,
    markdownFences: 1679,
    typescriptFences: {
      total: 1354,
      ts: 1353,
      tsx: 1,
      pages: 266,
      rendererCompatible: 1349,
      rendererCompatiblePages: 265,
      redirectSourceFences: 68,
    },
  },
  target: {
    groups: 10,
    canonicalPages: 266,
    retainedCurrentPages: 264,
    addedCanonicalPages: 2,
    redirectArtifacts: 12,
  },
};

export const PRODUCT_JOURNEY = [
  {
    title: 'Start',
    pages: [
      'introduction',
      'why-zmdb',
      'quick-start',
      'installation',
      'aot-setup',
      'pure-typescript',
      'tutorial-blog-api',
      'migrate-from-drizzle',
      'migrate-from-mikro-orm',
      'migrate-from-typeorm',
      'migrate-from-sequelize',
      'migrate-from-prisma',
      'web-faq',
      'codemod',
    ],
  },
  {
    title: 'Build an application',
    pages: [
      'configuration',
      'testing',
      'cli-overview',
      'config-file',
      'cli-codegen',
      'cli-generate',
      'cli-migrate',
      'cli-push',
      'cli-pull',
      'cli-check',
      'cli-up',
      'cli-export',
      'cli-studio',
      'web-cli',
      'web-cli-monorepo',
      'web-cli-apps',
      'guides',
      'guide-conditional-filters',
      'guide-count-rows',
      'guide-cursor-pagination',
      'guide-exists-subquery',
      'guide-increment-decrement',
      'guide-toggle-boolean',
      'guide-bulk-update',
      'guide-array-defaults',
      'guide-timestamp-defaults',
      'guide-case-insensitive-unique',
      'guide-fts-generated-columns',
    ],
  },
  {
    title: 'Schema and ORM',
    pages: [
      'schema-declaration',
      'column-types',
      'type-derivation',
      'tags-reference',
      'relations',
      'composite-keys',
      'bigint-keys',
      'indexes-constraints',
      'naming-strategy',
      'json-properties',
      'views',
      'materialized-views',
      'virtual-entities',
      'sequences',
      'generated-columns',
      'schemas-namespaces',
      'rls',
      'db-extensions',
      'stored-routines',
      'schema-first',
      'custom-types',
      'embeddables',
      'inheritance',
      'crud',
      'repository',
      'select',
      'insert',
      'update',
      'delete',
      'upsert',
      'filters',
      'entity-filters',
      'pagination',
      'read-dtos',
      'projections',
      'joins',
      'populate-results',
      'loading-strategies',
      'dataloaders',
      'aggregations',
      'aggregate-results',
      'full-text-search',
      'aliases',
      'set-operations',
      'dynamic-queries',
      'query-utils',
      'raw-sql',
      'sql-comments',
      'streaming',
      'query-cancellation',
      'serialization',
      'inert-rows',
      'caching',
      'transactions',
      'batch',
      'cascading',
      'transactional-outbox',
      'read-replicas',
      'lifecycle-hooks',
      'migrations',
      'migrations-cli',
      'migrations-custom',
      'migrations-teams',
      'seeding',
      'seed-functions',
    ],
  },
  {
    title: 'Validation and contracts',
    pages: [
      'validators-is',
      'validators-assert',
      'validators-validate',
      'validators-tags',
      'validators-shallow',
      'validators-misc',
      'unions-refinements',
      'json-stringify',
      'json-parse',
      'json-schema',
      'openapi',
      'random',
      'protobuf-message',
      'protobuf-encode',
      'protobuf-decode',
      'jit-vs-aot',
      'web-validation',
      'web-openapi',
      'web-openapi-operations',
      'web-openapi-decorators',
      'web-openapi-security',
      'web-mapped-types',
    ],
  },
  {
    title: 'Server framework',
    pages: [
      'web-overview',
      'web-controllers',
      'web-context',
      'web-di',
      'web-modules',
      'web-middleware',
      'web-exception-filters',
      'web-custom-decorators',
      'web-pipeline',
      'web-app',
      'web-standalone',
      'web-request-lifecycle',
      'web-domain-state',
      'web-data-integration',
      'web-gateways',
      'web-ws-adapter',
      'web-testing',
      'web-dynamic-modules',
      'web-injection-scopes',
      'web-async-providers',
      'web-circular-dependency',
      'web-module-ref',
      'web-discovery',
      'web-lazy-modules',
      'web-router-module',
      'web-cqrs',
      'web-configuration',
      'web-logging',
      'web-caching',
      'web-request-context',
      'web-raw-body',
      'web-events',
      'web-file-upload',
      'web-streaming-files',
      'web-compression',
      'web-static-files',
      'web-versioning',
      'web-multiple-servers',
      'web-hybrid-application',
      'web-authentication',
      'web-authorization',
      'web-cors',
      'web-csrf',
      'web-encryption',
      'web-security-headers',
      'web-rate-limiting',
      'web-cookies-sessions',
      'web-faq-errors',
    ],
  },
  {
    title: 'Client applications',
    pages: [
      'framework-integrations',
      'web-http-client',
      'web-templates',
      'connect-react-native',
      'migrations-web-mobile',
      'deploy-nextjs',
    ],
  },
  {
    title: 'Databases',
    pages: [
      'dialect-postgres',
      'dialect-mysql',
      'dialect-sqlite',
      'dialect-cockroach',
      'dialect-mssql',
      'dialect-singlestore',
      'dialect-gel',
      'dialect-mongodb',
      'custom-driver',
      'drivers',
      'connect-postgres',
      'connect-sqlite',
      'connect-pglite',
      'connect-neon',
      'connect-supabase',
      'connect-vercel-postgres',
      'connect-xata',
      'connect-nile',
      'connect-prisma-postgres',
      'connect-planetscale',
      'connect-tidb',
      'connect-turso',
      'connect-sqlite-cloud',
      'connect-cloudflare-d1',
      'connect-cloudflare-do',
      'connect-aws-data-api',
      'connect-bun',
      'connect-http-proxy',
      'guide-vector-search',
      'guide-postgis',
      'guide-local-postgres',
      'guide-local-mysql',
    ],
  },
  {
    title: 'Operations and deployment',
    pages: [
      'logging',
      'perf-queries',
      'perf-serverless',
      'deployment',
      'tutorials',
      'deploy-vercel',
      'deploy-netlify',
      'deploy-supabase-edge',
      'deploy-railway',
      'deploy-encore',
      'web-task-scheduling',
      'web-queues',
      'web-performance',
      'web-health-checks',
      'web-observability',
      'web-tracing',
      'web-devtools',
      'web-hot-reload',
      'web-repl',
      'web-serverless',
      'web-deployment',
    ],
  },
  {
    title: 'Ecosystem integrations',
    pages: [
      'llm-function-calling',
      'llm-json-schema',
      'llm-structured-output',
      'llm-strategy',
      'llm-chat',
      'llm-http',
      'llm-mcp',
      'llm-langchain',
      'llm-vercel-ai-sdk',
      'interop-zod',
      'interop-valibot',
      'interop-typebox',
      'interop-arktype',
      'interop-effect-schema',
      'interop-trpc',
      'interop-hono',
      'web-microservices',
      'web-microservices-transports',
      'web-microservices-grpc',
      'web-microservices-custom-transport',
      'graphql',
    ],
  },
  {
    title: 'Reference',
    pages: [
      'architecture',
      'faq',
      'gotchas',
      'goodies',
      'lint-rules',
      'anti-patterns',
      'benchmarks',
      'web-benchmarks',
      'package-reference',
    ],
  },
];

export const CANONICAL_PAGE_ADDITIONS = {
  graphql: {
    title: 'GraphQL',
    group: 'Ecosystem integrations',
    status: 'wontfix',
  },
  'package-reference': {
    title: 'Package reference',
    group: 'Reference',
    status: 'supported',
  },
};

export const LEGACY_REDIRECTS = {
  'web-graphql': 'graphql',
  'web-graphql-resolvers': 'graphql',
  'web-graphql-subscriptions': 'graphql',
  'web-graphql-scalars': 'graphql',
  'web-graphql-mapped-types': 'graphql',
  'web-graphql-directives': 'graphql',
  'web-graphql-plugins': 'graphql',
  'web-graphql-complexity': 'graphql',
  'web-graphql-field-middleware': 'graphql',
  'web-graphql-middleware': 'graphql',
  'web-graphql-federation': 'graphql',
  'web-graphql-schema-first': 'graphql',
};
