// zmdb docs page registry — metadata only. Page bodies live in ./content/<slug>.md
// so a ~400-page manual stays reviewable: this file is the table of contents,
// content/ is the prose. manifest.mjs joins the two.
//
//   status:'supported' -> the API is real; the page documents it
//   status:'todo'      -> a legitimate capability we have not built yet (roadmap,
//                         NOT an anti-pattern). `note` says what is missing.
//
// Anti-patterns are deliberately absent from NAV and enumerated, with rationale,
// in coverage/mapping.mjs + the anti-patterns page.

export const NAV = [
  {
    title: 'Getting Started',
    pages: [
      'introduction',
      'why-zmdb',
      'quick-start',
      'installation',
      'aot-setup',
      'pure-typescript',
      'tutorial-blog-api',
      'architecture',
      'faq',
      'gotchas',
      'goodies',
    ],
  },
  {
    title: 'Migrating to zmdb',
    pages: [
      'migrate-from-drizzle',
      'migrate-from-mikro-orm',
      'migrate-from-typeorm',
      'migrate-from-sequelize',
      'migrate-from-prisma',
      'web-faq',
      'codemod',
    ],
  },
  {
    title: 'Schema',
    pages: [
      'schema-declaration',
      'column-types',
      'type-derivation',
      'tags-reference',
      'relations',
      'composite-keys',
      'bigint-keys',
      'indexes-constraints',
      'naming-strategy',
      'json-properties',
      'views',
      'materialized-views',
      'virtual-entities',
      'sequences',
      'generated-columns',
      'schemas-namespaces',
      'rls',
      'db-extensions',
      'stored-routines',
      'schema-first',
    ],
  },
  {
    title: 'Data Access',
    pages: [
      'crud',
      'repository',
      'select',
      'insert',
      'update',
      'delete',
      'upsert',
      'filters',
      'entity-filters',
      'pagination',
      'read-dtos',
      'projections',
      'joins',
      'populate-results',
      'loading-strategies',
      'dataloaders',
      'aggregations',
      'aggregate-results',
      'full-text-search',
      'aliases',
      'set-operations',
      'dynamic-queries',
      'query-utils',
      'raw-sql',
      'sql-comments',
      'streaming',
      'query-cancellation',
      'serialization',
      'inert-rows',
    ],
  },
  {
    title: 'Transactions',
    pages: ['transactions', 'batch', 'cascading', 'transactional-outbox', 'read-replicas', 'lifecycle-hooks'],
  },
  {
    title: 'Migrations',
    pages: [
      'migrations',
      'migrations-cli',
      'migrations-custom',
      'migrations-teams',
      'migrations-web-mobile',
      'seeding',
      'seed-functions',
    ],
  },
  {
    title: 'CLI',
    pages: [
      'cli-overview',
      'config-file',
      'cli-codegen',
      'cli-generate',
      'cli-migrate',
      'cli-push',
      'cli-pull',
      'cli-check',
      'cli-up',
      'cli-export',
      'cli-studio',
    ],
  },
  {
    title: 'Dialects',
    pages: [
      'dialect-postgres',
      'dialect-mysql',
      'dialect-sqlite',
      'dialect-cockroach',
      'dialect-mssql',
      'dialect-singlestore',
      'dialect-gel',
      'dialect-mongodb',
      'custom-driver',
    ],
  },
  {
    title: 'Connecting',
    pages: [
      'drivers',
      'connect-postgres',
      'connect-sqlite',
      'connect-pglite',
      'connect-neon',
      'connect-supabase',
      'connect-vercel-postgres',
      'connect-xata',
      'connect-nile',
      'connect-prisma-postgres',
      'connect-planetscale',
      'connect-tidb',
      'connect-turso',
      'connect-sqlite-cloud',
      'connect-cloudflare-d1',
      'connect-cloudflare-do',
      'connect-aws-data-api',
      'connect-bun',
      'connect-http-proxy',
      'connect-react-native',
    ],
  },
  {
    title: 'Validation',
    pages: [
      'validators-is',
      'validators-assert',
      'validators-validate',
      'validators-tags',
      'validators-shallow',
      'validators-misc',
      'unions-refinements',
    ],
  },
  {
    title: 'JSON & Serialization',
    pages: [
      'json-stringify',
      'json-parse',
      'json-schema',
      'openapi',
      'random',
      'protobuf-message',
      'protobuf-encode',
      'protobuf-decode',
    ],
  },
  {
    title: 'LLM',
    pages: [
      'llm-function-calling',
      'llm-json-schema',
      'llm-structured-output',
      'llm-strategy',
      'llm-chat',
      'llm-http',
      'llm-mcp',
      'llm-langchain',
      'llm-vercel-ai-sdk',
    ],
  },
  {
    title: 'Advanced',
    pages: [
      'custom-types',
      'embeddables',
      'inheritance',
      'configuration',
      'logging',
      'caching',
      'testing',
      'jit-vs-aot',
      'perf-queries',
      'perf-serverless',
      'deployment',
      'lint-rules',
    ],
  },
  {
    title: 'Interop',
    pages: [
      'interop-zod',
      'interop-valibot',
      'interop-typebox',
      'interop-arktype',
      'interop-effect-schema',
      'interop-trpc',
      'interop-hono',
      'framework-integrations',
    ],
  },
  {
    title: 'Guides',
    pages: [
      'guides',
      'guide-conditional-filters',
      'guide-count-rows',
      'guide-cursor-pagination',
      'guide-exists-subquery',
      'guide-increment-decrement',
      'guide-toggle-boolean',
      'guide-bulk-update',
      'guide-array-defaults',
      'guide-timestamp-defaults',
      'guide-case-insensitive-unique',
      'guide-fts-generated-columns',
      'guide-vector-search',
      'guide-postgis',
      'guide-local-postgres',
      'guide-local-mysql',
    ],
  },
  {
    title: 'Deploying',
    pages: [
      'tutorials',
      'deploy-vercel',
      'deploy-nextjs',
      'deploy-netlify',
      'deploy-supabase-edge',
      'deploy-railway',
      'deploy-encore',
    ],
  },
  {
    title: 'Web Framework',
    pages: [
      'web-overview',
      'web-controllers',
      'web-context',
      'web-di',
      'web-modules',
      'web-middleware',
      'web-exception-filters',
      'web-custom-decorators',
      'web-pipeline',
      'web-app',
      'web-standalone',
      'web-request-lifecycle',
      'web-validation',
      'web-domain-state',
      'web-data-integration',
      'web-gateways',
      'web-ws-adapter',
      'web-testing',
      'web-benchmarks',
    ],
  },
  {
    title: 'Web Framework — DI & Modules',
    pages: [
      'web-dynamic-modules',
      'web-injection-scopes',
      'web-async-providers',
      'web-circular-dependency',
      'web-module-ref',
      'web-discovery',
      'web-lazy-modules',
      'web-router-module',
      'web-cqrs',
    ],
  },
  {
    title: 'Web Framework — OpenAPI',
    pages: [
      'web-openapi',
      'web-openapi-operations',
      'web-openapi-decorators',
      'web-openapi-security',
      'web-mapped-types',
    ],
  },
  {
    title: 'Web Framework — Techniques',
    pages: [
      'web-configuration',
      'web-logging',
      'web-caching',
      'web-request-context',
      'web-raw-body',
      'web-events',
      'web-http-client',
      'web-file-upload',
      'web-streaming-files',
      'web-compression',
      'web-static-files',
      'web-templates',
      'web-task-scheduling',
      'web-queues',
      'web-versioning',
      'web-performance',
      'web-health-checks',
      'web-observability',
      'web-tracing',
      'web-devtools',
      'web-hot-reload',
      'web-repl',
      'web-multiple-servers',
      'web-hybrid-application',
      'web-serverless',
      'web-deployment',
    ],
  },
  {
    title: 'Web Framework — Security',
    pages: [
      'web-authentication',
      'web-authorization',
      'web-cors',
      'web-csrf',
      'web-encryption',
      'web-security-headers',
      'web-rate-limiting',
      'web-cookies-sessions',
    ],
  },
  {
    title: 'Web Framework — CLI',
    pages: ['web-cli', 'web-cli-monorepo', 'web-cli-apps'],
  },
  {
    title: 'Web Framework — Microservices',
    pages: [
      'web-microservices',
      'web-microservices-transports',
      'web-microservices-grpc',
      'web-microservices-custom-transport',
    ],
  },
  {
    title: 'Web Framework — GraphQL',
    pages: [
      'web-graphql',
      'web-graphql-resolvers',
      'web-graphql-subscriptions',
      'web-graphql-scalars',
      'web-graphql-mapped-types',
      'web-graphql-directives',
      'web-graphql-plugins',
      'web-graphql-complexity',
      'web-graphql-field-middleware',
      'web-graphql-middleware',
      'web-graphql-federation',
      'web-graphql-schema-first',
    ],
  },
  {
    title: 'Web Framework — FAQ',
    pages: ['web-faq-errors'],
  },
  {
    title: 'Reference',
    pages: ['anti-patterns', 'benchmarks'],
  },
];

export const PAGE_META = {
  introduction: {
    title: 'Introduction',
    group: 'Getting Started',
    status: 'supported',
  },
  'why-zmdb': {
    title: 'Why zmdb',
    group: 'Getting Started',
    status: 'supported',
  },
  'quick-start': {
    title: 'Quick Start',
    group: 'Getting Started',
    status: 'supported',
  },
  installation: {
    title: 'Installation',
    group: 'Getting Started',
    status: 'supported',
  },
  'aot-setup': {
    title: 'AOT Setup (transformer)',
    group: 'Getting Started',
    status: 'supported',
  },
  'pure-typescript': {
    title: 'Pure TypeScript',
    group: 'Getting Started',
    status: 'supported',
  },
  'tutorial-blog-api': {
    title: 'Tutorial: a blog API end to end',
    group: 'Getting Started',
    status: 'supported',
  },
  architecture: {
    title: 'Architecture',
    group: 'Getting Started',
    status: 'supported',
  },
  faq: {
    title: 'FAQ',
    group: 'Getting Started',
    status: 'supported',
  },
  gotchas: {
    title: 'Gotchas',
    group: 'Getting Started',
    status: 'supported',
  },
  goodies: {
    title: 'Goodies',
    group: 'Getting Started',
    status: 'supported',
  },
  'migrate-from-drizzle': {
    title: 'From Drizzle ORM',
    group: 'Migrating to zmdb',
    status: 'supported',
  },
  'migrate-from-mikro-orm': {
    title: 'From MikroORM',
    group: 'Migrating to zmdb',
    status: 'supported',
  },
  'migrate-from-typeorm': {
    title: 'From TypeORM',
    group: 'Migrating to zmdb',
    status: 'supported',
  },
  'migrate-from-sequelize': {
    title: 'From Sequelize',
    group: 'Migrating to zmdb',
    status: 'supported',
  },
  'migrate-from-prisma': {
    title: 'From Prisma',
    group: 'Migrating to zmdb',
    status: 'supported',
  },
  'web-faq': {
    title: 'FAQ — Migrating from NestJS',
    group: 'Migrating to zmdb',
    status: 'supported',
  },
  codemod: {
    title: 'Codemod: defineSchema → a type',
    group: 'Migrating to zmdb',
    status: 'supported',
  },
  'schema-declaration': {
    title: 'Schema Declaration',
    group: 'Schema',
    status: 'supported',
  },
  'column-types': {
    title: 'Column Types',
    group: 'Schema',
    status: 'supported',
  },
  'type-derivation': {
    title: 'Type Derivation',
    group: 'Schema',
    status: 'supported',
  },
  'tags-reference': {
    title: 'Tag Reference',
    group: 'Schema',
    status: 'supported',
  },
  relations: {
    title: 'Relations',
    group: 'Schema',
    status: 'supported',
  },
  'composite-keys': {
    title: 'Composite Primary Keys',
    group: 'Schema',
    status: 'todo',
    note: 'the key derives and queries correctly; the DDL emitter writes one PRIMARY KEY per column and keyset pagination reads only the first',
  },
  'bigint-keys': {
    title: 'bigint Primary Keys',
    group: 'Schema',
    status: 'supported',
  },
  'indexes-constraints': {
    title: 'Indexes & Constraints',
    group: 'Schema',
    status: 'supported',
  },
  'naming-strategy': {
    title: 'Naming Strategy',
    group: 'Schema',
    status: 'todo',
    note: 'table and column names are used verbatim; there is no pluralisation / snake_case strategy hook',
  },
  'json-properties': {
    title: 'JSON Properties',
    group: 'Schema',
    status: 'supported',
  },
  views: {
    title: 'Views',
    group: 'Schema',
    status: 'supported',
  },
  'materialized-views': {
    title: 'Materialized Views',
    group: 'Schema',
    status: 'supported',
  },
  'virtual-entities': {
    title: 'Virtual Entities',
    group: 'Schema',
    status: 'supported',
  },
  sequences: {
    title: 'Sequences',
    group: 'Schema',
    status: 'supported',
  },
  'generated-columns': {
    title: 'Generated Columns',
    group: 'Schema',
    status: 'supported',
  },
  'schemas-namespaces': {
    title: 'Schemas / Namespaces',
    group: 'Schema',
    status: 'supported',
  },
  rls: {
    title: 'Row-Level Security (RLS)',
    group: 'Schema',
    status: 'supported',
  },
  'db-extensions': {
    title: 'Database Extensions',
    group: 'Schema',
    status: 'todo',
    note: 'no CREATE EXTENSION emitter and no extension-backed column types (vector, geometry, citext)',
  },
  'stored-routines': {
    title: 'Stored Procedures & Functions',
    group: 'Schema',
    status: 'todo',
    note: 'no procedure/function DDL emitter and no typed call site',
  },
  'schema-first': {
    title: 'Schema-First (existing database)',
    group: 'Schema',
    status: 'todo',
    note: 'no introspection: schema objects are the only source of truth, there is no DDL-to-schema direction',
  },
  crud: {
    title: 'CRUD',
    group: 'Data Access',
    status: 'supported',
  },
  repository: {
    title: 'Repository',
    group: 'Data Access',
    status: 'supported',
  },
  select: {
    title: 'Select',
    group: 'Data Access',
    status: 'supported',
  },
  insert: {
    title: 'Insert',
    group: 'Data Access',
    status: 'supported',
  },
  update: {
    title: 'Update',
    group: 'Data Access',
    status: 'supported',
  },
  delete: {
    title: 'Delete',
    group: 'Data Access',
    status: 'supported',
  },
  upsert: {
    title: 'Upsert',
    group: 'Data Access',
    status: 'todo',
    note: 'the insert builder has no ON CONFLICT / ON DUPLICATE KEY clause',
  },
  filters: {
    title: 'Filters & Operators',
    group: 'Data Access',
    status: 'supported',
  },
  'entity-filters': {
    title: 'Entity Filters (soft delete)',
    group: 'Data Access',
    status: 'todo',
    note: 'no schema-level filter registry that is applied implicitly to every query',
  },
  pagination: {
    title: 'Ordering & Pagination',
    group: 'Data Access',
    status: 'supported',
  },
  'read-dtos': {
    title: 'Read/Query DTOs — Get / List / Search',
    group: 'Data Access',
    status: 'supported',
  },
  projections: {
    title: 'Projections (partial select)',
    group: 'Data Access',
    status: 'supported',
  },
  joins: {
    title: 'Joins',
    group: 'Data Access',
    status: 'supported',
  },
  'populate-results': {
    title: 'Typed Populate & Join Results',
    group: 'Data Access',
    status: 'supported',
  },
  'loading-strategies': {
    title: 'Loading Strategies',
    group: 'Data Access',
    status: 'supported',
  },
  dataloaders: {
    title: 'DataLoaders',
    group: 'Data Access',
    status: 'todo',
    note: 'populate batches one query per relation per call; there is no request-scoped loader that batches across calls',
  },
  aggregations: {
    title: 'Aggregations',
    group: 'Data Access',
    status: 'supported',
  },
  'aggregate-results': {
    title: 'Typed Aggregate Results',
    group: 'Data Access',
    status: 'supported',
  },
  'full-text-search': {
    title: 'Full-Text Search',
    group: 'Data Access',
    status: 'supported',
  },
  aliases: {
    title: 'Aliases',
    group: 'Data Access',
    status: 'supported',
  },
  'set-operations': {
    title: 'Set Operations',
    group: 'Data Access',
    status: 'supported',
  },
  'dynamic-queries': {
    title: 'Dynamic Query Building',
    group: 'Data Access',
    status: 'supported',
  },
  'query-utils': {
    title: 'Query Utilities',
    group: 'Data Access',
    status: 'supported',
  },
  'raw-sql': {
    title: 'Raw SQL',
    group: 'Data Access',
    status: 'supported',
  },
  'sql-comments': {
    title: 'SQL Comments',
    group: 'Data Access',
    status: 'todo',
    note: 'the compiler emits no comment markers; the sqlcommenter format, closed key set and escaping rules are frozen (#579) and asserted by expected-failing tests (#580)',
  },
  streaming: {
    title: 'Streaming Results',
    group: 'Data Access',
    status: 'todo',
    note: 'Driver.execute resolves to a materialised array; there is no cursor or async-iterable path',
  },
  'query-cancellation': {
    title: 'Query Cancellation',
    group: 'Data Access',
    status: 'todo',
    note: 'no AbortSignal is threaded through Driver.execute',
  },
  serialization: {
    title: 'Serialization',
    group: 'Data Access',
    status: 'supported',
  },
  'inert-rows': {
    title: 'Why Fetched Rows Are Inert',
    group: 'Data Access',
    status: 'supported',
  },
  transactions: {
    title: 'Transactions',
    group: 'Transactions',
    status: 'supported',
  },
  batch: {
    title: 'Batch API',
    group: 'Transactions',
    status: 'supported',
  },
  cascading: {
    title: 'Cascading',
    group: 'Transactions',
    status: 'todo',
    note: 'references() records the FK target only — no ON DELETE / ON UPDATE action and no application-level cascade',
  },
  'transactional-outbox': {
    title: 'Transactional Outbox',
    group: 'Transactions',
    status: 'todo',
    note: 'no outbox table helper and no dispatcher loop; both are frozen (#592), and the consumer half is frozen too (#586).',
  },
  'read-replicas': {
    title: 'Read Replicas',
    group: 'Transactions',
    status: 'supported',
  },
  'lifecycle-hooks': {
    title: 'Lifecycle Hooks & Events',
    group: 'Transactions',
    status: 'supported',
  },
  migrations: {
    title: 'Migrations',
    group: 'Migrations',
    status: 'supported',
  },
  'migrations-cli': {
    title: 'Migrations CLI',
    group: 'Migrations',
    status: 'supported',
  },
  'migrations-custom': {
    title: 'Custom Migrations',
    group: 'Migrations',
    status: 'supported',
  },
  'migrations-teams': {
    title: 'Migrations in a Team',
    group: 'Migrations',
    status: 'supported',
  },
  'migrations-web-mobile': {
    title: 'Migrations on Web & Mobile',
    group: 'Migrations',
    status: 'todo',
    note: 'no bundler-embedded migration runner; depends on the React Native build path',
  },
  seeding: {
    title: 'Seeding',
    group: 'Migrations',
    status: 'supported',
  },
  'seed-functions': {
    title: 'Seed Value Generators',
    group: 'Migrations',
    status: 'supported',
  },
  'cli-overview': {
    title: 'CLI Overview',
    group: 'CLI',
    status: 'todo',
    note: 'there is no zmdb executable; the snapshot / diff / DDL engine is a library API you call from a script',
  },
  'config-file': {
    title: 'Config File',
    group: 'CLI',
    status: 'todo',
    note: 'no zmdb.config.ts loader',
  },
  'cli-codegen': {
    title: 'zmdb-codegen',
    group: 'CLI',
    status: 'supported',
  },
  'cli-generate': {
    title: 'generate',
    group: 'CLI',
    status: 'todo',
    note: 'no CLI wrapper around snapshot() + diff() + emitUp()',
  },
  'cli-migrate': {
    title: 'migrate',
    group: 'CLI',
    status: 'todo',
    note: 'no CLI wrapper around the migration runner',
  },
  'cli-push': {
    title: 'push',
    group: 'CLI',
    status: 'todo',
    note: 'no CLI wrapper around direct DDL application',
  },
  'cli-pull': {
    title: 'pull (introspect)',
    group: 'CLI',
    status: 'todo',
    note: 'no database introspection: nothing reads a live catalogue back into a schema object',
  },
  'cli-check': {
    title: 'check',
    group: 'CLI',
    status: 'todo',
    note: 'no CLI wrapper around snapshot conflict detection',
  },
  'cli-up': {
    title: 'up',
    group: 'CLI',
    status: 'todo',
    note: 'no snapshot format upgrader',
  },
  'cli-export': {
    title: 'export',
    group: 'CLI',
    status: 'todo',
    note: 'no CLI wrapper that prints the full DDL for a schema set',
  },
  'cli-studio': {
    title: 'studio',
    group: 'CLI',
    status: 'todo',
    note: 'no data browser',
  },
  'dialect-postgres': {
    title: 'PostgreSQL',
    group: 'Dialects',
    status: 'supported',
  },
  'dialect-mysql': {
    title: 'MySQL',
    group: 'Dialects',
    status: 'supported',
  },
  'dialect-sqlite': {
    title: 'SQLite',
    group: 'Dialects',
    status: 'supported',
  },
  'dialect-cockroach': {
    title: 'CockroachDB',
    group: 'Dialects',
    status: 'todo',
    note: 'not a Dialect value; the postgres dialect works over the wire but Cockroach-specific DDL and types are unhandled',
  },
  'dialect-mssql': {
    title: 'SQL Server',
    group: 'Dialects',
    status: 'todo',
    note: 'no mssql dialect: different placeholder syntax, quoting, LIMIT form and type set',
  },
  'dialect-singlestore': {
    title: 'SingleStore',
    group: 'Dialects',
    status: 'todo',
    note: 'not a Dialect value; the mysql dialect works over the wire but columnstore DDL is unhandled',
  },
  'dialect-gel': {
    title: 'Gel (EdgeDB)',
    group: 'Dialects',
    status: 'todo',
    note: 'no Gel support: EdgeQL is not SQL, so it needs a second compiler target',
  },
  'dialect-mongodb': {
    title: 'MongoDB',
    group: 'Dialects',
    status: 'todo',
    note: 'the compiler emits SQL text; a document store needs a separate compiler target',
  },
  'custom-driver': {
    title: 'Writing a Driver',
    group: 'Dialects',
    status: 'supported',
  },
  drivers: {
    title: 'Drivers',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-postgres': {
    title: 'PostgreSQL (node-postgres)',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-sqlite': {
    title: 'SQLite (node:sqlite)',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-pglite': {
    title: 'PGlite',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-neon': {
    title: 'Neon',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-supabase': {
    title: 'Supabase',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-vercel-postgres': {
    title: 'Vercel Postgres',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-xata': {
    title: 'Xata',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-nile': {
    title: 'Nile',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-prisma-postgres': {
    title: 'Prisma Postgres',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-planetscale': {
    title: 'PlanetScale',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-tidb': {
    title: 'TiDB Cloud',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-turso': {
    title: 'Turso / libSQL',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-sqlite-cloud': {
    title: 'SQLite Cloud',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-cloudflare-d1': {
    title: 'Cloudflare D1',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-cloudflare-do': {
    title: 'Cloudflare Durable Objects',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-aws-data-api': {
    title: 'AWS RDS Data API',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-bun': {
    title: 'Bun',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-http-proxy': {
    title: 'HTTP Proxy',
    group: 'Connecting',
    status: 'supported',
  },
  'connect-react-native': {
    title: 'React Native & Expo',
    group: 'Connecting',
    status: 'todo',
    note: 'no Metro plugin for the AOT transformer, so schemas and validators are not transformed in an RN bundle',
  },
  'validators-is': {
    title: 'is()',
    group: 'Validation',
    status: 'supported',
  },
  'validators-assert': {
    title: 'assert()',
    group: 'Validation',
    status: 'supported',
  },
  'validators-validate': {
    title: 'validate()',
    group: 'Validation',
    status: 'supported',
  },
  'validators-tags': {
    title: 'Special Tags',
    group: 'Validation',
    status: 'supported',
  },
  'validators-shallow': {
    title: 'Shallow Validation',
    group: 'Validation',
    status: 'todo',
    note: 'no depth-limited validator variant; is()/assert() always walk the whole tree',
  },
  'validators-misc': {
    title: 'equals, prune & other utilities',
    group: 'Validation',
    status: 'supported',
  },
  'unions-refinements': {
    title: 'Unions, Refinements & Transforms',
    group: 'Validation',
    status: 'supported',
  },
  'json-stringify': {
    title: 'stringify()',
    group: 'JSON & Serialization',
    status: 'supported',
  },
  'json-parse': {
    title: 'parse()',
    group: 'JSON & Serialization',
    status: 'supported',
  },
  'json-schema': {
    title: 'JSON Schema',
    group: 'JSON & Serialization',
    status: 'supported',
  },
  openapi: {
    title: 'OpenAPI',
    group: 'JSON & Serialization',
    status: 'supported',
  },
  random: {
    title: 'Random Generator',
    group: 'JSON & Serialization',
    status: 'supported',
  },
  'protobuf-message': {
    title: 'Protobuf Messages',
    group: 'JSON & Serialization',
    status: 'todo',
    note: 'no protobuf schema derivation from TypeScript types',
  },
  'protobuf-encode': {
    title: 'protobuf encode',
    group: 'JSON & Serialization',
    status: 'todo',
    note: 'no protobuf wire encoder',
  },
  'protobuf-decode': {
    title: 'protobuf decode',
    group: 'JSON & Serialization',
    status: 'todo',
    note: 'no protobuf wire decoder',
  },
  'llm-function-calling': {
    title: 'LLM Function Calling',
    group: 'LLM',
    status: 'supported',
  },
  'llm-json-schema': {
    title: 'LLM Schemas',
    group: 'LLM',
    status: 'supported',
  },
  'llm-structured-output': {
    title: 'Structured Output',
    group: 'LLM',
    status: 'supported',
  },
  'llm-strategy': {
    title: 'Provider Schema Strategies',
    group: 'LLM',
    status: 'todo',
    note: 'toolFromSchema emits one JSON Schema shape; no per-provider dialect (OpenAI / Claude / Gemini) switch',
  },
  'llm-chat': {
    title: 'Chat & Agents',
    group: 'LLM',
    status: 'todo',
    note: 'no chat loop, message types or agent driver',
  },
  'llm-http': {
    title: 'HTTP Tools from Controllers',
    group: 'LLM',
    status: 'todo',
    note: 'no generator that turns an OpenAPI document into callable tool specs',
  },
  'llm-mcp': {
    title: 'Model Context Protocol',
    group: 'LLM',
    status: 'todo',
    note: 'no MCP server or client',
  },
  'llm-langchain': {
    title: 'LangChain',
    group: 'LLM',
    status: 'todo',
    note: 'no LangChain tool adapter',
  },
  'llm-vercel-ai-sdk': {
    title: 'Vercel AI SDK',
    group: 'LLM',
    status: 'todo',
    note: 'no AI SDK tool adapter',
  },
  'custom-types': {
    title: 'Custom Types & Codecs',
    group: 'Advanced',
    status: 'supported',
  },
  embeddables: {
    title: 'Embeddables',
    group: 'Advanced',
    status: 'supported',
  },
  inheritance: {
    title: 'Inheritance Mapping',
    group: 'Advanced',
    status: 'supported',
  },
  configuration: {
    title: 'Configuration',
    group: 'Advanced',
    status: 'supported',
  },
  logging: {
    title: 'Logging',
    group: 'Advanced',
    status: 'supported',
  },
  caching: {
    title: 'Query Caching',
    group: 'Advanced',
    status: 'todo',
    note: 'no result cache: every read reaches the driver',
  },
  testing: {
    title: 'Testing',
    group: 'Advanced',
    status: 'supported',
  },
  'jit-vs-aot': {
    title: 'AOT vs JIT',
    group: 'Advanced',
    status: 'supported',
  },
  'perf-queries': {
    title: 'Query Performance',
    group: 'Advanced',
    status: 'supported',
  },
  'perf-serverless': {
    title: 'Serverless Performance',
    group: 'Advanced',
    status: 'supported',
  },
  deployment: {
    title: 'Deployment',
    group: 'Advanced',
    status: 'supported',
  },
  'lint-rules': {
    title: 'Lint Rules',
    group: 'Advanced',
    status: 'todo',
    note: 'no shipped oxlint/ESLint plugin for schema and query mistakes',
  },
  'interop-zod': {
    title: 'Zod',
    group: 'Interop',
    status: 'supported',
  },
  'interop-valibot': {
    title: 'Valibot',
    group: 'Interop',
    status: 'supported',
  },
  'interop-typebox': {
    title: 'TypeBox',
    group: 'Interop',
    status: 'supported',
  },
  'interop-arktype': {
    title: 'ArkType',
    group: 'Interop',
    status: 'supported',
  },
  'interop-effect-schema': {
    title: 'Effect Schema',
    group: 'Interop',
    status: 'supported',
  },
  'interop-trpc': {
    title: 'tRPC',
    group: 'Interop',
    status: 'supported',
  },
  'interop-hono': {
    title: 'Hono',
    group: 'Interop',
    status: 'supported',
  },
  'framework-integrations': {
    title: 'Framework Integrations',
    group: 'Interop',
    status: 'supported',
  },
  guides: {
    title: 'Guides',
    group: 'Guides',
    status: 'supported',
  },
  'guide-conditional-filters': {
    title: 'Conditional filters',
    group: 'Guides',
    status: 'supported',
  },
  'guide-count-rows': {
    title: 'Counting rows',
    group: 'Guides',
    status: 'supported',
  },
  'guide-cursor-pagination': {
    title: 'Cursor-based pagination',
    group: 'Guides',
    status: 'supported',
  },
  'guide-exists-subquery': {
    title: 'Parents with at least one child',
    group: 'Guides',
    status: 'supported',
  },
  'guide-increment-decrement': {
    title: 'Incrementing and decrementing a value',
    group: 'Guides',
    status: 'todo',
    note: 'UpdateBuilder.set() takes values only, so an update cannot reference the current column value',
  },
  'guide-toggle-boolean': {
    title: 'Toggling a boolean',
    group: 'Guides',
    status: 'todo',
    note: 'same gap as increment/decrement: no column references in SET',
  },
  'guide-bulk-update': {
    title: 'Updating many rows to different values',
    group: 'Guides',
    status: 'todo',
    note: 'same gap as increment/decrement: no CASE expression in SET',
  },
  'guide-array-defaults': {
    title: 'Array columns and empty defaults',
    group: 'Guides',
    status: 'supported',
  },
  'guide-timestamp-defaults': {
    title: 'Timestamp defaults',
    group: 'Guides',
    status: 'supported',
  },
  'guide-case-insensitive-unique': {
    title: 'Case-insensitive unique email',
    group: 'Guides',
    status: 'todo',
    note: 'IndexDef takes column names, not expressions, so a functional index on lower(email) cannot be emitted',
  },
  'guide-fts-generated-columns': {
    title: 'Full-text search with a generated column',
    group: 'Guides',
    status: 'supported',
  },
  'guide-vector-search': {
    title: 'Vector similarity search',
    group: 'Guides',
    status: 'todo',
    note: 'no vector column type and no distance operators; depends on database extensions',
  },
  'guide-postgis': {
    title: 'Geometry and point columns',
    group: 'Guides',
    status: 'todo',
    note: 'no geometry/point column type; depends on database extensions',
  },
  'guide-local-postgres': {
    title: 'A local PostgreSQL',
    group: 'Guides',
    status: 'supported',
  },
  'guide-local-mysql': {
    title: 'A local MySQL',
    group: 'Guides',
    status: 'supported',
  },
  tutorials: {
    title: 'Deployment Tutorials',
    group: 'Deploying',
    status: 'supported',
  },
  'deploy-vercel': {
    title: 'Vercel',
    group: 'Deploying',
    status: 'supported',
  },
  'deploy-nextjs': {
    title: 'Next.js',
    group: 'Deploying',
    status: 'supported',
  },
  'deploy-netlify': {
    title: 'Netlify',
    group: 'Deploying',
    status: 'supported',
  },
  'deploy-supabase-edge': {
    title: 'Supabase Edge Functions',
    group: 'Deploying',
    status: 'supported',
  },
  'deploy-railway': {
    title: 'Railway',
    group: 'Deploying',
    status: 'supported',
  },
  'deploy-encore': {
    title: 'Encore',
    group: 'Deploying',
    status: 'supported',
  },
  'web-overview': {
    title: '@zmdb/web — Overview',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-controllers': {
    title: 'Controllers & Routing',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-context': {
    title: 'Typed Request Context',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-di': {
    title: 'Dependency Injection',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-modules': {
    title: 'Modules & Providers',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-middleware': {
    title: 'Guards, Pipes, Interceptors & Filters',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-exception-filters': {
    title: 'Exception Filters',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-custom-decorators': {
    title: 'Custom Decorators',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-pipeline': {
    title: 'Request Pipeline & Adapters',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-app': {
    title: 'Application Bootstrap & Lifecycle',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-standalone': {
    title: 'Standalone Applications',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-request-lifecycle': {
    title: 'Request Lifecycle',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-validation': {
    title: 'Validation & Serialization',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-domain-state': {
    title: 'Domain State Machines',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-data-integration': {
    title: 'Building an API with zmdb',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-gateways': {
    title: 'WebSockets & SSE',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-ws-adapter': {
    title: 'WebSocket Adapters',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-testing': {
    title: 'Testing',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-benchmarks': {
    title: 'Web Performance & Benchmarks',
    group: 'Web Framework',
    status: 'supported',
  },
  'web-dynamic-modules': {
    title: 'Dynamic Modules',
    group: 'Web Framework — DI & Modules',
    status: 'supported',
  },
  'web-injection-scopes': {
    title: 'Injection Scopes',
    group: 'Web Framework — DI & Modules',
    status: 'supported',
  },
  'web-async-providers': {
    title: 'Asynchronous Providers',
    group: 'Web Framework — DI & Modules',
    status: 'supported',
  },
  'web-circular-dependency': {
    title: 'Circular Dependencies',
    group: 'Web Framework — DI & Modules',
    status: 'supported',
  },
  'web-module-ref': {
    title: 'Module Reference',
    group: 'Web Framework — DI & Modules',
    status: 'supported',
  },
  'web-discovery': {
    title: 'Discovery & Introspection',
    group: 'Web Framework — DI & Modules',
    status: 'supported',
  },
  'web-lazy-modules': {
    title: 'Lazy-Loading Modules',
    group: 'Web Framework — DI & Modules',
    status: 'todo',
    note: 'compileModule resolves the whole graph at createApp; there is no lazy module loader',
  },
  'web-router-module': {
    title: 'Route Composition',
    group: 'Web Framework — DI & Modules',
    status: 'supported',
  },
  'web-cqrs': {
    title: 'CQRS',
    group: 'Web Framework — DI & Modules',
    status: 'todo',
    note: 'no command/query bus or saga runtime',
  },
  'web-openapi': {
    title: 'OpenAPI Generation',
    group: 'Web Framework — OpenAPI',
    status: 'supported',
  },
  'web-openapi-operations': {
    title: 'Operations & Responses',
    group: 'Web Framework — OpenAPI',
    status: 'supported',
  },
  'web-openapi-decorators': {
    title: 'Schema Decorators',
    group: 'Web Framework — OpenAPI',
    status: 'supported',
  },
  'web-openapi-security': {
    title: 'Security Schemes',
    group: 'Web Framework — OpenAPI',
    status: 'todo',
    note: 'no securitySchemes or per-operation security; guard-derived security and the strictness rule are frozen (#573).',
  },
  'web-mapped-types': {
    title: 'Mapped Types',
    group: 'Web Framework — OpenAPI',
    status: 'supported',
  },
  'web-configuration': {
    title: 'Configuration',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-logging': {
    title: 'Logging',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-caching': {
    title: 'Caching',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-request-context': {
    title: 'Request Context',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-raw-body': {
    title: 'Raw Body',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-events': {
    title: 'Events',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no application event emitter module; EventBus covers entity lifecycle only',
  },
  'web-http-client': {
    title: 'HTTP Client',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-file-upload': {
    title: 'File Upload',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'multipart/form-data parsing is not shipped; the limits and the buffered-parser decision are frozen (#565).',
  },
  'web-streaming-files': {
    title: 'Streaming Files',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'WebResponse.body is a string; the tagged three-arm union that replaces it is frozen (#565).',
  },
  'web-compression': {
    title: 'Compression',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'depends on streaming responses; the negotiation policy is frozen and brotli is declined (#565).',
  },
  'web-static-files': {
    title: 'Serving Static Files',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no static file handler; the confinement, caching and range rules are frozen (#565).',
  },
  'web-templates': {
    title: 'Server-Side Templates',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'declined with a reason — respond() returns HTML and no seam is shipping (#565).',
  },
  'web-task-scheduling': {
    title: 'Task Scheduling',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no @Cron/@Interval decorators or scheduler registry; the dialect, the DST rules and the per-task lease are frozen (#586).',
  },
  'web-queues': {
    title: 'Queues',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no queue module or worker abstraction; the handler contract, retry, dead-letter and idempotency are frozen (#586).',
  },
  'web-versioning': {
    title: 'API Versioning',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no version negotiator; path prefixes work today, and the three strategies are frozen (#573).',
  },
  'web-performance': {
    title: 'Performance & Keep-Alive',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-health-checks': {
    title: 'Health Checks',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no readiness/liveness aggregation module; the split, response shapes, timeouts and caching are frozen (#579) and asserted by expected-failing tests (#580)',
  },
  'web-observability': {
    title: 'Observability',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no OpenTelemetry instrumentation of the router, pipeline or driver; the metric names, units and attribute sources are frozen (#579) and asserted by expected-failing tests (#580)',
  },
  'web-tracing': {
    title: 'Distributed Tracing',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no span propagation across the request pipeline; the span hierarchy, attribute names and W3C propagation are frozen (#579) and asserted by expected-failing tests (#580)',
  },
  'web-devtools': {
    title: 'Devtools',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no module-graph inspector',
  },
  'web-hot-reload': {
    title: 'Hot Reload',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-repl': {
    title: 'REPL',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'no REPL entry point that boots the container',
  },
  'web-multiple-servers': {
    title: 'Multiple Servers',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-hybrid-application': {
    title: 'Hybrid Applications',
    group: 'Web Framework — Techniques',
    status: 'todo',
    note: 'transports and the hybrid lifecycle are frozen (microservices/SPEC.md §10) but not built',
  },
  'web-serverless': {
    title: 'Serverless',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-deployment': {
    title: 'Deployment',
    group: 'Web Framework — Techniques',
    status: 'supported',
  },
  'web-authentication': {
    title: 'Authentication',
    group: 'Web Framework — Security',
    status: 'supported',
  },
  'web-authorization': {
    title: 'Authorization',
    group: 'Web Framework — Security',
    status: 'supported',
  },
  'web-cors': {
    title: 'CORS',
    group: 'Web Framework — Security',
    status: 'supported',
  },
  'web-csrf': {
    title: 'CSRF Protection',
    group: 'Web Framework — Security',
    status: 'todo',
    note: 'no CSRF middleware; the threat model and a session-bound signed token are frozen (#565).',
  },
  'web-encryption': {
    title: 'Encryption & Hashing',
    group: 'Web Framework — Security',
    status: 'supported',
  },
  'web-security-headers': {
    title: 'Security Headers',
    group: 'Web Framework — Security',
    status: 'supported',
  },
  'web-rate-limiting': {
    title: 'Rate Limiting',
    group: 'Web Framework — Security',
    status: 'supported',
  },
  'web-cookies-sessions': {
    title: 'Cookies & Sessions',
    group: 'Web Framework — Security',
    status: 'supported',
  },
  'web-cli': {
    title: 'CLI & Scaffolding',
    group: 'Web Framework — CLI',
    status: 'todo',
    note: 'no zmdb executable, so no project/controller/module scaffolding',
  },
  'web-cli-monorepo': {
    title: 'Monorepos & Libraries',
    group: 'Web Framework — CLI',
    status: 'todo',
    note: 'depends on the CLI, which is not built',
  },
  'web-cli-apps': {
    title: 'Building CLI Applications',
    group: 'Web Framework — CLI',
    status: 'todo',
    note: 'no command decorators or argv parser bound to the container',
  },
  'web-microservices': {
    title: 'Microservices',
    group: 'Web Framework — Microservices',
    status: 'todo',
    note: 'transport strategy frozen in microservices/SPEC.md; nothing shipped yet.',
  },
  'web-microservices-transports': {
    title: 'Broker Transports',
    group: 'Web Framework — Microservices',
    status: 'todo',
    note: 'Redis / NATS / RabbitMQ frozen and unbuilt; Kafka, MQTT and TCP deferred with reasons',
  },
  'web-microservices-grpc': {
    title: 'gRPC',
    group: 'Web Framework — Microservices',
    status: 'todo',
    note: 'binding frozen in microservices/grpc/SPEC.md; blocked in fact on the protobuf codecs',
  },
  'web-microservices-custom-transport': {
    title: 'Custom Transports',
    group: 'Web Framework — Microservices',
    status: 'todo',
    note: 'the public strategy contract and its stability promise are frozen; nothing shipped yet',
  },
  'web-graphql': {
    title: 'GraphQL',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no GraphQL layer shipped; resolvers could sit on the DI container.',
  },
  'web-graphql-resolvers': {
    title: 'Resolvers & Mutations',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no @Resolver/@Query/@Mutation decorators',
  },
  'web-graphql-subscriptions': {
    title: 'Subscriptions',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no @Subscription decorator or pub/sub binding',
  },
  'web-graphql-scalars': {
    title: 'Scalars, Enums, Unions & Interfaces',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no SDL type emitters',
  },
  'web-graphql-mapped-types': {
    title: 'Mapped Types & Shared Models',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no PartialType/PickType analogue for SDL output',
  },
  'web-graphql-directives': {
    title: 'Directives & Extensions',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no directive or extension metadata',
  },
  'web-graphql-plugins': {
    title: 'Plugins',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no server plugin lifecycle',
  },
  'web-graphql-complexity': {
    title: 'Complexity Limits',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no complexity estimator or plugin',
  },
  'web-graphql-field-middleware': {
    title: 'Field Middleware',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no per-field middleware chain',
  },
  'web-graphql-middleware': {
    title: 'Guards & Interceptors',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no GraphQL execution context for the middleware chain',
  },
  'web-graphql-federation': {
    title: 'Federation',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no federated schema directives or gateway',
  },
  'web-graphql-schema-first': {
    title: 'Schema-First',
    group: 'Web Framework — GraphQL',
    status: 'todo',
    note: 'no SDL-to-resolver-type generator',
  },
  'web-faq-errors': {
    title: 'Common Errors',
    group: 'Web Framework — FAQ',
    status: 'supported',
  },
  'anti-patterns': {
    title: 'Anti-patterns (deliberately excluded)',
    group: 'Reference',
    status: 'supported',
  },
  benchmarks: {
    title: 'Benchmarks',
    group: 'Reference',
    status: 'supported',
  },
};
