// generated by @zmdb/schema-core/llm/http — do not edit
import { assert } from '@zmdb/aot-validator/utilities';
import type { OpenApiGeneratedTool } from '@zmdb/schema-core/llm/http';
import type { MaxLength } from '@zmdb/schema-core/tags';

type OpenApiNoArguments = {
  readonly __openApiNoArguments?: string;
};

export type ListUsersArguments = Readonly<Record<never, never>>;

export const listUsersTool: OpenApiGeneratedTool<ListUsersArguments> = {
  spec: {
    name: 'list_users',
    parameters: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  request: {
    method: 'GET',
    path: '/users',
    pathParameters: [],
    queryParameters: [],
    bodyParameters: [],
    hasBody: false,
  },
  validate: (input: unknown): ListUsersArguments => assert<OpenApiNoArguments>(input),
};

export type PostUsersArguments = {
  readonly createdAt?: string;
  readonly email: string & MaxLength<255>;
};

export const postUsersTool: OpenApiGeneratedTool<PostUsersArguments> = {
  spec: {
    name: 'post_users',
    parameters: {
      type: 'object',
      properties: {
        createdAt: {
          format: 'date-time',
          type: 'string',
        },
        email: {
          maxLength: 255,
          type: 'string',
        },
      },
      required: ['email'],
    },
  },
  request: {
    method: 'POST',
    path: '/users',
    pathParameters: [],
    queryParameters: [],
    bodyParameters: ['createdAt', 'email'],
    hasBody: true,
  },
  validate: (input: unknown): PostUsersArguments => assert<PostUsersArguments>(input),
};

export type GetUsersHealthArguments = Readonly<Record<never, never>>;

export const getUsersHealthTool: OpenApiGeneratedTool<GetUsersHealthArguments> = {
  spec: {
    name: 'get_users_health',
    parameters: {
      type: 'object',
      properties: {},
      required: [],
    },
  },
  request: {
    method: 'GET',
    path: '/users/health',
    pathParameters: [],
    queryParameters: [],
    bodyParameters: [],
    hasBody: false,
  },
  validate: (input: unknown): GetUsersHealthArguments => assert<OpenApiNoArguments>(input),
};

export type DeleteUsersIdArguments = {
  readonly id: string;
};

export const deleteUsersIdTool: OpenApiGeneratedTool<DeleteUsersIdArguments> = {
  spec: {
    name: 'delete_users_id',
    parameters: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
        },
      },
      required: ['id'],
    },
  },
  request: {
    method: 'DELETE',
    path: '/users/{id}',
    pathParameters: ['id'],
    queryParameters: [],
    bodyParameters: [],
    hasBody: false,
  },
  validate: (input: unknown): DeleteUsersIdArguments => assert<DeleteUsersIdArguments>(input),
};

export type GetUsersIdArguments = {
  readonly id: string;
};

export const getUsersIdTool: OpenApiGeneratedTool<GetUsersIdArguments> = {
  spec: {
    name: 'get_users_id',
    parameters: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
        },
      },
      required: ['id'],
    },
  },
  request: {
    method: 'GET',
    path: '/users/{id}',
    pathParameters: ['id'],
    queryParameters: [],
    bodyParameters: [],
    hasBody: false,
  },
  validate: (input: unknown): GetUsersIdArguments => assert<GetUsersIdArguments>(input),
};

export type PostUsersIdRolesArguments = {
  readonly id: string;
};

export const postUsersIdRolesTool: OpenApiGeneratedTool<PostUsersIdRolesArguments> = {
  spec: {
    name: 'post_users_id_roles',
    parameters: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
        },
      },
      required: ['id'],
    },
  },
  request: {
    method: 'POST',
    path: '/users/{id}/roles',
    pathParameters: ['id'],
    queryParameters: [],
    bodyParameters: [],
    hasBody: false,
  },
  validate: (input: unknown): PostUsersIdRolesArguments => assert<PostUsersIdRolesArguments>(input),
};

export type PutUsersIdRolesRoleIdArguments = {
  readonly id: string;
  readonly roleId: string;
};

export const putUsersIdRolesRoleIdTool: OpenApiGeneratedTool<PutUsersIdRolesRoleIdArguments> = {
  spec: {
    name: 'put_users_id_roles_roleId',
    parameters: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
        },
        roleId: {
          type: 'string',
        },
      },
      required: ['id', 'roleId'],
    },
  },
  request: {
    method: 'PUT',
    path: '/users/{id}/roles/{roleId}',
    pathParameters: ['id', 'roleId'],
    queryParameters: [],
    bodyParameters: [],
    hasBody: false,
  },
  validate: (input: unknown): PutUsersIdRolesRoleIdArguments => assert<PutUsersIdRolesRoleIdArguments>(input),
};

export const openApiTools = {
  list_users: listUsersTool,
  post_users: postUsersTool,
  get_users_health: getUsersHealthTool,
  delete_users_id: deleteUsersIdTool,
  get_users_id: getUsersIdTool,
  post_users_id_roles: postUsersIdRolesTool,
  put_users_id_roles_roleId: putUsersIdRolesRoleIdTool,
};
