import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { schemasFromFiles } from '@zmdb/aot-validator/testing';
import { createIntrospector, detectDrift } from '@zmdb/query-compiler/introspect';
import {
  diff,
  snapshot,
  type ColumnSnapshot,
  type ExtensionSnapshot,
  type ExtensionType,
  type ForeignKeySnapshot,
  type ReferentialAction,
  type SchemaSnapshot,
  type TableSnapshot,
} from '@zmdb/query-compiler/migrations';

import type { ResolvedConfig } from '../../config/index.js';
import { readMigrations } from '../migration-files.js';
import { EMBEDDED_WITH_DOWN_MARKER, embeddedOutputPath, renderEmbeddedModule } from './embed.js';

const EMPTY_SNAPSHOT: SchemaSnapshot = { version: 1, tables: [], extensions: [] };

export type CheckFindingKind =
  | 'uncommitted-schema'
  | 'duplicate-version'
  | 'snapshot-version'
  | 'missing-down'
  | 'stale-embedded'
  | 'drift';

export interface CheckFinding {
  readonly kind: CheckFindingKind;
  readonly message: string;
  readonly subject: string;
}

export interface CheckResult {
  readonly findings: readonly CheckFinding[];
  readonly skipped: readonly { readonly kind: 'drift'; readonly reason: string }[];
}

export async function checkProject(config: ResolvedConfig): Promise<CheckResult> {
  const findings: CheckFinding[] = [];
  const skipped: { readonly kind: 'drift'; readonly reason: string }[] = [];
  const snapshotPath = join(config.outDir, 'snapshot.json');
  const stored = await storedSnapshot(snapshotPath);
  const declared = snapshot(schemasFromFiles(config.schemaFiles, { project: config.project }));

  if ('newerVersion' in stored) {
    findings.push({
      kind: 'snapshot-version',
      message: `snapshot version ${String(stored.newerVersion)} is newer than this build's version 1`,
      subject: snapshotPath,
    });
  } else if (diff(stored.snapshot, declared, { dialect: config.dialect }).length > 0) {
    findings.push({
      kind: 'uncommitted-schema',
      message: 'declarations differ from the stored snapshot; run zmdb generate',
      subject: snapshotPath,
    });
  }

  const migrations = await readMigrations(config.outDir);
  const byVersion = new Map<number, string[]>();
  for (const migration of migrations) {
    const paths = byVersion.get(migration.version) ?? [];
    paths.push(migration.path);
    byVersion.set(migration.version, paths);
    if (!migration.hasDown) {
      findings.push({
        kind: 'missing-down',
        message: `migration ${String(migration.version)} ${migration.name} has no -- zmdb:down section`,
        subject: migration.path,
      });
    }
  }
  for (const [version, paths] of byVersion) {
    if (paths.length < 2) continue;
    findings.push({
      kind: 'duplicate-version',
      message: `migration version ${String(version)} appears in ${String(paths.length)} files`,
      subject: paths.join(', '),
    });
  }

  if (config.dialect === 'sqlite') {
    const embeddedPath = embeddedOutputPath(config);
    const embedded = await optionalFile(embeddedPath);
    if (embedded !== undefined) {
      const withDown = embedded.startsWith(
        `// Generated by \`zmdb embed\`. Do not edit.\n${EMBEDDED_WITH_DOWN_MARKER}\n`,
      );
      const expected = await renderEmbeddedModule(config, withDown ? { withDown: true } : {});
      if (embedded !== expected.source) {
        findings.push({
          kind: 'stale-embedded',
          message: 'embedded migration module differs from the configured migration files; run zmdb embed',
          subject: embeddedPath,
        });
      }
    }
  }

  if (config.driver === undefined) {
    skipped.push({ kind: 'drift', reason: `config ${config.configPath} has no driver` });
  } else if (!('newerVersion' in stored)) {
    const driver = await config.driver();
    const live = await createIntrospector(config.dialect).snapshot(driver, config.introspect);
    const report = detectDrift(live, stored.snapshot, { dialect: config.dialect });
    if (!report.clean) {
      findings.push({
        kind: 'drift',
        message:
          `live database differs from the stored snapshot: ` +
          `${String(report.onlyInDatabase.length)} database-only and ` +
          `${String(report.onlyInDeclarations.length)} declaration-only operations`,
        subject: config.configPath,
      });
    }
  }

  return { findings, skipped };
}

async function optionalFile(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if (errorCode(error) === 'ENOENT') return undefined;
    throw error;
  }
}

async function storedSnapshot(
  path: string,
): Promise<{ readonly snapshot: SchemaSnapshot } | { readonly newerVersion: number }> {
  let source: string;
  try {
    source = await readFile(path, 'utf8');
  } catch (error) {
    if (errorCode(error) === 'ENOENT') return { snapshot: EMPTY_SNAPSHOT };
    throw error;
  }
  const parsed: unknown = JSON.parse(source);
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new TypeError(`stored snapshot ${path} must be a JSON object`);
  }
  const version: unknown = Reflect.get(parsed, 'version');
  if (typeof version !== 'number' || !Number.isSafeInteger(version)) {
    throw new TypeError(`stored snapshot ${path} has no safe integer version`);
  }
  if (version > 1) return { newerVersion: version };
  if (version !== 1) throw new TypeError(`stored snapshot ${path} uses unknown version ${String(version)}`);
  return { snapshot: snapshotV1(parsed, path) };
}

function snapshotV1(value: object, path: string): SchemaSnapshot {
  const stored = record(value, `stored snapshot ${path}`);
  const tableValues = array(stored.tables, `stored snapshot ${path} tables`);
  const extensionValues = array(stored.extensions, `stored snapshot ${path} extensions`);
  return {
    version: 1,
    tables: tableValues.map((table, index) => tableSnapshot(table, path, index)),
    extensions: extensionValues.map((extension, index) => extensionSnapshot(extension, path, index)),
  };
}

function tableSnapshot(value: unknown, path: string, index: number): TableSnapshot {
  const table = record(value, `stored snapshot ${path} table ${String(index)}`);
  const name = text(table.name, `stored snapshot ${path} table ${String(index)} name`);
  const columns = array(table.columns, `stored snapshot ${path} table ${name} columns`).map((column, columnIndex) =>
    columnSnapshot(column, path, name, columnIndex),
  );
  const primaryKey =
    table.primaryKey === undefined
      ? columns.filter(column => column.primaryKey).map(column => column.name)
      : stringArray(table.primaryKey, `stored snapshot ${path} table ${name} primaryKey`);
  const foreignKeys =
    table.foreignKeys === undefined
      ? []
      : array(table.foreignKeys, `stored snapshot ${path} table ${name} foreignKeys`).map((foreignKey, keyIndex) =>
          foreignKeySnapshot(foreignKey, path, name, keyIndex),
        );
  return { name, columns, primaryKey, foreignKeys };
}

function columnSnapshot(value: unknown, path: string, table: string, index: number): ColumnSnapshot {
  const column = record(value, `stored snapshot ${path} table ${table} column ${String(index)}`);
  const length = column.length;
  if (length !== undefined && (typeof length !== 'number' || !Number.isSafeInteger(length) || length < 1)) {
    throw new TypeError(`stored snapshot ${path} table ${table} column ${String(index)} length must be positive`);
  }
  return {
    name: text(column.name, `stored snapshot ${path} table ${table} column ${String(index)} name`),
    type: columnType(column.type, path, table, index),
    nullable: flag(column.nullable, `stored snapshot ${path} table ${table} column ${String(index)} nullable`),
    primaryKey: flag(column.primaryKey, `stored snapshot ${path} table ${table} column ${String(index)} primaryKey`),
    ...(length === undefined ? {} : { length }),
  };
}

function columnType(value: unknown, path: string, table: string, index: number): string | ExtensionType {
  if (typeof value === 'string') return value;
  const type = record(value, `stored snapshot ${path} table ${table} column ${String(index)} type`);
  const args =
    type.args === undefined
      ? undefined
      : array(type.args, `stored snapshot ${path} table ${table} column ${String(index)} type args`).map(
          (argument, argumentIndex) => {
            if (typeof argument === 'string' || typeof argument === 'number') return argument;
            throw new TypeError(
              `stored snapshot ${path} table ${table} column ${String(index)} type arg ${String(argumentIndex)} ` +
                'must be a string or number',
            );
          },
        );
  return {
    extension: text(type.extension, `stored snapshot ${path} table ${table} column ${String(index)} type extension`),
    name: text(type.name, `stored snapshot ${path} table ${table} column ${String(index)} type name`),
    ...(args === undefined ? {} : { args }),
  };
}

function foreignKeySnapshot(value: unknown, path: string, table: string, index: number): ForeignKeySnapshot {
  const foreignKey = record(value, `stored snapshot ${path} table ${table} foreign key ${String(index)}`);
  return {
    name: text(foreignKey.name, `stored snapshot ${path} table ${table} foreign key ${String(index)} name`),
    columns: stringArray(
      foreignKey.columns,
      `stored snapshot ${path} table ${table} foreign key ${String(index)} columns`,
    ),
    targetTable: text(
      foreignKey.targetTable,
      `stored snapshot ${path} table ${table} foreign key ${String(index)} targetTable`,
    ),
    targetColumns: stringArray(
      foreignKey.targetColumns,
      `stored snapshot ${path} table ${table} foreign key ${String(index)} targetColumns`,
    ),
    onDelete: referentialAction(
      foreignKey.onDelete,
      `stored snapshot ${path} table ${table} foreign key ${String(index)} onDelete`,
    ),
    onUpdate: referentialAction(
      foreignKey.onUpdate,
      `stored snapshot ${path} table ${table} foreign key ${String(index)} onUpdate`,
    ),
  };
}

function extensionSnapshot(value: unknown, path: string, index: number): ExtensionSnapshot {
  const extension = record(value, `stored snapshot ${path} extension ${String(index)}`);
  const schema = extension.schema;
  if (schema !== undefined && typeof schema !== 'string') {
    throw new TypeError(`stored snapshot ${path} extension ${String(index)} schema must be a string`);
  }
  return {
    name: text(extension.name, `stored snapshot ${path} extension ${String(index)} name`),
    ...(schema === undefined ? {} : { schema }),
  };
}

function referentialAction(value: unknown, label: string): ReferentialAction {
  if (
    value === 'cascade' ||
    value === 'restrict' ||
    value === 'set null' ||
    value === 'set default' ||
    value === 'no action'
  ) {
    return value;
  }
  throw new TypeError(`${label} must be a referential action`);
}

function record(value: unknown, label: string): Readonly<Record<string, unknown>> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new TypeError(`${label} must be an object`);
  }
  return Object.fromEntries(Object.entries(value));
}

function array(value: unknown, label: string): readonly unknown[] {
  if (!Array.isArray(value)) throw new TypeError(`${label} must be an array`);
  return value;
}

function stringArray(value: unknown, label: string): readonly string[] {
  return array(value, label).map((item, index) => text(item, `${label} item ${String(index)}`));
}

function text(value: unknown, label: string): string {
  if (typeof value !== 'string') throw new TypeError(`${label} must be a string`);
  return value;
}

function flag(value: unknown, label: string): boolean {
  if (typeof value !== 'boolean') throw new TypeError(`${label} must be a boolean`);
  return value;
}

function errorCode(error: unknown): string | undefined {
  if (typeof error !== 'object' || error === null) return undefined;
  const code = Reflect.get(error, 'code');
  return typeof code === 'string' ? code : undefined;
}
