import { dirname, join, resolve } from 'node:path';

import type { FormatConfig } from 'oxfmt';

import type { ResolvedConfig } from '../../config/index.js';
import { writeTextAtomically } from '../atomic.js';
import { CliInvocationError } from '../errors.js';
import { readMigrations } from '../migration-files.js';

const FORMAT_OPTIONS: FormatConfig = {
  arrowParens: 'avoid',
  bracketSpacing: true,
  endOfLine: 'lf',
  insertFinalNewline: true,
  objectWrap: 'preserve',
  printWidth: 120,
  quoteProps: 'as-needed',
  semi: true,
  singleQuote: true,
  sortImports: true,
  sortPackageJson: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
};

export const EMBEDDED_WITH_DOWN_MARKER = '// Includes down sections for development tooling.';

export interface EmbedOptions {
  readonly out?: string;
  readonly withDown?: boolean;
}

export interface EmbeddedModuleResult {
  readonly file: string;
  readonly source: string;
  readonly migrations: readonly {
    readonly version: number;
    readonly name: string;
    readonly checksum: string;
  }[];
}

export interface EmbedResult {
  readonly file: string;
  readonly migrations: EmbeddedModuleResult['migrations'];
}

export function embeddedOutputPath(config: ResolvedConfig, requested?: string): string {
  return requested === undefined ? join(config.outDir, 'embedded.ts') : resolve(dirname(config.configPath), requested);
}

export async function renderEmbeddedModule(
  config: ResolvedConfig,
  options: EmbedOptions = {},
): Promise<EmbeddedModuleResult> {
  const file = embeddedOutputPath(config, options.out);
  const migrations = await Promise.all(
    (await readMigrations(config.outDir)).map(async migration => ({
      version: migration.version,
      name: migration.name,
      up: migration.up,
      ...(options.withDown === true ? { down: migration.down } : {}),
      checksum: await checksum(migration.up),
    })),
  );
  const arrayType =
    options.withDown === true
      ? 'readonly (EmbeddedMigration & { readonly down: string })[]'
      : 'readonly EmbeddedMigration[]';
  const marker = options.withDown === true ? `${EMBEDDED_WITH_DOWN_MARKER}\n` : '';
  const raw =
    '// Generated by `zmdb embed`. Do not edit.\n' +
    marker +
    "import type { EmbeddedMigration } from '@zmdb/query-compiler/migrations/embedded';\n\n" +
    `export const migrations: ${arrayType} = ${JSON.stringify(migrations, null, 2)} as const;\n`;
  const { format } = await import('oxfmt');
  const formatted = await format(file, raw, FORMAT_OPTIONS);
  if (formatted.errors.length > 0) {
    throw new TypeError(`oxfmt could not format generated ${file}: ${JSON.stringify(formatted.errors)}`);
  }
  return {
    file,
    source: formatted.code,
    migrations: migrations.map(migration => ({
      version: migration.version,
      name: migration.name,
      checksum: migration.checksum,
    })),
  };
}

export async function embedMigrations(config: ResolvedConfig, options: EmbedOptions = {}): Promise<EmbedResult> {
  if (config.dialect !== 'sqlite') {
    throw new CliInvocationError(
      `embedded migrations execute SQLite, but ${config.configPath} configures ${config.dialect}`,
    );
  }
  const rendered = await renderEmbeddedModule(config, options);
  await writeTextAtomically(rendered.file, rendered.source);
  return { file: rendered.file, migrations: rendered.migrations };
}

async function checksum(source: string): Promise<string> {
  const bytes = new TextEncoder().encode(source);
  const digest = new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256', bytes));
  const hex = Array.from(digest, byte => byte.toString(16).padStart(2, '0')).join('');
  return `sha256:${hex}`;
}
