import type { Dialect } from '@zmdb/query-compiler';
import { describe, expect, it } from 'vitest';

import type { ColumnSnapshot, SchemaSnapshot, TableSnapshot } from '../index.js';

type FrozenIndexColumn =
  | string
  | { readonly column: string; readonly opclass?: string }
  | { readonly expr: string; readonly opclass?: string };

interface FrozenIndexSnapshot {
  readonly name: string;
  readonly columns: readonly FrozenIndexColumn[];
  readonly unique: boolean;
}

interface FrozenForeignKeySnapshot {
  readonly name: string;
  readonly columns: readonly string[];
  readonly targetTable: string;
  readonly targetColumns: readonly string[];
  readonly onDelete: 'no action' | 'restrict' | 'cascade' | 'set null' | 'set default';
  readonly onUpdate: 'no action' | 'restrict' | 'cascade' | 'set null' | 'set default';
}

type FrozenColumnSnapshot = ColumnSnapshot & {
  readonly catalogType?: string;
  readonly default?: string;
};

type FrozenTableSnapshot = Omit<TableSnapshot, 'columns'> & {
  readonly columns: readonly FrozenColumnSnapshot[];
  readonly primaryKey: readonly string[];
  readonly foreignKeys: readonly FrozenForeignKeySnapshot[];
  readonly indexes: readonly FrozenIndexSnapshot[];
};

type FrozenSchemaSnapshot = Omit<SchemaSnapshot, 'tables'> & {
  readonly tables: readonly FrozenTableSnapshot[];
  readonly extensions: readonly { readonly name: string; readonly schema?: string }[];
};

interface FrozenEmitOptions {
  readonly dialect: Dialect;
}

interface FrozenEmitDeclarationsResult {
  readonly files: readonly { readonly path: string; readonly source: string }[];
  readonly warnings: readonly {
    readonly table: string;
    readonly column?: string;
    readonly reason: string;
  }[];
}

type FrozenEmitDeclarations = (
  snapshot: FrozenSchemaSnapshot,
  options: FrozenEmitOptions,
) => FrozenEmitDeclarationsResult | Promise<FrozenEmitDeclarationsResult>;

async function emitDeclarations(
  snapshot: FrozenSchemaSnapshot,
  options: FrozenEmitOptions,
): Promise<FrozenEmitDeclarationsResult> {
  const module: unknown = await import('./index.js');
  const value: unknown = Reflect.get(Object(module), 'emitDeclarations');
  if (typeof value !== 'function') {
    throw new Error('@zmdb/migrations/declarations exports no "emitDeclarations" (frozen: introspect/SPEC.md 6)');
  }
  return (value as FrozenEmitDeclarations)(snapshot, options);
}

function snapshotOf(table: FrozenTableSnapshot): FrozenSchemaSnapshot {
  return { version: 1, tables: [table], extensions: [] };
}

function tableOf(name: string, columns: readonly FrozenColumnSnapshot[]): FrozenTableSnapshot {
  return { name, columns, primaryKey: [], foreignKeys: [], indexes: [] };
}

describe('declaration emission (frozen: introspect/SPEC.md 6-7)', () => {
  it('emits formatter-clean declarations with overwrite and warning metadata preserved', async () => {
    const input = snapshotOf(
      tableOf('accounts', [
        {
          name: 'created_at',
          type: 'timestamp',
          catalogType: 'TEXT',
          nullable: false,
          primaryKey: false,
          default: 'CURRENT_TIMESTAMP',
        },
        { name: 'email', type: 'text', catalogType: 'TEXT', nullable: false, primaryKey: false },
        { name: 'id', type: 'serial', catalogType: 'INTEGER', nullable: false, primaryKey: true },
      ]),
    );

    const first = await emitDeclarations(input, { dialect: 'sqlite' });
    const second = await emitDeclarations(input, { dialect: 'sqlite' });
    expect(first).toEqual(second);
    expect(first.files.map(file => file.path)).toEqual(['accounts.ts', 'index.ts']);

    const account = first.files.find(file => file.path === 'accounts.ts');
    if (!account) throw new Error('emitter produced no accounts.ts');
    expect(account.source).toContain(
      '// Generated by zmdb introspection from a sqlite database. Do not edit; regenerate instead.',
    );
    expect(account.source).toContain('// Snapshot version 1. Hand edits are overwritten wholesale.');
    expect(account.source).toContain("export interface Account extends Table<'accounts'>");
    expect(account.source).toContain("id: number & Sql<'integer'> & Serial & PrimaryKey;");
    expect(account.source).toContain("created_at: Date & Sql<'timestamp'> & HasDefault;");
    expect(account.source).toContain('// Database default expression: "CURRENT_TIMESTAMP"');
    expect(account.source).not.toMatch(/[ \t]+$/m);
    expect(account.source.endsWith('\n')).toBe(true);

    const warningResult = await emitDeclarations(
      snapshotOf(
        tableOf('documents', [
          { name: 'payload', type: 'bytea', catalogType: 'bytea', nullable: false, primaryKey: false },
        ]),
      ),
      { dialect: 'postgres' },
    );
    expect(warningResult.warnings).toEqual([
      {
        table: 'documents',
        column: 'payload',
        reason: expect.stringMatching(/bytea.*cannot be represented without data loss/i),
      },
    ]);
  });

  // `bytea` has no app type that round-trips its bytes. It remains exact in the
  // snapshot, but the declaration omits the property and names the omission twice:
  // structurally and beside the generated interface. `unknown` is never the fallback.
  it('warns and comments rather than widening an unrepresentable type', async () => {
    const input = snapshotOf(
      tableOf('documents', [
        { name: 'id', type: 'serial', catalogType: 'int4', nullable: false, primaryKey: true },
        { name: 'payload', type: 'bytea', catalogType: 'bytea', nullable: false, primaryKey: false },
      ]),
    );
    const result = await emitDeclarations(input, { dialect: 'postgres' });
    const document = result.files.find(file => file.path === 'documents.ts');
    if (!document) throw new Error('emitter produced no documents.ts');

    expect(result.warnings).toEqual([
      {
        table: 'documents',
        column: 'payload',
        reason: expect.stringMatching(/bytea.*cannot be represented without data loss/i),
      },
    ]);
    expect(document.source).toMatch(/TODO:.*payload.*bytea/i);
    expect(document.source).not.toMatch(/^\s*payload\s*:/m);
    expect(document.source).not.toContain('unknown');
  });

  it('emits extension-backed declarations with their app type and Ext tag', async () => {
    const input: FrozenSchemaSnapshot = {
      version: 1,
      tables: [
        tableOf('documents', [
          {
            name: 'embedding',
            type: { extension: 'vector', name: 'vector', args: [3] },
            catalogType: 'vector',
            nullable: false,
            primaryKey: false,
          },
          {
            name: 'handle',
            type: { extension: 'citext', name: 'citext' },
            catalogType: 'citext',
            nullable: true,
            primaryKey: false,
          },
        ]),
      ],
      extensions: [{ name: 'citext' }, { name: 'vector' }],
    };

    const result = await emitDeclarations(input, { dialect: 'postgres' });
    const document = result.files.find(file => file.path === 'documents.ts');
    if (!document) throw new Error('emitter produced no documents.ts');

    expect(document.source).toContain("import type { Ext, Table } from '@zmdb/schema-core/tags';");
    expect(document.source).toContain("embedding: readonly number[] & Ext<'vector', 'vector', [3]>;");
    expect(document.source).toContain("handle: (string & Ext<'citext', 'citext'>) | null;");
    expect(result.warnings).toEqual([]);
  });

  it('emits an unambiguous many-to-one relation and its exact reference', async () => {
    const accounts = tableOf('accounts', [
      { name: 'id', type: 'serial', catalogType: 'INTEGER', nullable: false, primaryKey: true },
    ]);
    const posts: FrozenTableSnapshot = {
      ...tableOf('posts', [
        {
          name: 'account_id',
          type: 'integer',
          catalogType: 'INTEGER',
          nullable: false,
          primaryKey: false,
        },
        { name: 'id', type: 'serial', catalogType: 'INTEGER', nullable: false, primaryKey: true },
      ]),
      foreignKeys: [
        {
          name: 'posts_account_id_fkey',
          columns: ['account_id'],
          targetTable: 'accounts',
          targetColumns: ['id'],
          onDelete: 'no action',
          onUpdate: 'no action',
        },
      ],
    };
    const result = await emitDeclarations(
      { version: 1, tables: [posts, accounts], extensions: [] },
      { dialect: 'sqlite' },
    );
    const post = result.files.find(file => file.path === 'posts.ts');
    if (!post) throw new Error('emitter produced no posts.ts');

    expect(post.source).toContain("account_id: number & Sql<'integer'> & References<'accounts.id'>;");
    expect(post.source).toContain("account?: Account & ManyToOne<'accounts', 'account_id'>;");
    expect(post.source).toContain("import type { Account } from './accounts.js';");
    expect(result.warnings).toEqual([]);
  });

  it('skips an ambiguous relation with a warning', async () => {
    const users = tableOf('users', [
      { name: 'id', type: 'serial', catalogType: 'INTEGER', nullable: false, primaryKey: true },
    ]);
    const posts: FrozenTableSnapshot = {
      ...tableOf('posts', [
        { name: 'author_id', type: 'integer', catalogType: 'INTEGER', nullable: false, primaryKey: false },
        { name: 'editor_id', type: 'integer', catalogType: 'INTEGER', nullable: false, primaryKey: false },
        { name: 'id', type: 'serial', catalogType: 'INTEGER', nullable: false, primaryKey: true },
      ]),
      foreignKeys: [
        {
          name: 'posts_author_id_fkey',
          columns: ['author_id'],
          targetTable: 'users',
          targetColumns: ['id'],
          onDelete: 'no action',
          onUpdate: 'no action',
        },
        {
          name: 'posts_editor_id_fkey',
          columns: ['editor_id'],
          targetTable: 'users',
          targetColumns: ['id'],
          onDelete: 'no action',
          onUpdate: 'no action',
        },
      ],
    };
    const result = await emitDeclarations(
      { version: 1, tables: [posts, users], extensions: [] },
      { dialect: 'sqlite' },
    );
    const post = result.files.find(file => file.path === 'posts.ts');
    if (!post) throw new Error('emitter produced no posts.ts');

    expect(result.warnings).toContainEqual({
      table: 'posts',
      reason: expect.stringMatching(/all target "users".*ambiguous.*omitted/i),
    });
    expect(post.source).toMatch(/TODO:.*ambiguous.*omitted/i);
    expect(post.source).not.toMatch(/^\s*user\??:/m);
  });
});
