/*zmdb:imports*/
// Generated by @zmdb/compiler from src/orders.ts. Checked, not edited.
//
// One wrapper per validation call src/orders.ts used to make, written against the runtime
// API so that the compiler still sees each type argument. That is the point of the file: it
// is what the project compiler reads on the next run to regenerate the compiled module, and it is
// what turns a renamed or deleted type into a build error here instead of a validator that
// silently checks a shape nobody declares.
//
// Editing it by hand does nothing. An entry disappears when the source stops referring to
// its export name, so deleting a call in the source is how you delete a validator; there's
// no bookkeeping to keep in step.

import type { Order } from './model.js';
import type { JsonSchemaObject, TaggedSchema } from 'zmdb/schema';
import type { ValidateResult } from 'zmdb/validator';
import { assert, is, random, validate } from 'zmdb/validator';
import { schemaOf, toJsonSchema } from 'zmdb/schema';
/*zmdb:/imports*/

/*zmdb:begin:zmdbIsOrder*/
export function zmdbIsOrder(value: unknown): value is Order {
  return is<Order>(value);
}
/*zmdb:end:zmdbIsOrder*/

/*zmdb:begin:zmdbIsReadonlyXNumberReadonlyYNumber*/
export function zmdbIsReadonlyXNumberReadonlyYNumber(value: unknown): value is { readonly x: number; readonly y: number } {
  return is<{ readonly x: number; readonly y: number }>(value);
}
/*zmdb:end:zmdbIsReadonlyXNumberReadonlyYNumber*/

/*zmdb:begin:zmdbAssertOrder*/
export function zmdbAssertOrder(value: unknown): Order {
  return assert<Order>(value);
}
/*zmdb:end:zmdbAssertOrder*/

/*zmdb:begin:zmdbValidateOrder*/
export function zmdbValidateOrder(value: unknown): ValidateResult<Order> {
  return validate<Order>(value);
}
/*zmdb:end:zmdbValidateOrder*/

/*zmdb:begin:zmdbRandomOrder*/
export function zmdbRandomOrder(): Order {
  return random<Order>();
}
/*zmdb:end:zmdbRandomOrder*/

/*zmdb:begin:zmdbJsonSchemaOrder*/
export function zmdbJsonSchemaOrder(): JsonSchemaObject {
  return toJsonSchema<Order>();
}
/*zmdb:end:zmdbJsonSchemaOrder*/

/*zmdb:begin:zmdbSchemaOrder*/
export function zmdbSchemaOrder(): TaggedSchema<Order> {
  return schemaOf<Order>();
}
/*zmdb:end:zmdbSchemaOrder*/
