// Generated by zmdb-codegen from src/orders.ts. Do not edit.
//
// The validators, compiled. Every check below was emitted from a type in src/orders.ts's
// witness module by `@zmdb/aot-validator`, so there is no schema to walk at runtime and
// nothing to look up: the shape is the control flow.
//
// This half is the types: the signatures the compiler reads when the source imports the
// module next door. Nothing here is checked against the implementation, and nothing needs
// to be — the witness makes the same claims against the runtime API, and *that* is checked.
import type { Order } from './model.ts';
import type { JsonSchemaObject, TaggedSchema, ValidateResult } from 'zmdb';

export declare function zmdbIsOrder(value: unknown): value is Order;

export declare function zmdbIsReadonlyXNumberReadonlyYNumber(value: unknown): value is { readonly x: number; readonly y: number };

export declare function zmdbAssertOrder(value: unknown): Order;

export declare function zmdbValidateOrder(value: unknown): ValidateResult<Order>;

export declare function zmdbRandomOrder(): Order;

export declare function zmdbJsonSchemaOrder(): JsonSchemaObject;

export declare function zmdbSchemaOrder(): TaggedSchema<Order>;
