// zmdb/app/messaging — curated transport-neutral messaging facade.
export {
  EventPattern,
  InFlight,
  MessageCorrelationError,
  MessagePattern,
  MessageRemoteError,
  MessageTimeoutError,
  TransportUnsupportedError,
  abortError,
  createEventPublisher,
  createMessageClient,
  createMessageDispatcher,
  decodeDelivery,
  decodeReply,
  encodeDelivery,
  encodeReply,
  getMessagePatterns,
  reportTransportError,
  transportExtension,
  withinGrace,
} from '@zmdb/app/messaging';
export type {
  ClientPatterns,
  DeliveryMetadata,
  DispatchOutcome,
  DispatcherOptions,
  EventPatterns,
  EventPublisher,
  MessageClient,
  MessageClientOptions,
  MessageContext,
  MessageDispatcher,
  MessageReply,
  RawMessage,
  ResolvedMessagePattern,
  Settlement,
  TransportCapabilities,
  TransportErrorSink,
  TransportRequest,
  TransportStrategy,
  WithHeaders,
} from '@zmdb/app/messaging';
