// zmdb/dto — explicit named re-exports of the read/query DTO family.
// (No `export *`: each symbol is enumerated so the umbrella surface is explicit.)
export {
  applyKeysetFilter,
  applyOrderBy,
  applyPagination,
  buildListResult,
  buildSearchResult,
  compileWhere,
  describeAggregate,
  getResult,
  project,
} from '@zmdb/schema-core/dto';
export type {
  AggFn,
  AggregateResult,
  AggregateSpec,
  ComputedSpec,
  FieldOps,
  GetDTO,
  GetOptions,
  KeysetCursorPage,
  KeysetListDTO,
  KeysetOrderByDTO,
  ListDTO,
  ListResult,
  NonNullableEntityKeys,
  OffsetListDTO,
  OffsetPage,
  OrderByDTO,
  OrderDir,
  OrderTarget,
  PaginationDTO,
  Projection,
  SearchDTO,
  SearchHit,
  SearchResult,
  WhereDTO,
  WhereTarget,
} from '@zmdb/schema-core/dto';
