// Stable product facade for the independently usable migration engine.
//
// Keep this list explicit: a new implementation export must be deliberately
// admitted to the product vocabulary rather than leaking through `export *`.
export {
  CHANGE_PHASES,
  ddlType,
  DDL_TYPES,
  diff,
  down,
  downTo,
  driverMigrationConnection,
  emitDown,
  emitSchemaObject,
  emitUp,
  ensureVersionTable,
  planMigration,
  rollbackTo,
  runCli,
  snapshot,
  status,
  up,
} from '@zmdb/migrations';
export type {
  AppliedMigration,
  ChangeOp,
  ColumnSnapshot,
  DdlSqlType,
  DiffOptions,
  ExtensionSnapshot,
  ExtensionType,
  ForeignKeySnapshot,
  Migration,
  MigrationConnection,
  MigrationDialect,
  MigrationDriver,
  MigrationPlan,
  MigrationPlanDialect,
  MigrationProject,
  MigrationRunOptions,
  MigrationStatus,
  MigrationTableOptions,
  ReferentialAction,
  SchemaObjectOperation,
  SchemaSnapshot,
  SnapshotableSchema,
  TableOptions,
  TableSnapshot,
} from '@zmdb/migrations';
export {
  applyPush,
  checkProject,
  embedMigrations,
  embeddedOutputPath,
  exportSchema,
  generateMigration,
  isDestructive,
  planPush,
  pullDeclarations,
  renderEmbeddedModule,
  upgradeSnapshot,
} from '@zmdb/migrations/files';
export type {
  CheckFinding,
  CheckFindingKind,
  CheckResult,
  EmbeddedModuleResult,
  EmbedOptions,
  EmbedResult,
  ExportResult,
  GenerateOptions,
  GenerateResult,
  PullExecution,
  PullFile,
  PullOptions,
  PullOutputFile,
  PullResult,
  PullSkippedFile,
  PushPlan,
  PushResult,
  UpgradeResult,
} from '@zmdb/migrations/files';
