import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  compareGeneratedRegion,
  inspectProductCatalog,
  renderIntegrationRows,
  renderPackageReferenceRows,
  verifyFacadeOwnership,
  verifyIntegrationRecords,
} from '../../../.github/scripts/verify-product-catalog.mjs';
import {
  REQUIRED_PRODUCT_SUBPATHS,
  TARGET_ROOT_TYPES,
  TARGET_ROOT_VALUES,
  inspectProductConsumerFixture,
  inspectProductFacade,
  runPackedProductConsumer,
} from '../../../.github/scripts/verify-product-facade.mjs';

const ROOT = process.cwd();
const PRODUCT_FIXTURE = join(ROOT, 'fixtures', 'consumer-product');

let measuredFacade: ReturnType<typeof inspectProductFacade> | undefined;
function facadeReport(): ReturnType<typeof inspectProductFacade> {
  measuredFacade ??= inspectProductFacade(ROOT);
  return measuredFacade;
}

let measuredCatalog: ReturnType<typeof inspectProductCatalog> | undefined;
function catalogReport(): ReturnType<typeof inspectProductCatalog> {
  measuredCatalog ??= inspectProductCatalog(ROOT);
  return measuredCatalog;
}

describe('the one-product facade and catalog (#619)', () => {
  // Current measured state: the root exposes 42 runtime values and 32
  // type-only declarations, while the frozen target is 19 values and 27 types.
  // Seven of the thirteen required concern/driver subpaths are also absent.
  it.fails('imports the complete application surface from zmdb without internal package imports', () => {
    const report = facadeReport();

    expect(report.processProblems).toEqual([]);
    expect(report.runtimeNames).toEqual(TARGET_ROOT_VALUES);
    expect(report.typeNames).toEqual(TARGET_ROOT_TYPES);
    expect(report.missingSubpaths).toEqual([]);
    expect(REQUIRED_PRODUCT_SUBPATHS).toHaveLength(13);
  });

  // Current measured state: no optional external peer is loaded, but importing
  // the root reaches @zmdb/query-compiler/migrations and its runner through the
  // eagerly exported `migrations` namespace.
  it.fails('does not reach tooling or optional integrations when the zmdb root is imported', () => {
    const report = facadeReport();

    expect(report.processProblems).toEqual([]);
    expect(report.forbiddenImports).toEqual([]);
  });

  // Current measured state: scripts/product/catalog.mjs does not exist, so no
  // package role, facade ownership, or generated package-reference bytes can be
  // derived from a canonical source.
  it.fails('derives every official package role and facade exposure from one product catalog', async () => {
    const report = await catalogReport();

    expect(report.membershipProblems).toEqual([]);
    expect(report.facadeProblems).toEqual([]);
    expect(report.rows).toHaveLength(report.manifests.size);
    expect(report.packageReferenceBytes).not.toBe('');
  });

  it('rejects a facade export whose owning package or visibility is absent from the catalog', () => {
    const surface = {
      root: [{ name: 'schemaOf', owner: '@zmdb/schema-core' }],
      subpaths: [],
    };
    expect(verifyFacadeOwnership([], surface)).toContain(
      'facade root export schemaOf owner @zmdb/schema-core is absent from the catalog',
    );

    const hidden = [
      {
        npmName: '@zmdb/schema-core',
        facade: { root: [], subpaths: [] },
      },
    ];
    expect(verifyFacadeOwnership(hidden, surface)).toContain(
      'facade root export schemaOf is absent from @zmdb/schema-core catalog visibility',
    );
  });

  it('rejects a package-reference or integration row that disagrees with the catalog', () => {
    const catalog = [
      {
        id: 'schema',
        directory: 'packages/schema-core',
        npmName: '@zmdb/schema-core',
        role: 'schema',
        facade: { root: ['schemaOf'], subpaths: ['zmdb/schema'] },
        optionality: { kind: 'required' },
        docsOwner: 'schema-declaration',
        consumer: { reason: 'covered by the product consumer' },
      },
    ];
    const manifests = new Map([
      [
        'packages/schema-core',
        {
          manifest: {
            name: '@zmdb/schema-core',
            version: '1.0.0-alpha.4',
          },
        },
      ],
    ]);
    const first = renderPackageReferenceRows(catalog, manifests);
    const second = renderPackageReferenceRows(catalog, manifests);
    expect(second).toBe(first);

    const source = [
      '# Package reference',
      '<!-- generated: product-catalog package-reference -->',
      '| stale | row |',
      '<!-- /generated: product-catalog package-reference -->',
      '',
    ].join('\n');
    expect(
      compareGeneratedRegion(
        source,
        '<!-- generated: product-catalog package-reference -->',
        '<!-- /generated: product-catalog package-reference -->',
        first,
      ),
    ).toEqual(['generated bytes disagree with the product catalog']);
    expect(source).toContain('| stale | row |');

    const records = [
      {
        capability: 'React',
        package: '@zmdb/react',
        status: 'optional',
        peer: 'react',
        docs: 'react',
        evidence: ['fixtures/react'],
      },
    ];
    expect(renderIntegrationRows(records)).toBe(renderIntegrationRows(records));
    expect(verifyIntegrationRecords(catalog, records)).toContain(
      'integration React names uncatalogued package @zmdb/react',
    );
  });

  // Current measured state: the canonical catalog is absent, so none of the
  // six publishable package manifests has a catalog-owned fixture or reason.
  it.fails('assigns every official package an external consumer or an explicit catalog reason', async () => {
    const report = await catalogReport();

    expect(report.consumerProblems).toEqual([]);
    expect(report.rows).toHaveLength(report.manifests.size);
  });

  // The fixture itself is a real external project: one registry dependency,
  // no workspace protocol, no paths, no skipLibCheck and no @zmdb/* import.
  // The tarball process currently reaches the exact missing boundary first:
  // `zmdb/compiler` is not exported.
  it.fails('installs only zmdb and serves a validated SQLite-backed HTTP request from packed tarballs', () => {
    expect(inspectProductConsumerFixture(PRODUCT_FIXTURE)).toEqual([]);

    const result = runPackedProductConsumer(ROOT, PRODUCT_FIXTURE);
    expect(result.status, `${result.stage}\n${result.stdout}\n${result.stderr}`).toBe(0);
    const output: unknown = JSON.parse(result.stdout.trim());
    expect(output).toMatchObject({
      applied: [20260905000100],
      invalidStatus: 400,
      afterInvalid: { count: 0 },
      created: { id: 1, name: 'first order' },
      ledger: [
        {
          version: 20260905000100,
          name: 'create_orders',
          checksum: 'sha256:consumer-product-create-orders-v1',
        },
      ],
      stored: [{ id: 1, name: 'first order' }],
    });
  }, 240_000);
});
