import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  catalogFacadeOwnership,
  compareGeneratedRegion,
  discoverCatalogConsumers,
  handwrittenInventoryProblems,
  inspectProductCatalog,
  renderIntegrationRows,
  renderPackageReferenceRows,
  verifyFacadeDelegation,
  verifyFacadeOwnership,
  verifyIntegrationRecords,
  verifyProductCatalogRows,
} from '../../../.github/scripts/verify-product-catalog.mjs';
import {
  REQUIRED_PRODUCT_SUBPATHS,
  TARGET_ROOT_TYPES,
  TARGET_ROOT_VALUES,
  inspectProductConsumerFixture,
  inspectProductFacade,
  readFacadeOwnership,
  runPackedProductConsumer,
} from '../../../.github/scripts/verify-product-facade.mjs';
import {
  PACKED_BUILD_TEST_TIMEOUT_MS,
  withPackedBuildLock,
} from '../../../fixtures/client-adapters/src/packed-project.js';
import { PRODUCT_CATALOG } from '../../../scripts/product/catalog.mjs';

const ROOT = process.cwd();
const PRODUCT_FIXTURE = join(ROOT, 'fixtures', 'consumer-product');

let measuredFacade: ReturnType<typeof inspectProductFacade> | undefined;
function facadeReport(): ReturnType<typeof inspectProductFacade> {
  measuredFacade ??= inspectProductFacade(ROOT);
  return measuredFacade;
}

let measuredCatalog: ReturnType<typeof inspectProductCatalog> | undefined;
function catalogReport(): ReturnType<typeof inspectProductCatalog> {
  measuredCatalog ??= inspectProductCatalog(ROOT);
  return measuredCatalog;
}

describe('the one-product facade and catalog (#619, #622)', () => {
  // Current measured state: the root exposes 42 runtime values and 32
  // type-only declarations, while the frozen target is 19 values and 27 types.
  // Seven of the thirteen required concern/driver subpaths are also absent.
  it.fails('imports the complete application surface from zmdb without internal package imports', () => {
    const report = facadeReport();

    expect(report.processProblems).toEqual([]);
    expect(report.runtimeNames).toEqual(TARGET_ROOT_VALUES);
    expect(report.typeNames).toEqual(TARGET_ROOT_TYPES);
    expect(report.missingSubpaths).toEqual([]);
    expect(REQUIRED_PRODUCT_SUBPATHS).toHaveLength(13);
  });

  // Current measured state: no optional external peer is loaded, but importing
  // the root reaches @zmdb/query-compiler/migrations and its runner through the
  // eagerly exported `migrations` namespace.
  it.fails('does not reach tooling or optional integrations when the zmdb root is imported', () => {
    const report = facadeReport();

    expect(report.processProblems).toEqual([]);
    expect(report.forbiddenImports).toEqual([]);
  });

  it('derives every official package role and facade exposure from one product catalog', async () => {
    const report = await catalogReport();

    expect(report.membershipProblems).toEqual([]);
    expect(report.facadeProblems).toEqual([]);
    expect(report.rows).toHaveLength(report.manifests.size);
    expect(report.packageReferenceBytes).not.toBe('');
  });

  it('rejects a facade export whose owning package or visibility is absent from the catalog', () => {
    const surface = {
      root: [{ name: 'schemaOf', owner: '@zmdb/schema-core' }],
      subpaths: [],
    };
    expect(verifyFacadeOwnership([], surface)).toContain(
      'facade root export schemaOf owner @zmdb/schema-core is absent from the catalog',
    );

    const hidden = [
      {
        npmName: '@zmdb/schema-core',
        facade: { root: [], subpaths: [] },
      },
    ];
    expect(verifyFacadeOwnership(hidden, surface)).toContain(
      'facade root export schemaOf is absent from @zmdb/schema-core catalog visibility',
    );
  });

  it('rejects a package-reference or integration row that disagrees with the catalog', () => {
    const catalog = [
      {
        id: 'schema',
        directory: 'packages/schema-core',
        npmName: '@zmdb/schema-core',
        role: 'schema',
        facade: { root: ['schemaOf'], subpaths: ['zmdb/schema'] },
        optionality: { kind: 'required' },
        docsOwner: 'schema-declaration',
        consumer: { reason: 'covered by the product consumer' },
      },
    ] as const;
    const manifests = new Map([
      [
        'packages/schema-core',
        {
          manifest: {
            name: '@zmdb/schema-core',
            version: '1.0.0-alpha.4',
          },
        },
      ],
    ]);
    const first = renderPackageReferenceRows(catalog, manifests);
    const second = renderPackageReferenceRows(catalog, manifests);
    expect(second).toBe(first);

    const source = [
      '# Package reference',
      '<!-- generated: product-catalog package-reference -->',
      '| stale | row |',
      '<!-- /generated: product-catalog package-reference -->',
      '',
    ].join('\n');
    expect(
      compareGeneratedRegion(
        source,
        '<!-- generated: product-catalog package-reference -->',
        '<!-- /generated: product-catalog package-reference -->',
        first,
      ),
    ).toEqual(['generated bytes disagree with the product catalog']);
    expect(source).toContain('| stale | row |');

    const records = [
      {
        capability: 'React',
        package: '@zmdb/react',
        status: 'optional',
        peers: ['react'],
        docs: 'react',
        evidence: ['fixtures/react'],
      },
    ];
    expect(renderIntegrationRows(records)).toBe(renderIntegrationRows(records));
    expect(verifyIntegrationRecords(catalog, records)).toContain(
      'integration React names uncatalogued package @zmdb/react',
    );
  });

  it('assigns every official package an external consumer or an explicit catalog reason', async () => {
    const report = await catalogReport();

    expect(report.consumerProblems).toEqual([]);
    expect(report.rows).toHaveLength(report.manifests.size);
  });

  it('accounts for every official package exactly once and rejects stale catalog rows', async () => {
    const report = await catalogReport();
    expect(report.membershipProblems).toEqual([]);
    expect(report.rows).toHaveLength(27);
    expect(report.manifests.size).toBe(27);

    const pages = new Set(PRODUCT_CATALOG.map(row => row.docsOwner));
    const staleManifests = new Map(report.manifests);
    const first = PRODUCT_CATALOG[0];
    if (first === undefined) throw new Error('product catalog is empty');
    staleManifests.delete(first.directory);
    expect(verifyProductCatalogRows(PRODUCT_CATALOG, staleManifests, pages)).toContain(
      `catalog package directory ${first.directory} has no manifest`,
    );

    const unregistered = new Map(report.manifests);
    unregistered.set('packages/unregistered', {
      manifest: { name: '@zmdb/unregistered' },
    });
    expect(verifyProductCatalogRows(PRODUCT_CATALOG, unregistered, pages)).toContain(
      'official package manifest packages/unregistered/package.json has no catalog row',
    );
  });

  it('derives root and subpath facade ownership from the catalog', () => {
    const actual = readFacadeOwnership(ROOT);
    const derived = catalogFacadeOwnership(PRODUCT_CATALOG);

    expect(derived.root).toHaveLength(71);
    expect(derived.subpaths).toHaveLength(14);
    expect(actual.root).toEqual(derived.root);
    expect(actual.subpaths.map(item => item.name)).toEqual(derived.subpaths.map(item => item.name));
    expect(verifyFacadeOwnership(PRODUCT_CATALOG, actual)).toEqual([]);
    expect(verifyFacadeDelegation(ROOT, PRODUCT_CATALOG)).toEqual([]);
  });

  it('generates package-reference and support-matrix rows without a handwritten package list', async () => {
    const report = await catalogReport();
    expect(report.generatedProblems).toEqual([]);
    expect(report.packageReferenceBytes).toContain('@zmdb/schema-core');
    expect(report.packageReferenceBytes).toContain('npm add @zmdb/jobs@1.0.0-alpha.4');
    expect(report.packageReferenceBytes).toMatch(/\|\s+zmdb\s+\|/);
    expect(handwrittenInventoryProblems(ROOT, PRODUCT_CATALOG)).toEqual([]);

    const records = [
      {
        capability: 'Vercel AI SDK',
        package: '@zmdb/ai-vercel',
        status: 'optional',
        peers: ['ai'],
        docs: 'llm-vercel-ai-sdk',
        evidence: ['fixtures/llm-adapters'],
      },
    ];
    expect(verifyIntegrationRecords(PRODUCT_CATALOG, records)).toEqual([]);
    expect(renderIntegrationRows(records)).toContain('Vercel AI SDK');
    expect(renderIntegrationRows(records)).toContain('@zmdb/ai-vercel');
  });

  it('discovers every packed external consumer from its catalog owner', () => {
    const report = discoverCatalogConsumers(ROOT, PRODUCT_CATALOG);

    expect(report.problems).toEqual([]);
    expect(report.assignments).toHaveLength(27);
    expect(report.assignments.filter(assignment => 'fixture' in assignment)).toHaveLength(19);
    expect(report.assignments.filter(assignment => 'reason' in assignment)).toHaveLength(8);
  });

  it('rejects an undocumented package, duplicate public role, or facade export with no owner', async () => {
    const report = await catalogReport();
    const pages = new Set(PRODUCT_CATALOG.map(row => row.docsOwner));
    const first = PRODUCT_CATALOG[0];
    const second = PRODUCT_CATALOG[1];
    if (first === undefined || second === undefined) throw new Error('product catalog needs two rows');

    const undocumented = Object.freeze(
      PRODUCT_CATALOG.map(row => (row === first ? Object.freeze({ ...row, docsOwner: 'missing-page' }) : row)),
    );
    expect(verifyProductCatalogRows(undocumented, report.manifests, pages)).toContain(
      `catalog package ${first.npmName} docs owner missing-page is absent from the page registry`,
    );

    const duplicateRole = Object.freeze(
      PRODUCT_CATALOG.map(row => (row === second ? Object.freeze({ ...row, role: first.role }) : row)),
    );
    expect(verifyProductCatalogRows(duplicateRole, report.manifests, pages)).toContain(
      `duplicate catalog role ${first.role}`,
    );

    expect(
      verifyFacadeOwnership(PRODUCT_CATALOG, {
        root: [{ name: 'orphanedFacadeExport', owner: '@zmdb/missing' }],
        subpaths: [],
      }),
    ).toContain('facade root export orphanedFacadeExport owner @zmdb/missing is absent from the catalog');
  });

  it('exposes package membership to release governance without encoding versions or publish actions', () => {
    const releaseFields = [
      'changelog',
      'credentials',
      'distTag',
      'npmTag',
      'publish',
      'publishOrder',
      'releaseNotes',
      'tag',
      'version',
    ];

    expect(PRODUCT_CATALOG.map(row => row.id)).toEqual(PRODUCT_CATALOG.map(row => row.id).toSorted());
    for (const row of PRODUCT_CATALOG) {
      expect(Object.keys(row).toSorted()).toEqual([
        'consumer',
        'directory',
        'docsOwner',
        'facade',
        'id',
        'npmName',
        'optionality',
        'role',
      ]);
      expect(Object.isFrozen(row)).toBe(true);
      expect(Object.isFrozen(row.facade)).toBe(true);
      expect(Object.isFrozen(row.facade.root)).toBe(true);
      expect(Object.isFrozen(row.facade.subpaths)).toBe(true);
      expect(Object.isFrozen(row.optionality)).toBe(true);
      expect(Object.isFrozen(row.consumer)).toBe(true);
      for (const field of releaseFields) expect(Object.hasOwn(row, field)).toBe(false);
    }
    expect(Reflect.set(PRODUCT_CATALOG[0] ?? {}, 'version', '9.9.9')).toBe(false);
  });

  // The fixture itself is a real external project: one registry dependency,
  // no workspace protocol, no paths, no skipLibCheck and no @zmdb/* import.
  // The tarball process currently reaches the exact missing boundary first:
  // `zmdb/compiler` is not exported.
  it.fails(
    'installs only zmdb and serves a validated SQLite-backed HTTP request from packed tarballs',
    () => {
      expect(inspectProductConsumerFixture(PRODUCT_FIXTURE)).toEqual([]);

      const result = withPackedBuildLock(ROOT, () => runPackedProductConsumer(ROOT, PRODUCT_FIXTURE));
      expect(result.status, `${result.stage}\n${result.stdout}\n${result.stderr}`).toBe(0);
      const output: unknown = JSON.parse(result.stdout.trim());
      expect(output).toMatchObject({
        applied: [20260905000100],
        invalidStatus: 400,
        afterInvalid: { count: 0 },
        created: { id: 1, name: 'first order' },
        ledger: [
          {
            version: 20260905000100,
            name: 'create_orders',
            checksum: 'sha256:consumer-product-create-orders-v1',
          },
        ],
        stored: [{ id: 1, name: 'first order' }],
      });
    },
    PACKED_BUILD_TEST_TIMEOUT_MS,
  );
});
