// Complete schema concern: declarations, derivation, DTOs, relations, IR,
// JSON Schema, custom codecs, and naming. Every name delegates by identity.

export {
  ValidationError,
  aliasRow,
  applyOrderBy,
  applyPagination,
  attachPopulated,
  buildListResult,
  claimsValidationIssues,
  compilePopulate,
  compileWhere,
  createStateUpdatePayload,
  defineEntityStateMachine,
  defineStateTransitions,
  isRecord,
  resolveRelation,
  schemaOf,
  validationIssuesOf,
} from '@zmdb/schema-core';
export type {
  AllowedTargetStates,
  ColumnFlags,
  ColumnMeta,
  ColumnsMap,
  CoreSchema,
  CreateDTO,
  DeclaredTable,
  Entity,
  EntityStateMachine,
  EntityStateMachineOptions,
  JoinRow,
  ListDTO,
  ListResult,
  OrderByDTO,
  OrderTarget,
  PaginationDTO,
  PopulateDialect,
  PopulateQuery,
  Populated,
  PopulatedEntity,
  PrimaryKeyOf,
  ReadDTO,
  ResolvedRelation,
  SqlType,
  StateTransitions,
  StateUpdateDTO,
  TaggedSchema,
  UpdateDTO,
  ValidationIssue,
  ValidationRule,
  WhereDTO,
} from '@zmdb/schema-core';

export type {
  AnyRelation,
  Codec,
  ColumnSqlType,
  Ext,
  ForeignKey,
  Fts,
  HasDefault,
  Length,
  ManyToMany,
  ManyToOne,
  Max,
  MaxLength,
  Min,
  MinLength,
  NonNull,
  Nullable,
  Numeric,
  OnDelete,
  OnUpdate,
  OneToMany,
  OneToOne,
  Pattern,
  Physical,
  PrimaryKey,
  Proto,
  ProtoField,
  References,
  ReferentialAction,
  RelationKind,
  Rowstore,
  Rule,
  Sensitive,
  Serial,
  ShardKey,
  SoftDelete,
  SortKey,
  Sql,
  Table,
  Unique,
  WireAs,
} from '@zmdb/schema-core/tags';

export type {
  ColumnKeys,
  DefaultKeys,
  GetDTO,
  GetOptions,
  KeysCarrying,
  NullableKeys,
  PrimaryKeyKeys,
  Projection,
  RelationKeys,
  SensitiveKeys,
  SerialKeys,
  SoftDeleteKeys,
  UniqueKeys,
  Wire,
  WireCreateDTO,
} from '@zmdb/schema-core/derive';

export {
  applyKeysetFilter,
  buildSearchResult,
  decodeCursor,
  describeAggregate,
  encodeCursor,
  getResult,
  project,
} from '@zmdb/schema-core/dto';
export type {
  AggFn,
  AggregateColumn,
  AggregateResult,
  AggregateSpec,
  ComputedSpec,
  FieldOps,
  OffsetPage,
  OrderBySpec,
  OrderDir,
  PaginationSpec,
  SearchDTO,
  SearchHit,
  SearchResult,
  SubqueryTarget,
  UnknownRow,
  WhereTarget,
} from '@zmdb/schema-core/dto';

export {
  KNOWN_CONSTRAINT_KINDS,
  PROTO_SCALARS,
  RELATION_KINDS,
  SQL_TYPES,
  appTypeOf,
  dbDecodedColumns,
  decodeDbValue,
  decodeWire,
  decodeWireValue,
  encodeWire,
  encodeWireValue,
  jsonSchemaForColumn,
  jsonSchemaFromIR,
  jsonSchemaFromShape,
  jsonSchemaFromTypeIR,
  objectTypeFromIR,
  objectTypeFromShape,
  schemaFromIR,
  shapeOfVariant,
  wireTypeOf,
} from '@zmdb/schema-core/ir';
export type {
  ArrayIR,
  CodecRegistry,
  ColumnIR,
  ConstraintKind,
  Constraints,
  ExtensionType,
  ForeignKeyIR,
  JsonValue,
  Layer,
  LiteralIR,
  NullIR,
  ObjectIR,
  PropertyIR,
  ProtoScalar,
  RefIR,
  RelationIR,
  ScalarIR,
  ScalarKind,
  SchemaIR,
  ShapeColumnIR,
  ShapeIR,
  TableOptions,
  TagField,
  TupleIR,
  TypeIR,
  UndefinedIR,
  UnionIR,
  UnknownIR,
  UnsupportedIR,
} from '@zmdb/schema-core/ir';

export {
  componentName,
  toJsonSchema,
  toJsonSchemaWithRelations,
  toListSchema,
  toOpenApiComponents,
  toSearchSchema,
} from '@zmdb/schema-core/openapi';
export type { EnvelopeSchema, JsonSchemaObject, Variant } from '@zmdb/schema-core/openapi';

export { decodeValue, defineType, encodeValue, wireCodec } from '@zmdb/schema-core/custom-types';
export type { CustomType } from '@zmdb/schema-core/custom-types';

export { resolveNaming, snakeCase, snakeCasePlural } from '@zmdb/schema-core/naming';
export type { NamingStrategy, NamingStrategyConfig, NamingStrategyName } from '@zmdb/schema-core/naming';
