// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Direct SQL compilation and DDL concern. Migration execution and catalog
// introspection live under `@zmdb/core/migrations`.

export {
  DISTANCE_OPERATORS,
  EXPR,
  InvalidOperatorError,
  OP_MAP,
  QueryCompilerError,
  UnsupportedFeatureError,
  appendComment,
  coalesce,
  concat,
  createQueryCompiler,
  dec,
  defineSqlDialect,
  dialectCapabilities,
  dialectFamily,
  dialectName,
  dialectSupportsReturning,
  dialectTraits,
  distance,
  extendSqlDialect,
  formatPlaceholder,
  inc,
  isSqlDialect,
  mul,
  not,
  proposed,
  quoteColumn,
  quoteIdentifier,
  quoteTable,
  renderPredicate,
  renumberPlaceholders,
  serializeComment,
  sqlOperator,
  stContains,
  stDWithin,
  withComments,
} from '@zmdb/sql';
export {
  type AliasedColumn,
  type AliasedDistanceExpression,
  type ColumnExpr,
  type CommentKey,
  type CommentKeys,
  type CommentPairs,
  type ComparisonPredicate,
  type CompiledQuery,
  type DatabaseCapabilities,
  type DeleteBuilder,
  type DialectFeature,
  type DialectSqlType,
  type DialectTarget,
  type DialectTypeMap,
  type Direction,
  type DistanceExpression,
  type DistanceOp,
  type ExtensionColumnOf,
  type GeoJsonGeometry,
  type GeometryColumnOf,
  type GeometryValueOf,
  type InsertBuilder,
  type OnConflictBuilder,
  type Operator,
  type PaginationTail,
  type PlaceholderStyle,
  type Predicate,
  type PredicateGroup,
  type QueryCompiler,
  type QueryCompilerOptions,
  type QueryEffects,
  type QueryTelemetry,
  type ResolvedDialectTraits,
  type ReturningCapability,
  type ReturningStatement,
  type ReturningStyle,
  type SchemaObjectOperation,
  type SelectBuilder,
  type SetValue,
  type SpatialPredicate,
  type SqlDialect,
  type SqlDialectDefinition,
  type SqlDialectExtension,
  type UpdateBuilder,
  type VectorColumnOf,
} from '@zmdb/sql';

export { escapeFts5Term, trustedTable } from '@zmdb/sql';
export type { JoinCondition, JoinKind, QueryPredicate, TrustedTable } from '@zmdb/sql';

export { SET_KEYWORD, batch, setOperation } from '@zmdb/sql/set-ops';
export { type BatchHandle, type SetOp } from '@zmdb/sql/set-ops';

export {
  checkConstraintDdl,
  createExtensionDdl,
  createIndexDdl,
  createPolicyDdl,
  createRoutineDdl,
  createSchemaDdl,
  createSequenceDdl,
  createViewDdl,
  ddlType,
  dropRoutineDdl,
  dropViewDdl,
  enableRlsDdl,
  generatedColumnDdl,
  qualify,
  quoteId,
  replaceRoutineStatements,
  routineFingerprint,
} from '@zmdb/sql/schema-objects';
export {
  type ExtensionDef,
  type GeneratedColumn,
  type IndexColumn,
  type IndexDef,
  type IndexMethod,
  type RlsPolicy,
  type RoutineDef,
  type RoutineSqlType,
  type SequenceDef,
  type ViewDef,
} from '@zmdb/sql/schema-objects';

export { singularPascalCase } from '@zmdb/schema/naming';
