// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Direct SQL compilation and DDL concern. Migration execution and catalog
// introspection live under `@zmdb/core/migrations`.

export {
  DISTANCE_OPERATORS,
  EXPR,
  OP_MAP,
  QueryCompilerError,
  UnsupportedFeatureError,
  appendComment,
  assertNoWindowFunction,
  checkDialectCapability,
  coalesce,
  concat,
  createQueryCompiler,
  dec,
  defineSqlDialect,
  dialectCapabilities,
  dialectFamily,
  dialectName,
  dialectSupportsReturning,
  dialectTraits,
  distance,
  extendSqlDialect,
  formatPlaceholder,
  inc,
  isSqlDialect,
  isWindowFunctionBuilder,
  isWindowProjectionNode,
  mul,
  not,
  proposed,
  quoteColumn,
  quoteIdentifier,
  quoteTable,
  renderPredicate,
  renderWindowProjectionNode,
  renumberPlaceholders,
  serializeComment,
  stContains,
  stDWithin,
  windowFunction,
  withComments,
} from '@zmdb/sql';
export type {
  AliasedColumn,
  AliasedDistanceExpression,
  ColumnExpr,
  CommentKey,
  CommentKeys,
  CommentPairs,
  ComparisonPredicate,
  CompiledQuery,
  CteSpec,
  DatabaseCapabilities,
  DeleteBuilder,
  DialectFeature,
  DialectSqlType,
  DialectTarget,
  DialectTypeMap,
  Direction,
  DistanceExpression,
  DistanceOp,
  ExtensionColumnOf,
  GeoJsonGeometry,
  GeometryColumnOf,
  GeometryValueOf,
  InsertBuilder,
  OnConflictBuilder,
  Operator,
  PaginationTail,
  PlaceholderStyle,
  Predicate,
  PredicateGroup,
  ProjectionItem,
  QueryCompiler,
  QueryCompilerOptions,
  QueryEffects,
  QueryTelemetry,
  ResolvedDialectTraits,
  ReturningCapability,
  ReturningColumn,
  ReturningStatement,
  ReturningStyle,
  SchemaObjectOperation,
  SelectBuilder,
  SelectedColumn,
  SetValue,
  SpatialPredicate,
  SqlDialect,
  SqlDialectDefinition,
  SqlDialectExtension,
  SubqueryInput,
  UpdateBuilder,
  VectorColumnOf,
  WindowFunctionBuilder,
  WindowProjectionNode,
} from '@zmdb/sql';

export { escapeFts5Term, trustedTable } from '@zmdb/sql';
export type { JoinCondition, JoinKind, QueryPredicate, TrustedTable } from '@zmdb/sql';

export { SET_KEYWORD, batch, setOperation } from '@zmdb/sql/set-ops';
export { type BatchHandle, type SetOp } from '@zmdb/sql/set-ops';

export {
  checkConstraintDdl,
  createExtensionDdl,
  createIndexDdl,
  createPolicyDdl,
  createRoutineDdl,
  createSchemaDdl,
  createSequenceDdl,
  createViewDdl,
  ddlType,
  dropRoutineDdl,
  dropViewDdl,
  enableRlsDdl,
  generatedColumnDdl,
  qualify,
  quoteId,
  replaceRoutineStatements,
  routineFingerprint,
} from '@zmdb/sql/schema-objects';
export {
  type ExtensionDef,
  type GeneratedColumn,
  type IndexColumn,
  type IndexDef,
  type IndexMethod,
  type RlsPolicy,
  type RoutineDef,
  type RoutineSqlType,
  type SequenceDef,
  type ViewDef,
} from '@zmdb/sql/schema-objects';

export { singularPascalCase } from '@zmdb/schema/naming';
