// Direct SQL compilation and DDL concern. Migration execution and catalog
// introspection live under `zmdb/migrations`.

export {
  DISTANCE_OPERATORS,
  EXPR,
  OP_MAP,
  QueryCompilerError,
  UnsupportedFeatureError,
  appendComment,
  assertNoWindowFunction,
  checkDialectCapability,
  coalesce,
  concat,
  createQueryCompiler,
  dec,
  defineSqlDialect,
  dialectCapabilities,
  dialectFamily,
  dialectName,
  dialectSupportsReturning,
  dialectTraits,
  distance,
  extendSqlDialect,
  formatPlaceholder,
  inc,
  isSqlDialect,
  isWindowFunctionBuilder,
  isWindowProjectionNode,
  mul,
  not,
  proposed,
  quoteColumn,
  quoteIdentifier,
  quoteTable,
  renderPredicate,
  renderWindowProjectionNode,
  renumberPlaceholders,
  serializeComment,
  stContains,
  stDWithin,
  windowFunction,
  withComments,
} from '@zmdb/query-compiler';
export type {
  AliasedColumn,
  AliasedDistanceExpression,
  ColumnExpr,
  CommentKey,
  CommentKeys,
  CommentPairs,
  ComparisonPredicate,
  CompiledQuery,
  CteSpec,
  DatabaseCapabilities,
  DeleteBuilder,
  DialectFeature,
  DialectSqlType,
  DialectTarget,
  DialectTypeMap,
  Direction,
  DistanceExpression,
  DistanceOp,
  ExtensionColumnOf,
  GeoJsonGeometry,
  GeometryColumnOf,
  GeometryValueOf,
  InsertBuilder,
  OnConflictBuilder,
  Operator,
  PaginationTail,
  PlaceholderStyle,
  Predicate,
  PredicateGroup,
  ProjectionItem,
  QueryCompiler,
  QueryCompilerOptions,
  QueryTelemetry,
  ResolvedDialectTraits,
  ReturningCapability,
  ReturningColumn,
  ReturningStatement,
  ReturningStyle,
  SchemaObjectOperation,
  SelectBuilder,
  SelectedColumn,
  SetValue,
  SpatialPredicate,
  SqlDialect,
  SqlDialectDefinition,
  SqlDialectExtension,
  SubqueryInput,
  UpdateBuilder,
  VectorColumnOf,
  WindowFunctionBuilder,
  WindowProjectionNode,
} from '@zmdb/query-compiler';

export { escapeFts5Term, ftsSelectFrom } from '@zmdb/query-compiler/fts';
export type { FtsOptions, FtsSelect, FtsTableOptions } from '@zmdb/query-compiler/fts';

export { joinableSelectFrom } from '@zmdb/query-compiler/joins';
export type { JoinCondition, JoinKind, JoinableSelect } from '@zmdb/query-compiler/joins';

export { aggregateSelectFrom } from '@zmdb/query-compiler/aggregations';
export type { AggregateSelect } from '@zmdb/query-compiler/aggregations';

export { SET_KEYWORD, batch, setOperation } from '@zmdb/query-compiler/set-ops';
export type { BatchHandle, SetOp } from '@zmdb/query-compiler/set-ops';

export {
  checkConstraintDdl,
  createExtensionDdl,
  createIndexDdl,
  createPolicyDdl,
  createRoutineDdl,
  createSchemaDdl,
  createSequenceDdl,
  createViewDdl,
  ddlType,
  dropRoutineDdl,
  dropViewDdl,
  enableRlsDdl,
  generatedColumnDdl,
  qualify,
  quoteId,
  replaceRoutineStatements,
  routineFingerprint,
} from '@zmdb/query-compiler/schema-objects';
export type {
  ExtensionDef,
  GeneratedColumn,
  IndexColumn,
  IndexDef,
  IndexMethod,
  RlsPolicy,
  RoutineDef,
  RoutineSqlType,
  SequenceDef,
  ViewDef,
} from '@zmdb/query-compiler/schema-objects';

export { singularPascalCase } from '@zmdb/query-compiler/naming';
