// zmdb/web/contract — curated runtime re-export of @zmdb/web/contract.
export { defineHttpContract, httpOperation } from '@zmdb/web/contract';
export type {
  AuthorizationCodeFlow,
  ClientCredentialsFlow,
  CompiledHttpContract,
  CompiledHttpOperation,
  HttpBodyDeclaration,
  HttpBodyIR,
  HttpBodyKind,
  HttpContractDeclaration,
  HttpContractIR,
  HttpController,
  HttpMethod,
  HttpOperationDeclaration,
  HttpOperationIR,
  HttpOperationTypes,
  HttpParameterDeclaration,
  HttpParameterIR,
  HttpRequestBodyDeclaration,
  HttpRequestBodyIR,
  HttpResponseDeclaration,
  HttpResponseHeaderDeclaration,
  HttpResponseHeaderIR,
  HttpResponseIR,
  HttpTypeIR,
  HttpVersionDeclaration,
  HttpVersionIR,
  ImplicitFlow,
  JsonValue,
  OAuthFlow,
  OAuthFlows,
  PasswordFlow,
  SecurityRequirement,
  SecurityScheme,
} from '@zmdb/web/contract';
