// zmdb/web — umbrella re-export of the app kernel and HTTP framework.
// (No `export *`: every public symbol is enumerated, type exports separated.)
export {
  Container,
  Inject,
  Module,
  UnresolvedTokenError,
  compileModule,
  createToken,
  injectionsOf,
  lazy,
  metadataOf,
  moduleDefOf,
} from '@zmdb/app';
export { repositoryToken } from '@zmdb/app/data';
export {
  SpanKind,
  consumerSpan,
  fromTraceContext,
  fromTraceparent,
  toTraceHeaders,
  toTraceparent,
  tracedDriver,
} from '@zmdb/app/observability';
export { defineState, transition } from '@zmdb/app/state';
export type {
  ApplicationMetadata as WebMetadata,
  CompiledModule,
  Constructor,
  LazyImport,
  LazyModuleHandle,
  LazyStatus,
  ModuleClass,
  ModuleDef,
  OnApplicationBootstrap,
  OnModuleInit,
  OnShutdown,
  ProviderDef,
  Scope,
  Token,
} from '@zmdb/app';
export type {
  Attributes,
  CommentKey,
  CommentKeys,
  CommentPairs,
  ExecutingDriver,
  Meter,
  Observability,
  QueryTelemetry,
  Span,
  SpanContext,
  SpanOptions,
  TraceCarrier,
  Tracer,
} from '@zmdb/app/observability';
export type { Brand, State } from '@zmdb/app/state';

export {
  ChainError,
  Controller,
  Delete,
  Gateway,
  Get,
  Patch,
  Post,
  Put,
  Subscribe,
  UseFilters,
  UseGuards,
  UseInterceptors,
  UsePipes,
  Version,
  VersionNeutral,
  bodyText,
  bytes,
  compilePattern,
  compileRouteChain,
  compress,
  compressionInterceptor,
  countSegments,
  createApp,
  createCsrf,
  createGatewayDispatcher,
  createRouter,
  createStaticHandler,
  createTracedRouter,
  defineHttpContract,
  dtoChain,
  extractParams,
  file,
  getRoutes,
  getSubscriptions,
  httpOperation,
  json,
  matchCompiled,
  multipartPipe,
  parseMultipart,
  respond,
  runChain,
  serializationInterceptor,
  serveOpenApi,
  sseStream,
  stream,
  text,
  toFetchHandler,
  toNodeHandler,
  toOpenApi,
  validateWith,
  validationPipe,
  versionsOf,
  UPLOAD_DEFAULTS,
} from '@zmdb/web';
export type {
  App,
  AnyCtx,
  Chain,
  ChainHandler,
  CompressionOptions,
  ContentCoding,
  CompiledPattern,
  Ctx,
  Csrf,
  CsrfOptions,
  DtoChainOptions,
  ExceptionFilter,
  FilterInput,
  GatewayDispatcher,
  Guard,
  GuardInput,
  HandlerFor,
  HttpBodyDeclaration,
  HttpBodyIR,
  HttpBodyKind,
  HttpContractDeclaration,
  HttpContractIR,
  HttpController,
  HttpMethod,
  HttpOperationDeclaration,
  HttpOperationIR,
  HttpOperationTypes,
  HttpParameterDeclaration,
  HttpParameterIR,
  HttpRequestBodyDeclaration,
  HttpRequestBodyIR,
  HttpResponseDeclaration,
  HttpResponseHeaderDeclaration,
  HttpResponseHeaderIR,
  HttpResponseIR,
  HttpTypeIR,
  HttpVersionDeclaration,
  HttpVersionIR,
  Interceptor,
  InterceptorInput,
  JsonSchema,
  JsonValue,
  MessageCtx,
  OpenApiDocument,
  OpenApiRenderOptions,
  OAuthFlow,
  OAuthFlows,
  PathParams,
  Pipe,
  PipeInput,
  QueryValues,
  ResolvedRoute,
  ResponseOptions,
  ResponseBody,
  RouteDefinition,
  RouteOptions,
  Router,
  SecurityRequirement,
  SecurityScheme,
  SseFrame,
  StaticHandler,
  StaticOptions,
  Subscription,
  StreamOptions,
  FileResponseOptions,
  AdapterOptions,
  WebRequest,
  WebResponse,
  VersionStrategy,
  Multipart,
  UploadLimits,
  UploadPart,
} from '@zmdb/web';
