// Upstream functional-test inventories — the denominator for the API coverage gate
// (.github/scripts/verify-api-coverage.mjs).
//
// docs-site/coverage/inventory.mjs already pins what Drizzle, MikroORM, NestJS and Typia
// *document*. This pins what they *test*, which is the stronger claim to answer: a documented
// feature is a promise, a tested one is a behaviour someone depends on. Kysely is here and not
// in the docs inventory because its site is API reference generated from source — there are no
// prose pages to enumerate, but there are 650 assertions.
//
// Harvested from each project's test tree at the commit below. Refresh with:
//
//   node scripts/harvest-api-tests.mjs [--write]
//
// The unit differs per upstream, because their test trees are shaped differently and a uniform
// unit would misrepresent all five. Each row records how many upstream assertions it subsumes,
// so the gate reports a real denominator rather than a row count. See the script header for the
// per-source rule and for what is excluded (driver bindings, transports, regression tests filed
// against internal bugs, and each project's own test plumbing).
//
// Everything else is in scope: a row here must map to a zmdb test or to an argued exclusion in
// ./mapping.mjs.

export const SOURCES = {
  kysely: {
    label: 'Kysely',
    role: 'query builder',
    repo: 'kysely-org/kysely',
    branch: 'master',
    commit: 'b9674df67734fb7a68a2a49bf5b1754a16776481',
    testDir: 'test/node/src',
    unit: 'describe suite',
  },
  drizzle: {
    label: 'Drizzle ORM',
    role: 'schema + query builder',
    repo: 'drizzle-team/drizzle-orm',
    branch: 'main',
    commit: 'b7862528fd8fc39bc2653a6c18dad7c1f4e68d10',
    testDir: 'integration-tests/tests',
    unit: 'test title',
  },
  'mikro-orm': {
    label: 'MikroORM',
    role: 'repository / unit of work',
    repo: 'mikro-orm/mikro-orm',
    branch: 'master',
    commit: '0406ee75228513d1d5b83fbaf80e2da6b35b3be5',
    testDir: 'tests/features',
    unit: 'feature area',
  },
  nestjs: {
    label: 'NestJS',
    role: 'HTTP application framework',
    repo: 'nestjs/nest',
    branch: 'master',
    commit: '39fbddae51281ca56bf2fed9123d98e61509066c',
    testDir: 'integration',
    unit: 'e2e spec',
  },
  typia: {
    label: 'Typia',
    role: 'AOT validation',
    repo: 'samchon/typia',
    branch: 'master',
    commit: '00872d2952ecdb06c548c83fb4f2a376256b7d9a',
    testDir: 'tests',
    unit: 'public API function',
  },
};

export const INVENTORY = {
  kysely: {
    'aggregate-function > aggregate functions': 20,
    'aggregate-function > aggregate functions > execute order-sensitive aggregate functions': 2,
    'array > arrays': 3,
    'async-dispose > async dispose': 1,
    'camel-case > camel case': 9,
    cancellation: 10,
    'cancellation > ConnectionBuilder': 2,
    case: 9,
    clear: 15,
    coalesce: 3,
    'controlled-transaction > controlled transaction': 10,
    'controlled-transaction > custom dialect: controlled transaction': 3,
    'deduplicate-joins > deduplicate joins': 4,
    delete: 38,
    'execute > executeTakeFirstOrThrow': 3,
    'execute > Kysely.executeQuery': 2,
    explain: 7,
    'expression > expressions': 1,
    'file-migration-provider > FileMigrationProvider > files': 2,
    'group-by > group by': 7,
    'handle-empty-in-lists-plugin > handle empty in lists plugin > strategy': 12,
    having: 3,
    'immediate-value-plugin > ImmediateValuePlugin': 1,
    'insert > insert into': 30,
    'introspect > getSchemas': 1,
    'introspect > getTables': 1,
    'introspect > getTables > implicit autoincrement': 1,
    'join > cross join': 1,
    'join > cross join > apply': 2,
    'join > cross join > lateral join': 3,
    'join > inner join': 6,
    'join > left join': 5,
    'join > right join': 1,
    'join > right join > full join': 1,
    'json > json helpers': 13,
    'json-traversal > json traversal > JSON reference using JSON Path syntax ($)': 11,
    'json-traversal > json traversal > JSON reference using style syntax (->->->>)': 10,
    'json-traversal > json traversal > Standalone JSON path syntax ($)': 1,
    'logging > when query execution fails > when query logging is disabled': 4,
    'logging > when query execution fails > when query logging is enabled': 4,
    'logging > when query execution succeeds > when query logging is disabled': 4,
    'logging > when query execution succeeds > when query logging is enabled': 4,
    merge: 10,
    'merge > multiple whens': 1,
    'merge > using': 5,
    'merge > whenMatched': 5,
    'merge > whenMatched > update': 6,
    'merge > whenNotMatched': 1,
    'merge > whenNotMatched > insert': 16,
    'migration > getMigrations': 1,
    'migration > migrateDown': 3,
    'migration > migrateDown > custom migration tables in a custom schema': 1,
    'migration > migrateDown > Migrate up should work when timestamps are equal': 1,
    'migration > migrateTo': 4,
    'migration > migrateTo > with allowUnorderedMigrations enabled': 4,
    'migration > migrateToLatest': 7,
    'migration > migrateToLatest > using folder of migration files': 1,
    'migration > migrateToLatest > with allowUnorderedMigrations': 2,
    'migration > migrateUp': 10,
    'order-by > order by': 11,
    'parse-json-results-plugin > ParseJSONResultsPlugin': 1,
    "parse-json-results-plugin > ParseJSONResultsPlugin > when `objectStrategy` is 'create'": 1,
    'plugin-composition > plugin composition > transformQuery': 1,
    'plugin-composition > plugin composition > transformResult': 1,
    'raw-query > raw queries': 6,
    'raw-sql > raw sql': 13,
    'replace > replace into': 5,
    'safe-null-comparison-plugin > safe null comparison': 8,
    'sanitize-identifiers > sanitize identifiers': 2,
    'schema > alter table': 4,
    'schema > alter table > add check constraint': 1,
    'schema > alter table > add column': 16,
    'schema > alter table > add foreign key constraint': 2,
    'schema > alter table > add index': 6,
    'schema > alter table > add primary key constraint': 3,
    'schema > alter table > add unique constraint': 6,
    'schema > alter table > drop column': 3,
    'schema > alter table > drop constraint': 1,
    'schema > alter table > drop index': 1,
    'schema > alter table > mixed column alterations': 2,
    'schema > alter table > parse schema name': 1,
    'schema > alter table > rename': 1,
    'schema > alter table > rename column': 2,
    'schema > alter table > rename constraint': 1,
    'schema > alter table > set schema': 1,
    'schema > create index': 13,
    'schema > create schema': 2,
    'schema > create table': 42,
    'schema > create view': 5,
    'schema > drop index': 4,
    'schema > drop schema': 4,
    'schema > drop schema > alter type': 8,
    'schema > drop schema > create type': 1,
    'schema > drop schema > drop type': 5,
    'schema > drop table': 5,
    'schema > drop view': 4,
    'schema > refresh materialized view': 3,
    select: 47,
    'set-operation > set operations': 11,
    'sql-injection > select': 11,
    transaction: 8,
    update: 28,
    where: 26,
    'where > whereRef': 1,
    with: 11,
    'with-schema > with schema > create index': 2,
    'with-schema > with schema > create table': 1,
    'with-schema > with schema > create view': 1,
    'with-schema > with schema > delete from': 2,
    'with-schema > with schema > drop view': 1,
    'with-schema > with schema > insert into': 1,
    'with-schema > with schema > merge into': 1,
    'with-schema > with schema > select from': 8,
    'with-schema > with schema > update': 1,
    'with-schema > with schema > with': 2,
  },
  drizzle: {
    '[Find Many] Get deep select {}': 1,
    '[Find Many] Get groups with users': 1,
    '[Find Many] Get groups with users + limit': 1,
    '[Find Many] Get groups with users + limit + where': 1,
    '[Find Many] Get groups with users + orderBy': 1,
    '[Find Many] Get groups with users + where': 1,
    '[Find Many] Get only custom fields': 1,
    '[Find Many] Get only custom fields + where': 1,
    '[Find Many] Get only custom fields + where + limit': 1,
    '[Find Many] Get only custom fields + where + orderBy': 1,
    '[Find Many] Get schema users - dbName & tsName match': 1,
    '[Find Many] Get schema users - dbName & tsName mismatch': 1,
    '[Find Many] Get select {}': 1,
    '[Find Many] Get users with groups': 1,
    '[Find Many] Get users with groups + limit': 1,
    '[Find Many] Get users with groups + limit + where': 1,
    '[Find Many] Get users with groups + orderBy': 1,
    '[Find Many] Get users with groups + orderBy + limit': 1,
    '[Find Many] Get users with groups + where': 1,
    '[Find Many] Get users with posts': 1,
    '[Find Many] Get users with posts + custom fields': 1,
    '[Find Many] Get users with posts + custom fields + limits': 1,
    '[Find Many] Get users with posts + limit posts': 1,
    '[Find Many] Get users with posts + limit posts and users': 1,
    '[Find Many] Get users with posts + orderBy': 1,
    '[Find Many] Get users with posts + prepared + limit + offset + where': 1,
    '[Find Many] Get users with posts + prepared limit': 1,
    '[Find Many] Get users with posts + prepared limit + offset': 1,
    '[Find Many] Get users with posts + prepared where': 1,
    '[Find Many] Get users with posts + where': 1,
    '[Find Many] Get users with posts + where + partial': 1,
    '[Find Many] Get users with posts + where + partial. Did not select posts id, but used it in where': 1,
    '[Find Many] Get users with posts + where + partial(false)': 1,
    '[Find Many] Get users with posts + where + partial(true + false)': 1,
    '[Find Many] Get users with posts in rollbacked transaction': 1,
    '[Find Many] Get users with posts in transaction': 1,
    '[Find One] Get deep select {}': 1,
    '[Find One] Get groups with users': 1,
    '[Find One] Get groups with users + limit': 1,
    '[Find One] Get groups with users + limit + where': 1,
    '[Find One] Get groups with users + orderBy': 1,
    '[Find One] Get groups with users + where': 1,
    '[Find One] Get only custom fields': 1,
    '[Find One] Get only custom fields + where': 1,
    '[Find One] Get only custom fields + where + limit': 1,
    '[Find One] Get only custom fields + where + orderBy': 1,
    '[Find One] Get select {}': 1,
    '[Find One] Get users with groups': 1,
    '[Find One] Get users with groups + limit': 1,
    '[Find One] Get users with groups + limit + where': 1,
    '[Find One] Get users with groups + orderBy': 1,
    '[Find One] Get users with groups + orderBy + limit': 1,
    '[Find One] Get users with groups + where': 1,
    '[Find One] Get users with posts': 1,
    '[Find One] Get users with posts + custom fields': 1,
    '[Find One] Get users with posts + custom fields + limits': 1,
    '[Find One] Get users with posts + limit posts': 1,
    '[Find One] Get users with posts + limit posts and users': 1,
    '[Find One] Get users with posts + orderBy': 1,
    '[Find One] Get users with posts + where': 1,
    '[Find One] Get users with posts + where + partial': 1,
    '[Find One] Get users with posts + where + partial. Did not select posts id, but used it in where': 1,
    '[Find One] Get users with posts + where + partial(false)': 1,
    '[Find One] Get users with posts + where + partial(true + false)': 1,
    '[Find One] Get users with posts no results found': 1,
    '$count embedded': 2,
    '$count embedded reuse': 2,
    '$count embedded with filters': 2,
    '$count separate': 2,
    '$count separate reuse': 2,
    '$count separate with filters': 2,
    '$default function': 2,
    'aggregate function: avg': 2,
    'aggregate function: count': 2,
    'aggregate function: max': 2,
    'aggregate function: min': 2,
    'aggregate function: sum': 2,
    'all date and time columns': 1,
    'all date and time columns with timezone second case mode date': 1,
    'all date and time columns with timezone third case mode date': 1,
    'all types': 2,
    'array mapping and parsing': 1,
    'array operators': 1,
    'array types': 1,
    'async api - CRUD': 1,
    'async api - insert + select w/ prepare + async execute': 1,
    'async api - insert + select w/ prepare + sync execute': 1,
    'build query': 2,
    'build query insert with onConflict do nothing': 1,
    'build query insert with onConflict do nothing + target': 1,
    'build query insert with onConflict do update': 1,
    'build query insert with onConflict do update / multiple columns': 1,
    'char delete': 1,
    'char insert': 1,
    'char update': 1,
    'cross join': 2,
    'cross join (lateral)': 1,
    'define constraints as array': 1,
    'define constraints as array inside third param': 1,
    'delete as cte': 1,
    'delete returning sql': 2,
    'delete with limit and order by': 1,
    'delete with returning all fields': 2,
    'delete with returning partial': 2,
    'Enable RLS function': 1,
    'Filter by columns not present in select': 1,
    'full join with alias': 2,
    'Get groups with users + custom': 1,
    'Get groups with users + orderBy + limit': 1,
    'Get user + limit with invitee': 1,
    'Get user with invitee': 1,
    'Get user with invitee + order by': 1,
    'Get user with invitee + where': 1,
    'Get user with invitee + where + partial': 1,
    'Get user with invitee + where + partial. Did not select users id, but used it in where': 1,
    'Get user with invitee + where + partial(false)': 1,
    'Get user with invitee + where + partial(true+false)': 1,
    'Get user with invitee and custom fields': 1,
    'Get user with invitee and custom fields + limits': 1,
    'Get user with invitee and posts': 1,
    'Get user with invitee and posts + custom fields in each': 1,
    'Get user with invitee and posts + limit posts and users': 1,
    'Get user with invitee and posts + limit posts and users + where': 1,
    'Get user with invitee and posts + limits + custom fields in each': 1,
    'Get user with invitee and posts + orderBy': 1,
    'Get user with invitee and posts + orderBy + where + custom': 1,
    'Get user with invitee and posts + orderBy + where + partial + custom': 1,
    'Get user with invitee and posts + where': 1,
    'Get user with posts and posts with comments': 1,
    'Get user with posts and posts with comments and comments with owner': 1,
    'Get user with posts and posts with comments and comments with owner where exists': 1,
    'Get users with groups + custom': 1,
    having: 2,
    'inner join (lateral)': 1,
    'insert + select': 2,
    'Insert all defaults in 1 row': 2,
    'Insert all defaults in multiple rows': 2,
    'insert as cte': 1,
    'insert bigint values': 1,
    'insert into - select': 2,
    'insert into - select with keys in different order': 2,
    'insert many': 2,
    'insert many with returning': 2,
    'insert multiple rows into table with generated identity column': 1,
    'insert null timestamp': 1,
    'insert returning sql': 2,
    'insert sql': 1,
    'insert undefined': 2,
    'insert via db.get': 1,
    'insert via db.get w/ query builder': 1,
    'insert via db.run + select via db.all': 1,
    'insert via db.run + select via db.get': 1,
    'insert with auto increment': 1,
    'insert with default values': 1,
    'insert with onConflict chained (.nothing -> .nothing)': 1,
    'insert with onConflict chained (.nothing -> .update)': 1,
    'insert with onConflict chained (.update -> .nothing)': 1,
    'insert with onConflict chained (.update -> .update)': 1,
    'insert with onConflict do nothing': 2,
    'insert with onConflict do nothing + target': 1,
    'insert with onConflict do nothing using composite pk': 1,
    'insert with onConflict do nothing using composite pk as target': 1,
    'insert with onConflict do nothing using target': 1,
    'insert with onConflict do update': 2,
    'insert with onConflict do update using composite pk': 1,
    'insert with onConflict do update where': 1,
    'insert with overridden default values': 2,
    'insert with spaces': 2,
    'insert: placeholders on columns with encoder': 2,
    'join on aliased sql from select': 2,
    'join on aliased sql from with clause': 2,
    'join subquery': 2,
    'join subquery with join': 2,
    'join view as subquery': 2,
    'json insert': 2,
    'left join (all fields)': 1,
    'left join (flat object fields)': 1,
    'left join (grouped fields)': 1,
    'left join (lateral)': 1,
    'limit -1': 2,
    'limit 0': 2,
    'materialized view': 1,
    'mySchema - build query': 1,
    'mySchema - build query insert with onConflict do nothing + target': 1,
    'mySchema - build query insert with onConflict do update / multiple columns': 1,
    'mySchema - delete returning sql': 1,
    'mySchema - delete with returning all fields': 1,
    'mySchema - insert + select': 1,
    'mySchema - insert many': 1,
    'mySchema - insert returning sql': 1,
    'mySchema - insert with overridden default values': 1,
    'mySchema - insert with spaces': 1,
    'mySchema - materialized view': 1,
    'mySchema - partial join with alias': 1,
    'mySchema - prepared statement with placeholder in .limit': 1,
    'mySchema - select all fields': 1,
    'mySchema - select distinct': 1,
    'mySchema - select from tables with same name from different schema using alias': 1,
    'mySchema - select sql': 1,
    'mySchema - select typed sql': 1,
    'mySchema - select with group by as column + sql': 1,
    'mySchema - select with group by as field': 1,
    'mySchema - update with returning partial': 1,
    'mySchema - view': 1,
    'nested transaction': 2,
    'nested transaction rollback': 2,
    'network types': 1,
    'Object keys as column names': 2,
    'orderBy with aliased column': 2,
    'partial join with alias': 2,
    policy: 1,
    'prefixed table': 2,
    'prepared statement': 2,
    'prepared statement built using $dynamic': 2,
    'prepared statement reuse': 2,
    'prepared statement with placeholder in .limit': 2,
    'prepared statement with placeholder in .offset': 2,
    'prepared statement with placeholder in .where': 2,
    'proper json and jsonb handling': 1,
    'Query check: Insert all defaults in 1 row': 1,
    'Query check: Insert all defaults in multiple rows': 1,
    'query check: insert multiple empty rows': 1,
    'query check: insert single empty row': 1,
    'select + .get() for empty result': 1,
    'select a field without joining its table': 2,
    'select all fields': 2,
    'select all fields from subquery without alias': 2,
    'select count w/ custom mapper': 1,
    'select count()': 2,
    'select distinct': 2,
    'select for': 1,
    'select from a many subquery': 2,
    'select from a one subquery': 2,
    'select from alias': 2,
    'select from enum': 1,
    'select from enum as ts enum': 1,
    'select from existing view': 1,
    'select from raw sql': 2,
    'select from raw sql with joins': 2,
    'select from sql': 1,
    'select from subquery sql': 2,
    'select partial': 1,
    'select sql': 2,
    'select typed sql': 2,
    'select with empty array in inArray': 2,
    'select with empty array in notInArray': 2,
    'select with exists': 2,
    'select with group by as column + sql': 2,
    'select with group by as field': 2,
    'select with group by as sql': 2,
    'select with group by as sql + column': 2,
    'select with group by complex query': 2,
    'set json/jsonb fields with objects and retrieve with the -> operator': 1,
    'set json/jsonb fields with objects and retrieve with the ->> operator': 1,
    'set json/jsonb fields with strings and retrieve with the -> operator': 1,
    'set json/jsonb fields with strings and retrieve with the ->> operator': 1,
    'set null to jsonb field': 1,
    'set operations (except all) as function': 1,
    'set operations (except all) from query builder': 1,
    'set operations (except) as function': 2,
    'set operations (except) from query builder': 2,
    'set operations (intersect all) as function': 1,
    'set operations (intersect all) from query builder': 1,
    'set operations (intersect) as function': 2,
    'set operations (intersect) from query builder': 2,
    'set operations (mixed all) as function': 1,
    'set operations (mixed all) as function with subquery': 1,
    'set operations (mixed) from query builder': 1,
    'set operations (mixed) from query builder with subquery': 1,
    'set operations (union all) as function': 2,
    'set operations (union all) from query builder': 2,
    'set operations (union) as function': 2,
    'set operations (union) from query builder with subquery': 2,
    'sql operator as cte': 2,
    'sql.identifier escape': 2,
    'subquery with view': 1,
    'table config: foreign keys name': 2,
    'table config: primary keys name': 2,
    'table configs: unique in column': 2,
    'table configs: unique third param': 2,
    'table selection with single table': 1,
    'test $onUpdateFn and $onUpdate works as $default': 2,
    'test $onUpdateFn and $onUpdate works updating': 2,
    'test $onUpdateFn and $onUpdate works with sql value': 2,
    'test if method with sql operators': 1,
    'timestamp timezone': 1,
    'toSQL()': 1,
    transaction: 2,
    'transaction rollback': 2,
    'update - from': 2,
    'update - from with alias': 2,
    'update - from with join': 2,
    'update as cte': 1,
    'update returning sql': 2,
    'update undefined': 2,
    'update with limit and order by': 1,
    'update with returning all fields': 2,
    'update with returning partial': 2,
    view: 2,
    'with - delete': 2,
    'with - insert': 2,
    'with - select': 2,
    'with - update': 2,
  },
  'mikro-orm': {
    accessors: 6,
    'attach-database': 20,
    'auto-flush': 10,
    'auto-refreshing': 7,
    'balanced-strategy': 2,
    'batch-insert': 2,
    'cache-adapters': 5,
    cancellation: 30,
    'check-constraint': 1,
    cli: 112,
    clone: 26,
    collection: 24,
    'compiled-functions': 9,
    'composite-keys': 91,
    'concurrency-checks': 8,
    'count-by': 11,
    createForeignKeyConstraint: 4,
    'cursor-based-pagination': 74,
    'custom-entity-manager': 1,
    'custom-order': 32,
    'custom-types': 98,
    dataloader: 42,
    decorators: 62,
    'default-values': 9,
    'deferrable-constraints': 4,
    'define-entity-setclass': 7,
    'disable-transactions': 7,
    'duplicate-class-names': 1,
    embeddables: 199,
    'entity-assigner': 43,
    'entity-default-order': 32,
    'entity-generator': 113,
    'entity-manager': 578,
    'event-manager': 6,
    events: 4,
    filters: 77,
    'find-one-or-fail-strict': 1,
    formulas: 3,
    fulltext: 8,
    'generated-columns': 12,
    'get-kysely': 20,
    'get-kysely-transaction-context': 3,
    hydration: 1,
    inheritance: 4,
    'joined-strategy': 15,
    'kysely-convert-values-where-clause': 9,
    'lazy-ref': 24,
    'lazy-scalar-properties': 15,
    'load-count-where': 1,
    'loadable-mixin': 13,
    logging: 25,
    migrations: 151,
    'mikro-kysely-plugin': 102,
    'multiple-schemas': 35,
    'multiple-schemas-entity-manager': 9,
    naming: 1,
    'native-enums': 13,
    'native-query-builder': 33,
    'non-pk-relation-target': 35,
    'on-reserve-connection': 3,
    'optimistic-lock': 21,
    'paginate-flag': 6,
    'partial-loading': 33,
    'pivot-table-upsert': 9,
    'polymorphic-relations': 221,
    'populate-hints': 6,
    'populate-limit': 13,
    'query-builder': 351,
    'raw-queries': 47,
    'read-replicas': 11,
    reflection: 18,
    refresh: 4,
    'result-cache': 12,
    'reusing-kysely-client': 1,
    'schema-generator': 404,
    seeder: 16,
    serialization: 41,
    'sharing-column-in-composite-fk': 8,
    'single-table-inheritance': 44,
    'special-object-keys': 3,
    'stored-routines': 152,
    streaming: 14,
    'table-per-type-inheritance': 115,
    'terminated-connection': 2,
    transactions: 131,
    trigger: 16,
    truncate: 4,
    'unit-of-work': 33,
    upsert: 97,
    'using-index-hints': 62,
    validation: 2,
    'view-entities': 68,
    'virtual-entities': 9,
    wilcardSchemaIndex: 4,
  },
  nestjs: {
    'auto-mock/test/bar.service': 4,
    'cors/e2e/': 12,
    'discovery/e2e/discover-by-meta': 3,
    'graceful-shutdown/e2e/': 2,
    'graphql-code-first/e2e/code-first': 1,
    'graphql-code-first/e2e/guards-filters': 1,
    'graphql-code-first/e2e/pipes': 1,
    'graphql-schema-first/e2e/graphql': 1,
    'graphql-schema-first/e2e/graphql-async': 1,
    'graphql-schema-first/e2e/graphql-async-class': 1,
    'graphql-schema-first/e2e/graphql-async-existing': 1,
    'graphql-schema-first/e2e/graphql-request-scoped': 1,
    'hello-world/e2e/adapter': 7,
    'hello-world/e2e/exceptions': 6,
    'hello-world/e2e/exclude-middleware': 20,
    'hello-world/e2e/force-console': 6,
    'hello-world/e2e/guards': 2,
    'hello-world/e2e/hello-world': 4,
    'hello-world/e2e/instance': 5,
    'hello-world/e2e/interceptors': 6,
    'hello-world/e2e/local-pipes': 3,
    'hello-world/e2e/middleware': 40,
    'hello-world/e2e/middleware-before-init': 3,
    'hello-world/e2e/middleware-class': 5,
    'hello-world/e2e/middleware-execute-order': 2,
    'hello-world/e2e/middleware-with-versioning': 6,
    'hello-world/e2e/multiple': 7,
    'hello-world/e2e/router-module': 3,
    'hello-world/e2e/router-module-middleware': 3,
    'hello-world/e2e/schema-in-pipes': 5,
    'hello-world/e2e/standard-schema-serializer': 11,
    'hooks/e2e/before-app-shutdown': 3,
    'hooks/e2e/enable-shutdown-hook': 5,
    'hooks/e2e/lifecycle-hook-order': 1,
    'hooks/e2e/on-app-bootstrap': 5,
    'hooks/e2e/on-app-shutdown': 3,
    'hooks/e2e/on-module-destroy': 5,
    'hooks/e2e/on-module-init': 5,
    'injector/e2e/circular': 1,
    'injector/e2e/circular-custom-providers': 2,
    'injector/e2e/circular-modules': 1,
    'injector/e2e/circular-property-injection': 1,
    'injector/e2e/circular-structure-dynamic-modules': 1,
    'injector/e2e/core-injectables': 3,
    'injector/e2e/default-values': 1,
    'injector/e2e/for-root-for-feature-resolution': 3,
    'injector/e2e/inherited-optional': 1,
    'injector/e2e/injector': 10,
    'injector/e2e/introspection': 3,
    'injector/e2e/many-global-modules': 1,
    'injector/e2e/multiple-providers': 3,
    'injector/e2e/optional-factory-provider-dep': 5,
    'injector/e2e/parallel-request-scoped-resolution': 5,
    'injector/e2e/property-injection': 2,
    'injector/e2e/request-scope-bubbling': 1,
    'injector/e2e/request-scoped-factory-provider': 1,
    'injector/e2e/scoped-instances': 9,
    'inspector/e2e/graph-inspector': 2,
    'lazy-modules/e2e/lazy-import-global-modules': 1,
    'lazy-modules/e2e/lazy-import-request-providers': 1,
    'lazy-modules/e2e/lazy-import-transient-providers': 1,
    'microservices/e2e/disconnected-client': 5,
    'microservices/e2e/sum-rpc': 11,
    'microservices/e2e/sum-rpc-async': 1,
    'microservices/e2e/sum-rpc-tls': 11,
    'microservices/e2e/tcp-json-socket-pipeline': 1,
    'module-utils/test/integration-module': 2,
    'nest-application/app-locals/e2e/': 2,
    'nest-application/get-url/e2e/': 9,
    'nest-application/global-prefix/e2e/global-prefix': 8,
    'nest-application/listen/e2e/': 6,
    'nest-application/raw-body/e2e/': 8,
    'nest-application/sse/e2e/': 26,
    'nest-application/use-body-parser/e2e/': 8,
    'query-method/e2e/query-method': 6,
    'repl/e2e/repl': 10,
    'repl/e2e/repl-process': 1,
    'route-conflict/e2e/conflict-policy': 12,
    'route-conflict/e2e/resolution-strategy': 12,
    'route-conflict/e2e/versioned-wildcard': 7,
    'route-conflict/e2e/wildcard-conflict-policy': 5,
    'route-conflict/e2e/wildcard-resolution-strategy': 8,
    'scopes/e2e/circular-request-scope': 4,
    'scopes/e2e/circular-transient-scope': 4,
    'scopes/e2e/durable-cross-module-forward-ref': 1,
    'scopes/e2e/durable-forward-ref': 1,
    'scopes/e2e/durable-providers': 7,
    'scopes/e2e/inject-inquirer': 2,
    'scopes/e2e/msvc-request-scope': 5,
    'scopes/e2e/request-modules-scope': 3,
    'scopes/e2e/request-scope': 9,
    'scopes/e2e/resolve-scoped': 2,
    'scopes/e2e/transient-scope': 17,
    'send-files/e2e/': 13,
    'testing-module-override/e2e/modules-override': 6,
    'typeorm/e2e/typeorm': 1,
    'typeorm/e2e/typeorm-async': 1,
    'typeorm/e2e/typeorm-async-class': 1,
    'typeorm/e2e/typeorm-async-existing': 1,
    'typeorm/e2e/typeorm-async-options': 1,
    'versioning/e2e/custom-versioning': 164,
    'versioning/e2e/default-versioning': 6,
    'versioning/e2e/header-versioning': 136,
    'versioning/e2e/media-type-versioning': 136,
    'versioning/e2e/uri-versioning': 113,
    'websockets/e2e/error-gateway': 1,
    'websockets/e2e/gateway': 7,
    'websockets/e2e/gateway-ack': 4,
    'websockets/e2e/request-scope-gateway': 1,
    'websockets/e2e/ws-error-gateway': 1,
    'websockets/e2e/ws-gateway': 8,
  },
  typia: {
    assert: 60,
    assertEquals: 25,
    assertGuard: 3,
    assertGuardEquals: 4,
    CamelCase: 2,
    'compare.createEquals': 5,
    'compare.equals': 2,
    createAssert: 5,
    createClone: 1,
    createIs: 76,
    createRandom: 62,
    createValidate: 3,
    createValidateEquals: 2,
    equals: 10,
    'http.assertFormData': 2,
    'http.assertHeaders': 2,
    'http.assertQuery': 5,
    'http.createAssertQuery': 3,
    'http.createFormData': 9,
    'http.createHeaders': 25,
    'http.createIsQuery': 3,
    'http.createParameter': 3,
    'http.createQuery': 10,
    'http.createValidateQuery': 3,
    'http.formData': 1,
    'http.headers': 1,
    'http.isFormData': 2,
    'http.isHeaders': 2,
    'http.isQuery': 6,
    'http.query': 4,
    'http.validateFormData': 4,
    'http.validateHeaders': 4,
    'http.validateQuery': 7,
    is: 214,
    IValidation: 30,
    'IValidation.ISuccess': 4,
    'json.application': 151,
    'json.assertEncode': 1,
    'json.assertParse': 3,
    'json.assertStringify': 14,
    'json.createAssertParse': 139,
    'json.createStringify': 140,
    'json.isEncode': 2,
    'json.isParse': 3,
    'json.isStringify': 16,
    'json.schema': 110,
    'json.schemas': 42,
    'json.stringify': 33,
    'json.validateEncode': 2,
    'json.validateParse': 5,
    'json.validateStringify': 17,
    KebabCase: 2,
    literals: 1,
    'llm.application': 52,
    'llm.coerce': 2,
    'llm.controller': 63,
    'llm.createCoerce': 1,
    'llm.createParse': 1,
    'llm.parameters': 75,
    'llm.parse': 3,
    'llm.schema': 111,
    'llm.structuredOutput': 14,
    'notations.assertX': 2,
    'notations.camel': 5,
    'notations.isX': 1,
    'notations.kebab': 5,
    'notations.pascal': 5,
    'notations.snake': 5,
    'notations.validateX': 3,
    PascalCase: 2,
    'plain.assertClone': 3,
    'plain.assertPrune': 2,
    'plain.classify': 5,
    'plain.clone': 10,
    'plain.createAssertClone': 1,
    'plain.createClassify': 4,
    'plain.createClone': 24,
    'plain.createIsClone': 3,
    'plain.isClone': 4,
    'plain.isPrune': 5,
    'plain.prune': 1,
    'plain.validateClone': 5,
    'plain.validatePrune': 5,
    'protobuf.assertDecode': 7,
    'protobuf.assertEncode': 3,
    'protobuf.createAssertDecode': 6,
    'protobuf.createDecode': 119,
    'protobuf.createEncode': 112,
    'protobuf.createIsDecode': 6,
    'protobuf.createValidateDecode': 7,
    'protobuf.decode': 53,
    'protobuf.encode': 12,
    'protobuf.isDecode': 8,
    'protobuf.isEncode': 1,
    'protobuf.message': 123,
    'protobuf.validateDecode': 9,
    'protobuf.validateEncode': 1,
    random: 179,
    'reflect.literals': 18,
    'reflect.name': 17,
    'reflect.schema': 20,
    'reflect.schemas': 4,
    Resolved: 70,
    SnakeCase: 2,
    'tags.ExclusiveMaximum': 6,
    'tags.ExclusiveMinimum': 6,
    'tags.Format': 6,
    'tags.Maximum': 19,
    'tags.MaxItems': 10,
    'tags.MaxLength': 10,
    'tags.Minimum': 23,
    'tags.MinItems': 11,
    'tags.MinLength': 12,
    'tags.MultipleOf': 3,
    'tags.Pattern': 5,
    'tags.TagBase': 3,
    'tags.Type': 122,
    validate: 69,
    validateEquals: 8,
  },
};

export const TOTAL_UPSTREAM_SUITES = 742;
export const TOTAL_UPSTREAM_ASSERTIONS = 9258;
