/*zmdb:imports*/
// Generated by zmdb-codegen from src/microservices/grpc/__fixtures__/orders.ts. Checked, not edited.
//
// One wrapper per validation call src/microservices/grpc/__fixtures__/orders.ts used to make, written against the runtime
// API so that the compiler still sees each type argument. That is the point of the file: it
// is what `zmdb-codegen` reads on the next run to regenerate the compiled module, and it is
// what turns a renamed or deleted type into a build error here instead of a validator that
// silently checks a shape nobody declares.
//
// Editing it by hand does nothing. An entry disappears when the source stops referring to
// its export name, so deleting a call in the source is how you delete a validator; there's
// no bookkeeping to keep in step.

import type { Orders } from './orders.js';
import type { GrpcLoadedService } from '@zmdb/protobuf';
import { loadGrpcService } from '@zmdb/protobuf';
/*zmdb:/imports*/

/*zmdb:begin:zmdbLoadGrpcServiceOrdersOrdersOrders*/
export function zmdbLoadGrpcServiceOrdersOrdersOrders(): GrpcLoadedService<Orders> {
  return loadGrpcService<Orders>('Orders', 'orders');
}
/*zmdb:end:zmdbLoadGrpcServiceOrdersOrdersOrders*/
