// Generated by zmdb-codegen from src/microservices/grpc/__fixtures__/orders.ts. Do not edit.
//
// The validators, compiled. Every check below was emitted from a type in src/microservices/grpc/__fixtures__/orders.ts's
// witness module by `@zmdb/aot-validator`, so there is no schema to walk at runtime and
// nothing to look up: the shape is the control flow.
//
// This half is the types: the signatures the compiler reads when the source imports the
// module next door. Nothing here is checked against the implementation, and nothing needs
// to be — the witness makes the same claims against the runtime API, and *that* is checked.
import type { Orders } from './orders.js';
import type { GrpcLoadedService } from '@zmdb/protobuf';

export declare function zmdbLoadGrpcServiceOrdersOrdersOrders(): GrpcLoadedService<Orders>;
