import { describe, expect, it } from 'vitest';

import type { Dialect } from '../index.js';
import type { ColumnSnapshot, SchemaSnapshot, TableSnapshot } from '../migrations/index.js';

type FrozenIndexColumn = string | { readonly expr: string; readonly opclass?: string };

interface FrozenIndexSnapshot {
  readonly name: string;
  readonly columns: readonly FrozenIndexColumn[];
  readonly unique: boolean;
}

type FrozenColumnSnapshot = ColumnSnapshot & {
  readonly catalogType?: string;
  readonly default?: string;
};

type FrozenTableSnapshot = Omit<TableSnapshot, 'columns'> & {
  readonly columns: readonly FrozenColumnSnapshot[];
  readonly primaryKey: readonly string[];
  readonly foreignKeys: readonly unknown[];
  readonly indexes: readonly FrozenIndexSnapshot[];
};

type FrozenSchemaSnapshot = Omit<SchemaSnapshot, 'tables'> & {
  readonly tables: readonly FrozenTableSnapshot[];
  readonly extensions: readonly { readonly name: string; readonly schema?: string }[];
};

interface FrozenEmitOptions {
  readonly dialect: Dialect;
}

interface FrozenEmitDeclarationsResult {
  readonly files: readonly { readonly path: string; readonly source: string }[];
  readonly warnings: readonly {
    readonly table: string;
    readonly column?: string;
    readonly reason: string;
  }[];
}

type FrozenEmitDeclarations = (
  snapshot: FrozenSchemaSnapshot,
  options: FrozenEmitOptions,
) => FrozenEmitDeclarationsResult | Promise<FrozenEmitDeclarationsResult>;

async function emitDeclarations(
  snapshot: FrozenSchemaSnapshot,
  options: FrozenEmitOptions,
): Promise<FrozenEmitDeclarationsResult> {
  const module: unknown = await import('../index.js');
  const value: unknown = Reflect.get(Object(module), 'emitDeclarations');
  if (typeof value !== 'function') {
    throw new Error('@zmdb/query-compiler exports no "emitDeclarations" (frozen: introspect/SPEC.md 6)');
  }
  return (value as FrozenEmitDeclarations)(snapshot, options);
}

function snapshotOf(table: FrozenTableSnapshot): FrozenSchemaSnapshot {
  return { version: 1, tables: [table], extensions: [] };
}

function tableOf(name: string, columns: readonly FrozenColumnSnapshot[]): FrozenTableSnapshot {
  return { name, columns, primaryKey: [], foreignKeys: [], indexes: [] };
}

describe('declaration emission (frozen: introspect/SPEC.md 6-7)', () => {
  // actual today: @zmdb/query-compiler exports no "emitDeclarations".
  it.fails('emits deterministic, formatted declaration source', async () => {
    const input = snapshotOf(
      tableOf('accounts', [
        {
          name: 'created_at',
          type: 'timestamp',
          catalogType: 'TEXT',
          nullable: false,
          primaryKey: false,
          default: 'CURRENT_TIMESTAMP',
        },
        { name: 'email', type: 'text', catalogType: 'TEXT', nullable: false, primaryKey: false },
        { name: 'id', type: 'serial', catalogType: 'INTEGER', nullable: false, primaryKey: true },
      ]),
    );

    const first = await emitDeclarations(input, { dialect: 'sqlite' });
    const second = await emitDeclarations(input, { dialect: 'sqlite' });
    expect(first).toEqual(second);
    expect(first.files.map(file => file.path)).toEqual(['accounts.ts', 'index.ts']);

    const account = first.files.find(file => file.path === 'accounts.ts');
    if (!account) throw new Error('emitter produced no accounts.ts');
    expect(account.source).toContain(
      '// Generated by zmdb introspection from a sqlite database. Do not edit; regenerate instead.',
    );
    expect(account.source).toContain('// Snapshot version 1. Hand edits are overwritten wholesale.');
    expect(account.source).toContain("export interface Account extends Table<'accounts'>");
    expect(account.source).toContain("id: number & Sql<'integer'> & Serial & PrimaryKey;");
    expect(account.source).toContain("created_at: Date & Sql<'timestamp'> & HasDefault;");
    expect(account.source).not.toMatch(/[ \t]+$/m);
    expect(account.source.endsWith('\n')).toBe(true);
  });

  // `bytea` has no app type that round-trips its bytes. It remains exact in the
  // snapshot, but the declaration omits the property and names the omission twice:
  // structurally and beside the generated interface. `unknown` is never the fallback.
  it.fails('warns and comments rather than widening an unrepresentable type', async () => {
    const input = snapshotOf(
      tableOf('documents', [
        { name: 'id', type: 'serial', catalogType: 'int4', nullable: false, primaryKey: true },
        { name: 'payload', type: 'bytea', catalogType: 'bytea', nullable: false, primaryKey: false },
      ]),
    );
    const result = await emitDeclarations(input, { dialect: 'postgres' });
    const document = result.files.find(file => file.path === 'documents.ts');
    if (!document) throw new Error('emitter produced no documents.ts');

    expect(result.warnings).toEqual([
      {
        table: 'documents',
        column: 'payload',
        reason: expect.stringMatching(/bytea.*cannot be represented without data loss/i),
      },
    ]);
    expect(document.source).toMatch(/TODO:.*payload.*bytea/i);
    expect(document.source).not.toMatch(/^\s*payload\s*:/m);
    expect(document.source).not.toContain('unknown');
  });
});
