import { createRequire } from 'node:module';

import { afterAll, describe, expect, it } from 'vitest';

import type { CompiledQuery, Dialect } from '../index.js';
import type { ColumnSnapshot, SchemaSnapshot, TableSnapshot } from '../migrations/index.js';

// This suite never turns an unavailable server into an expected failure. It probes at
// collection time: a reachable benchmark Postgres registers real expected-failing
// behavior tests; an unreachable server registers only the exact, loud skip assertion.

type FrozenColumnSnapshot = ColumnSnapshot & {
  readonly catalogType?: string;
  readonly default?: string;
};

type FrozenTableSnapshot = Omit<TableSnapshot, 'columns'> & {
  readonly columns: readonly FrozenColumnSnapshot[];
  readonly primaryKey: readonly string[];
  readonly foreignKeys: readonly unknown[];
  readonly indexes: readonly unknown[];
};

type FrozenSchemaSnapshot = Omit<SchemaSnapshot, 'tables'> & {
  readonly tables: readonly FrozenTableSnapshot[];
  readonly extensions: readonly { readonly name: string; readonly schema?: string }[];
};

interface FrozenDriver {
  execute(query: CompiledQuery): Promise<readonly Record<string, unknown>[]>;
}

interface FrozenIntrospector {
  readonly dialect: Dialect;
  snapshot(driver: FrozenDriver, options?: { readonly schemas?: readonly string[] }): Promise<FrozenSchemaSnapshot>;
}

type FrozenCreateIntrospector = (dialect: Dialect) => FrozenIntrospector;

interface PgPool {
  query(text: string, values?: readonly unknown[]): Promise<{ readonly rows: readonly Record<string, unknown>[] }>;
  end(): Promise<void>;
}

type PgPoolConstructor = new (options: {
  readonly connectionString: string;
  readonly connectionTimeoutMillis: number;
  readonly max: number;
}) => PgPool;

interface ReachablePostgres {
  readonly kind: 'reachable';
  readonly pool: PgPool;
  readonly schema: string;
  readonly version: string;
}

interface UnreachablePostgres {
  readonly kind: 'unreachable';
  readonly message: string;
}

type PostgresProbe = ReachablePostgres | UnreachablePostgres;

const CONNECTION =
  process.env.ZMDB_INTROSPECT_POSTGRES_URL ??
  process.env.ZMDB_PG ??
  'postgres://postgres:postgres@localhost:55432/bench';

function poolConstructor(): PgPoolConstructor | undefined {
  try {
    const requireFromRepository = createRequire(new URL('../../../repository/package.json', import.meta.url));
    const module: unknown = requireFromRepository('pg');
    const value: unknown = Reflect.get(Object(module), 'Pool');
    return typeof value === 'function' ? (value as PgPoolConstructor) : undefined;
  } catch {
    return undefined;
  }
}

async function probePostgres(): Promise<PostgresProbe> {
  const Pool = poolConstructor();
  if (!Pool) {
    return {
      kind: 'unreachable',
      message: '[skip] Postgres introspection: repository test dependency "pg" is unavailable',
    };
  }

  const pool = new Pool({ connectionString: CONNECTION, connectionTimeoutMillis: 250, max: 1 });
  const schema = `zmdb_introspect_430_${String(process.pid)}`;
  try {
    const version = await pool.query('SELECT version() AS version');
    const rawVersion = version.rows[0]?.['version'];
    if (typeof rawVersion !== 'string') throw new Error('SELECT version() returned no string');
    await pool.query(`CREATE SCHEMA "${schema}"`);
    await pool.query(
      `CREATE TABLE "${schema}".accounts (
        id BIGSERIAL PRIMARY KEY,
        identity_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
        email TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`,
    );
    return { kind: 'reachable', pool, schema, version: rawVersion };
  } catch {
    await pool.end();
    return {
      kind: 'unreachable',
      message: `[skip] Postgres introspection: no server reachable at ${CONNECTION}`,
    };
  }
}

async function introspectorFor(dialect: Dialect): Promise<FrozenIntrospector> {
  const module: unknown = await import('../index.js');
  const value: unknown = Reflect.get(Object(module), 'createIntrospector');
  if (typeof value !== 'function') {
    throw new Error('@zmdb/query-compiler exports no "createIntrospector" (frozen: introspect/SPEC.md 1)');
  }
  return (value as FrozenCreateIntrospector)(dialect);
}

function pgDriver(pool: PgPool): FrozenDriver {
  return {
    async execute(query) {
      const result = await pool.query(query.text, query.parameters);
      return result.rows.map(row => ({ ...row }));
    },
  };
}

function column(snapshot: FrozenSchemaSnapshot, tableName: string, columnName: string): FrozenColumnSnapshot {
  const table = snapshot.tables.find(candidate => candidate.name === tableName);
  const found = table?.columns.find(candidate => candidate.name === columnName);
  if (!found) throw new Error(`snapshot has no column "${tableName}.${columnName}"`);
  return found;
}

const postgres = await probePostgres();

if (postgres.kind === 'unreachable') {
  process.stderr.write(`${postgres.message}\n`);
}

afterAll(async () => {
  if (postgres.kind !== 'reachable') return;
  try {
    await postgres.pool.query(`DROP SCHEMA "${postgres.schema}" CASCADE`);
  } finally {
    await postgres.pool.end();
  }
});

it('skips the Postgres suite with an explicit message when no server is reachable', () => {
  if (postgres.kind === 'unreachable') {
    console.warn(postgres.message);
    expect(postgres.message).toMatch(/^\[skip\] Postgres introspection:/);
    return;
  }
  expect(postgres.version).toMatch(/^PostgreSQL /);
});

function reachablePostgres(): ReachablePostgres {
  if (postgres.kind === 'unreachable') {
    throw new Error(`the Postgres suite ran despite its gate: ${postgres.message}`);
  }
  return postgres;
}

describe.skipIf(postgres.kind === 'unreachable')('introspection against reachable real Postgres', () => {
  // actual today on a reachable server: the createIntrospector export is absent.
  it.fails('reads tables and columns from a reachable real Postgres server', async () => {
    const live = reachablePostgres();
    const actual = await (
      await introspectorFor('postgres')
    ).snapshot(pgDriver(live.pool), {
      schemas: [live.schema],
    });
    expect(actual.tables.map(table => table.name)).toEqual(['accounts']);
    expect(column(actual, 'accounts', 'email')).toMatchObject({
      type: 'text',
      catalogType: 'text',
      nullable: false,
      primaryKey: false,
    });
    expect(column(actual, 'accounts', 'created_at').default).toBe('now()');
  });

  it.fails('recognises serial and identity columns from a real Postgres database', async () => {
    const live = reachablePostgres();
    const actual = await (
      await introspectorFor('postgres')
    ).snapshot(pgDriver(live.pool), {
      schemas: [live.schema],
    });
    expect(column(actual, 'accounts', 'id').type).toBe('serial');
    expect(column(actual, 'accounts', 'identity_id').type).toBe('serial');
  });
});
