// Canonical, read-only membership and product-surface metadata for every
// published zmdb package. Array order is alphabetical by stable id for
// deterministic presentation only; it is not publish order.

const PUBLISH_VERIFIER_REASON =
  'yarn verify:publish packs, installs, imports, and typechecks every public export from outside the repository.';

const freezeArray = values => Object.freeze([...values]);

function productPackage({ id, directory, npmName, role, facade, optionality, docsOwner, consumer }) {
  return Object.freeze({
    id,
    directory,
    npmName,
    role,
    facade: Object.freeze({
      root: freezeArray(facade.root),
      subpaths: freezeArray(facade.subpaths),
    }),
    optionality: Object.freeze({ ...optionality }),
    docsOwner,
    consumer: Object.freeze({ ...consumer }),
  });
}

export const PRODUCT_CATALOG = Object.freeze([
  productPackage({
    id: 'ai',
    directory: 'packages/ai',
    npmName: '@zmdb/ai',
    role: 'ai',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'provider-neutral AI tools' },
    docsOwner: 'llm-function-calling',
    consumer: { reason: PUBLISH_VERIFIER_REASON },
  }),
  productPackage({
    id: 'ai-anthropic',
    directory: 'packages/ai-anthropic',
    npmName: '@zmdb/ai-anthropic',
    role: 'anthropic',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'Anthropic Messages API' },
    docsOwner: 'llm-chat',
    consumer: { reason: PUBLISH_VERIFIER_REASON },
  }),
  productPackage({
    id: 'ai-langchain',
    directory: 'packages/ai-langchain',
    npmName: '@zmdb/ai-langchain',
    role: 'langchain',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'LangChain' },
    docsOwner: 'llm-langchain',
    consumer: { fixture: 'fixtures/llm-adapters' },
  }),
  productPackage({
    id: 'ai-vercel',
    directory: 'packages/ai-vercel',
    npmName: '@zmdb/ai-vercel',
    role: 'vercel-ai',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'Vercel AI SDK' },
    docsOwner: 'llm-vercel-ai-sdk',
    consumer: { fixture: 'fixtures/llm-adapters' },
  }),
  productPackage({
    id: 'angular',
    directory: 'packages/angular',
    npmName: '@zmdb/angular',
    role: 'angular',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'Angular generated-client bindings' },
    docsOwner: 'framework-integrations',
    consumer: { fixture: 'fixtures/client-adapters' },
  }),
  productPackage({
    id: 'aot-validator',
    directory: 'packages/aot-validator',
    npmName: '@zmdb/aot-validator',
    role: 'validator',
    facade: {
      root: [
        'AssertError',
        'ValidateResult',
        'assert',
        'assertEquals',
        'assertShallow',
        'equals',
        'is',
        'isShallow',
        'random',
        'tags',
        'validate',
        'validateShallow',
      ],
      subpaths: ['zmdb/unplugin'],
    },
    optionality: { kind: 'required' },
    docsOwner: 'aot-setup',
    consumer: { fixture: 'fixtures/consumer-metro' },
  }),
  productPackage({
    id: 'app',
    directory: 'packages/app',
    npmName: '@zmdb/app',
    role: 'app',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'required' },
    docsOwner: 'web-app',
    consumer: { reason: PUBLISH_VERIFIER_REASON },
  }),
  productPackage({
    id: 'client',
    directory: 'packages/client',
    npmName: '@zmdb/client',
    role: 'client',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'generated HTTP clients' },
    docsOwner: 'web-http-client',
    consumer: { fixture: 'fixtures/consumer-http-client' },
  }),
  productPackage({
    id: 'jobs',
    directory: 'packages/jobs',
    npmName: '@zmdb/jobs',
    role: 'jobs',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'required' },
    docsOwner: 'web-queues',
    consumer: { fixture: 'fixtures/consumer-server-core' },
  }),
  productPackage({
    id: 'jobs-postgres',
    directory: 'packages/jobs-postgres',
    npmName: '@zmdb/jobs-postgres',
    role: 'jobs-postgres',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'PostgreSQL job storage' },
    docsOwner: 'web-queues',
    consumer: { fixture: 'fixtures/consumer-server-integrations' },
  }),
  productPackage({
    id: 'mcp',
    directory: 'packages/mcp',
    npmName: '@zmdb/mcp',
    role: 'mcp',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'Model Context Protocol' },
    docsOwner: 'llm-mcp',
    consumer: { fixture: 'fixtures/consumer-mcp' },
  }),
  productPackage({
    id: 'otel',
    directory: 'packages/otel',
    npmName: '@zmdb/otel',
    role: 'otel',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'OpenTelemetry' },
    docsOwner: 'web-observability',
    consumer: { fixture: 'fixtures/consumer-server-integrations' },
  }),
  productPackage({
    id: 'protobuf',
    directory: 'packages/protobuf',
    npmName: '@zmdb/protobuf',
    role: 'protobuf',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'Protocol Buffers' },
    docsOwner: 'protobuf-message',
    consumer: { reason: PUBLISH_VERIFIER_REASON },
  }),
  productPackage({
    id: 'query-compiler',
    directory: 'packages/query-compiler',
    npmName: '@zmdb/query-compiler',
    role: 'sql',
    facade: {
      root: [
        'ColumnExpr',
        'CommentKey',
        'CommentKeys',
        'CommentPairs',
        'CompiledQuery',
        'DIALECT_PARAM_LIMITS',
        'Dialect',
        'SetValue',
        'UnsupportedFeatureError',
        'appendComment',
        'chunkArray',
        'coalesce',
        'concat',
        'createQueryCompiler',
        'dec',
        'inc',
        'migrations',
        'mul',
        'not',
        'proposed',
        'sanitizeKeys',
        'serializeComment',
        'withComments',
      ],
      subpaths: [],
    },
    optionality: { kind: 'required' },
    docsOwner: 'raw-sql',
    consumer: { reason: PUBLISH_VERIFIER_REASON },
  }),
  productPackage({
    id: 'react',
    directory: 'packages/react',
    npmName: '@zmdb/react',
    role: 'react',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'React' },
    docsOwner: 'framework-integrations',
    consumer: { fixture: 'fixtures/client-adapters' },
  }),
  productPackage({
    id: 'repository',
    directory: 'packages/repository',
    npmName: '@zmdb/repository',
    role: 'orm',
    facade: {
      root: [
        'ActiveTransactionContext',
        'BaseRepository',
        'ClosedTransactionContext',
        'Driver',
        'IncompleteKeyError',
        'NumericColumnOf',
        'TransactionContext',
        'TransactionState',
        'TransactionalDb',
        'TxConnection',
        'UpdatePatch',
        'UpsertOptions',
        'ValidationError',
        'batch',
        'createTransactionalDb',
        'defineRepository',
        'markTransactionClosed',
      ],
      subpaths: ['zmdb/drivers/mssql', 'zmdb/drivers/pg'],
    },
    optionality: { kind: 'required' },
    docsOwner: 'repository',
    consumer: { reason: PUBLISH_VERIFIER_REASON },
  }),
  productPackage({
    id: 'schema-core',
    directory: 'packages/schema-core',
    npmName: '@zmdb/schema-core',
    role: 'schema',
    facade: {
      root: [
        'AllowedTargetStates',
        'ColumnMeta',
        'CoreSchema',
        'CreateDTO',
        'Entity',
        'EntityStateMachine',
        'EntityStateMachineOptions',
        'JsonSchemaObject',
        'PrimaryKeyOf',
        'StateTransitions',
        'StateUpdateDTO',
        'TaggedSchema',
        'UpdateDTO',
        'ValidationIssue',
        'createStateUpdatePayload',
        'defineEntityStateMachine',
        'defineStateTransitions',
        'schemaOf',
        'toJsonSchema',
      ],
      subpaths: ['zmdb/derive', 'zmdb/dto', 'zmdb/ir', 'zmdb/relations', 'zmdb/tags'],
    },
    optionality: { kind: 'required' },
    docsOwner: 'schema-declaration',
    consumer: { reason: PUBLISH_VERIFIER_REASON },
  }),
  productPackage({
    id: 'sqlite',
    directory: 'packages/sqlite',
    npmName: '@zmdb/sqlite',
    role: 'sqlite',
    facade: { root: [], subpaths: ['zmdb/drivers/sqlite'] },
    optionality: { kind: 'integration', technology: 'SQLite' },
    docsOwner: 'dialect-sqlite',
    consumer: { fixture: 'fixtures/database-sqlite' },
  }),
  productPackage({
    id: 'transport-grpc',
    directory: 'packages/transport-grpc',
    npmName: '@zmdb/transport-grpc',
    role: 'grpc',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'gRPC' },
    docsOwner: 'web-microservices-grpc',
    consumer: { fixture: 'fixtures/consumer-server-integrations' },
  }),
  productPackage({
    id: 'transport-nats',
    directory: 'packages/transport-nats',
    npmName: '@zmdb/transport-nats',
    role: 'transport-nats',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'core NATS messaging' },
    docsOwner: 'web-microservices-transports',
    consumer: { fixture: 'fixtures/consumer-server-integrations' },
  }),
  productPackage({
    id: 'transport-rabbitmq',
    directory: 'packages/transport-rabbitmq',
    npmName: '@zmdb/transport-rabbitmq',
    role: 'rabbitmq',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'RabbitMQ' },
    docsOwner: 'web-microservices-transports',
    consumer: { fixture: 'fixtures/consumer-server-integrations' },
  }),
  productPackage({
    id: 'transport-redis',
    directory: 'packages/transport-redis',
    npmName: '@zmdb/transport-redis',
    role: 'transport-redis',
    facade: { root: [], subpaths: [] },
    optionality: { kind: 'integration', technology: 'Redis Pub/Sub' },
    docsOwner: 'web-microservices-transports',
    consumer: { fixture: 'fixtures/consumer-server-integrations' },
  }),
  productPackage({
    id: 'web',
    directory: 'packages/web',
    npmName: '@zmdb/web',
    role: 'web',
    facade: {
      root: [],
      subpaths: ['zmdb/web', 'zmdb/web/contract', 'zmdb/web/contract/compiler'],
    },
    optionality: { kind: 'required' },
    docsOwner: 'web-overview',
    consumer: { reason: PUBLISH_VERIFIER_REASON },
  }),
  productPackage({
    id: 'zmdb',
    directory: 'packages/zmdb',
    npmName: 'zmdb',
    role: 'product',
    facade: { root: [], subpaths: ['zmdb/cli', 'zmdb/config'] },
    optionality: { kind: 'required' },
    docsOwner: 'package-reference',
    consumer: { fixture: 'fixtures/consumer-product' },
  }),
]);
