import { dirname, join, resolve } from 'node:path';

import { readMigrations, writeTextAtomically } from '../file-io.js';
import { MigrationProjectError, requiredSourceFormatter, type MigrationProject } from '../project.js';

export const EMBEDDED_WITH_DOWN_MARKER = '// Includes down sections for development tooling.';

export interface EmbedOptions {
  readonly out?: string;
  readonly withDown?: boolean;
}

export interface EmbeddedModuleResult {
  readonly file: string;
  readonly source: string;
  readonly migrations: readonly {
    readonly version: number;
    readonly name: string;
    readonly checksum: string;
  }[];
}

export interface EmbedResult {
  readonly file: string;
  readonly migrations: EmbeddedModuleResult['migrations'];
}

export function embeddedOutputPath(project: MigrationProject, requested?: string): string {
  return requested === undefined
    ? join(project.outDir, 'embedded.ts')
    : resolve(dirname(project.configPath), requested);
}

export async function renderEmbeddedModule(
  project: MigrationProject,
  options: EmbedOptions = {},
): Promise<EmbeddedModuleResult> {
  const file = embeddedOutputPath(project, options.out);
  const migrations = await Promise.all(
    (await readMigrations(project.outDir)).map(async migration => ({
      version: migration.version,
      name: migration.name,
      up: migration.up,
      ...(options.withDown === true ? { down: migration.down } : {}),
      checksum: await checksum(migration.up),
    })),
  );
  const arrayType =
    options.withDown === true
      ? 'readonly (EmbeddedMigration & { readonly down: string })[]'
      : 'readonly EmbeddedMigration[]';
  const marker = options.withDown === true ? `${EMBEDDED_WITH_DOWN_MARKER}\n` : '';
  const raw =
    '// Generated by `zmdb embed`. Do not edit.\n' +
    marker +
    "import type { EmbeddedMigration } from '@zmdb/migrations/embedded';\n\n" +
    `export const migrations: ${arrayType} = ${JSON.stringify(migrations, null, 2)} as const;\n`;
  return {
    file,
    source: await requiredSourceFormatter(project)(file, raw),
    migrations: migrations.map(migration => ({
      version: migration.version,
      name: migration.name,
      checksum: migration.checksum,
    })),
  };
}

export async function embedMigrations(project: MigrationProject, options: EmbedOptions = {}): Promise<EmbedResult> {
  if (project.dialect !== 'sqlite') {
    throw new MigrationProjectError(
      `embedded migrations execute SQLite, but ${project.configPath} configures ${project.dialect}`,
    );
  }
  const rendered = await renderEmbeddedModule(project, options);
  await writeTextAtomically(rendered.file, rendered.source);
  return { file: rendered.file, migrations: rendered.migrations };
}

async function checksum(source: string): Promise<string> {
  const bytes = new TextEncoder().encode(source);
  const digest = new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256', bytes));
  const hex = Array.from(digest, byte => byte.toString(16).padStart(2, '0')).join('');
  return `sha256:${hex}`;
}
