import { readFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';

import { writeTextAtomically } from '../file-io.js';
import type { CatalogWarning } from '../introspect/index.js';
import { requiredDeclarationEmitter, requiredDriver, requiredIntrospector, type MigrationProject } from '../project.js';

export interface PullOptions {
  /** Print the complete generated files and write nothing. */
  readonly dryRun?: boolean;
  /** Compare generated bytes with the staging tree and write nothing. */
  readonly check?: boolean;
}

export interface PullFile {
  readonly path: string;
  readonly tables: readonly string[];
}

export interface PullSkippedFile {
  readonly path: string;
  readonly reason: string;
}

export interface PullResult {
  readonly files: readonly PullFile[];
  readonly skipped: readonly PullSkippedFile[];
}

export interface PullOutputFile extends PullFile {
  readonly source: string;
  readonly barrel: boolean;
}

export interface PullExecution {
  readonly result: PullResult;
  readonly warnings: readonly CatalogWarning[];
  readonly outputs: readonly PullOutputFile[];
  readonly exitCode: 0 | 1;
  readonly mode: 'write' | 'dry-run' | 'check';
}

interface EmittedDeclarationFile {
  readonly path: string;
  readonly source: string;
}

const GENERATED_HEADER =
  /^\/\/ Generated by zmdb introspection from a [^\r\n]+ database\. Do not edit; regenerate instead\.\r?\n\/\/ Snapshot version \d+\. Hand edits are overwritten wholesale\.\r?\n/;

/**
 * Read a live catalogue and reconcile the deterministic staging declarations.
 *
 * The staging tree is deliberately separate from application-owned schema
 * files. A file is replaceable only when the emitter's two-line header proves
 * that zmdb created it; `--check` and `--dry-run` never write.
 */
export async function pullDeclarations(project: MigrationProject, options: PullOptions = {}): Promise<PullExecution> {
  const driver = requiredDriver(project);
  const snapshot = await requiredIntrospector(project).snapshot(driver, project.introspect);
  const emitted = await requiredDeclarationEmitter(project)(snapshot, { dialect: project.dialect });
  const projectRoot = dirname(project.configPath);
  const outputRoot = join(projectRoot, '.zmdb', 'introspected');
  const outputs = declarationOutputs(
    emitted.files,
    snapshot.tables.map(table => table.name),
    outputRoot,
    projectRoot,
  );
  const skipped: PullSkippedFile[] = [];
  const available: PullFile[] = [];
  const mode = options.check === true ? 'check' : options.dryRun === true ? 'dry-run' : 'write';

  for (const output of outputs) {
    const destination = join(projectRoot, output.path);
    const current = await readText(destination);

    if (current !== undefined && !GENERATED_HEADER.test(current)) {
      skipped.push({
        path: output.path,
        reason: 'existing file has no zmdb introspection header; left it untouched',
      });
      continue;
    }

    if (mode === 'check') {
      if (current === undefined) {
        skipped.push({ path: output.path, reason: 'generated declaration is missing' });
        continue;
      }
      if (current !== output.source) {
        skipped.push({ path: output.path, reason: 'generated declaration differs from the live database' });
        continue;
      }
    } else if (mode === 'write') {
      await writeTextAtomically(destination, output.source);
    }

    if (!output.barrel) available.push({ path: output.path, tables: output.tables });
  }

  return {
    result: { files: available, skipped },
    warnings: emitted.warnings,
    outputs,
    exitCode: skipped.length === 0 ? 0 : 1,
    mode,
  };
}

function declarationOutputs(
  files: readonly EmittedDeclarationFile[],
  tableNames: readonly string[],
  outputRoot: string,
  projectRoot: string,
): readonly PullOutputFile[] {
  const sortedTables = tableNames.toSorted();
  let tableIndex = 0;
  const outputs = files.map(file => {
    const barrel = file.path === 'index.ts';
    const tables = barrel ? sortedTables : [requiredTable(sortedTables, tableIndex, file.path)];
    if (!barrel) tableIndex += 1;
    return {
      path: relative(projectRoot, join(outputRoot, file.path)),
      tables,
      source: file.source,
      barrel,
    };
  });

  if (tableIndex !== sortedTables.length) {
    throw new TypeError(
      `declaration emitter returned ${String(tableIndex)} table files for ${String(sortedTables.length)} tables`,
    );
  }
  return outputs;
}

function requiredTable(tables: readonly string[], index: number, path: string): string {
  const table = tables[index];
  if (table === undefined) {
    throw new TypeError(`declaration emitter returned unexpected table file "${path}"`);
  }
  return table;
}

async function readText(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if (errorCode(error) === 'ENOENT') return undefined;
    throw error;
  }
}

function errorCode(error: unknown): string | undefined {
  if (typeof error !== 'object' || error === null) return undefined;
  const code = Reflect.get(error, 'code');
  return typeof code === 'string' ? code : undefined;
}
