// @generated by zmdb http-client; contract-format=1; generator=1.0.0
import { createClientRuntime } from '@zmdb/client';
import { toOpenApi } from '@zmdb/web/openapi';

const TypeIR = toOpenApi;

export const client = createClientRuntime({ baseUrl: '/api' });
export const workspace = '/home/example/zmdb/packages/web';
export { TypeIR };
