// @generated by zmdb http-client; contract-format=1; generator=1.0.0
import { createClientRuntime } from '@zmdb/client';

const token = 'committed-bearer-token';

export const client = createClientRuntime({
  baseUrl: 'https://api.example.test',
  headers: { authorization: `Bearer ${token}` },
});
