// @generated by zmdb http-client; contract-format=1; generator=1.0.0
import { createClientRuntime } from '@zmdb/client';
import type { CallOptions, ClientOptions } from '@zmdb/client';

const operation = Object.freeze({
  abi: 1,
  operationId: 'patch_accounts_accountId',
  security: [{ bearerAuth: [] }, { apiKeyAuth: [] }],
  schemes: {
    bearerAuth: { type: 'http', scheme: 'bearer' },
    apiKeyAuth: { type: 'apiKey', in: 'header', name: 'x-api-key' },
  },
});

export function createApiClient(options: ClientOptions) {
  const runtime = createClientRuntime(options);
  return {
    patch_accounts_accountId(input: unknown, callOptions?: CallOptions) {
      return runtime.call(operation, input, callOptions);
    },
  };
}
