// REQ-TF-4: the REQ-SC-2…REQ-SC-5 type tests, re-run against a tagged interface.
//
// This was `../type-derivation.type-test.ts` — the same assertions, same order, same names —
// with `User` bound to a `defineSchema` value. `defineSchema` is gone (plan D2) and so is the
// derivation that read its column map (plan phase 9): there is one family of derivations now,
// it takes the declared type, and this file is what checks it answers what the old one did.
//
// For a while this file also held the other half of the argument — the same two tables written
// out as column maps, and forty assertions that the two derivation families were mutually
// assignable at every property. That was the evidence for collapsing them, and it is spent:
// there is nothing left to substitute against, because `Entity` *is* the tagged derivation.
// `../schema-core.type-test.ts`, which held the value-side suite, went with it.
//
// The PRD said "pass unchanged", and one thing had to change. It is worth being precise about
// what, because it is a real design decision and not a technicality:
//
//   REQ-SC-2 asserted `Equal<Entity<User>['email'], string>`. Here that is
//   `string & Sql<'text'>`, because REQ-TF-5 requires the tags to survive every derivation —
//   `Omit`, `Pick` and `Partial` must not drop one, or the emitted validator would check less
//   on update than on insert. The two requirements are in direct tension and REQ-TF-5 wins:
//   the tags are what the validator is generated from.
//
//   That is not a weakening, because the tags erase for every purpose except `Equal`. A tag is
//   an optional unique-symbol slot, so `string` and `string & Sql<'text'>` are *mutually
//   assignable*: a consumer hands in a plain string and reads out a plain string, and the
//   phantom slot is invisible to them. `_Erase*` below is where that is asserted.
//
// So the assertions come in two layers, deliberately: `Equal` against the exact tagged type
// (which is the only thing that catches a wrong or missing tag), and the structural claims from
// REQ-SC-2…5 verbatim (key sets, what is absent, what is optional).
//
// The interfaces below were generated by running `scripts/codemod-tagged-schema.mjs` over the
// original file, which made this a second check on the codemod — and it earned that immediately.
// The codemod's first output for `role` was `'admin' | 'user' & HasDefault`, which TypeScript
// reads as `'admin' | ('user' & HasDefault)`, and `_Ent3` is what caught it.
//
// No runtime code: a compilation gate, run by `yarn typecheck` and therefore by CI.

import type { Equal, Expect, Mutual } from '../index.ts';
import type { HasDefault, PrimaryKey, Serial, Sql, Table } from '../tags/index.ts';
import type { CreateDTO, Entity, PrimaryKeyOf, UpdateDTO } from './index.ts';

interface User extends Table<'users'> {
  id: number & Sql<'integer'> & Serial & PrimaryKey;
  email: string & Sql<'text'>;
  role: ('admin' | 'user') & HasDefault;
  age: number & Sql<'integer'>;
  score: (number & Sql<'numeric'>) | null;
  createdAt: Date & Sql<'timestamp'> & HasDefault;
}

interface Composite extends Table<'org_members'> {
  tenantId: string & Sql<'text'> & PrimaryKey;
  userId: number & Sql<'integer'> & PrimaryKey;
  role: string & Sql<'text'>;
}

// --- Entity ----------------------------------------------------------------
export type _Ent1 = Expect<Equal<Entity<User>['id'], number & Sql<'integer'> & Serial & PrimaryKey>>;
export type _Ent2 = Expect<Equal<Entity<User>['email'], string & Sql<'text'>>>;
// The one that caught the codemod's operator-precedence bug: if the emitted type had been
// `'admin' | ('user' & HasDefault)` this would be that, and nothing else would have noticed.
export type _Ent3 = Expect<Equal<Entity<User>['role'], ('admin' | 'user') & HasDefault>>;
export type _Ent4 = Expect<Equal<Entity<User>['age'], number & Sql<'integer'>>>;
export type _Ent5 = Expect<Equal<Entity<User>['createdAt'], Date & Sql<'timestamp'> & HasDefault>>;
// `| null` widens the column, and only that column.
export type _Ent6 = Expect<Equal<Entity<User>['score'], (number & Sql<'numeric'>) | null>>;
// Verbatim from REQ-SC-2: the entity-level `Table<'users'>` tag must not leak into `keyof`.
export type _Ent7 = Expect<Equal<keyof Entity<User>, 'id' | 'email' | 'role' | 'age' | 'score' | 'createdAt'>>;

// --- CreateDTO -------------------------------------------------------------
// Verbatim from REQ-SC-3. `Serial` ⇒ absent entirely, not optional.
export type _Cre1 = Expect<Equal<keyof CreateDTO<User>, 'email' | 'age' | 'score' | 'role' | 'createdAt'>>;
// `HasDefault` ⇒ optional. Indexing an optional property adds `| undefined` either way, so
// this assertion reads the same on both sides.
export type _Cre2 = Expect<Equal<CreateDTO<User>['role'], (('admin' | 'user') & HasDefault) | undefined>>;
export type _Cre3 = Expect<Equal<CreateDTO<User>['createdAt'], (Date & Sql<'timestamp'> & HasDefault) | undefined>>;
// No default, not serial ⇒ required.
export type _Cre4 = Expect<Equal<CreateDTO<User>['email'], string & Sql<'text'>>>;
// The `@ts-expect-error` half of REQ-SC-3's criterion, which is about the key set and so
// transfers unchanged.
// @ts-expect-error a database-generated column cannot be supplied on insert
export const _Cre5: CreateDTO<User> = { id: 1, email: 'a@b.co', age: 30, score: null };
// Nullable and no default ⇒ optional, for the reason `CreateDTO` gives: omitting the key
// inserts `NULL`, which is what passing `null` does. Both spellings are accepted — `_Cre5`
// above and `_Erase6` below pass `score: null` explicitly — and the published `create`
// document has never listed a nullable column as required, so this is the assertion that
// keeps the contract and the type saying the same thing.
export type _Cre6 = Expect<Equal<CreateDTO<User>['score'], (number & Sql<'numeric'>) | null | undefined>>;
export const _Cre7: CreateDTO<User> = { email: 'a@b.co', age: 30 };

// --- UpdateDTO -------------------------------------------------------------
export type _Upd1 = Expect<Equal<UpdateDTO<User>['email'], (string & Sql<'text'>) | undefined>>;
export type _Upd2 = Expect<Equal<UpdateDTO<User>['role'], (('admin' | 'user') & HasDefault) | undefined>>;
// The value-side test wrote `{ email: undefined, role: 'admin' }` here and this file cannot.
// This is the one behavioural difference between the two derivations — everything else is a
// difference in spelling — and it applies to `CreateDTO` equally.
//
// `UpdateDTO` is a `Partial<…>`, and under `exactOptionalPropertyTypes` — on repo-wide, in
// `tsconfig.json` — `Partial` produces `email?: string`, which accepts the key being
// absent but not the key being present and `undefined`. The value-side `UpdateDTO` widened to
// `| undefined` and so accepted both.
//
// Keeping the strict version is deliberate. `{ email: undefined }` and `{}` mean the same
// thing to an update, and `{ email: null }` is how "set it to NULL" is spelled, so the widened
// version bought a third spelling of one of two meanings. It is a breaking change for anyone
// building an update object by assigning `undefined`, and it is listed as one.
export const _Upd3: UpdateDTO<User> = { role: 'admin' };
export const _Upd4: UpdateDTO<User> = {};
export const _Upd5: UpdateDTO<User> = { score: null };

// --- PrimaryKeyOf ------------------------------------------------------------
export type _Pk1 = Expect<Equal<PrimaryKeyOf<User>, number & Sql<'integer'> & Serial & PrimaryKey>>;
export type _Pk2 = Expect<
  Equal<
    PrimaryKeyOf<Composite>,
    { tenantId: string & Sql<'text'> & PrimaryKey; userId: number & Sql<'integer'> & PrimaryKey }
  >
>;
// And the structural half, verbatim: one key gives a scalar, two give a map with those keys.
export type _Pk3 = Expect<Equal<keyof PrimaryKeyOf<Composite>, 'tenantId' | 'userId'>>;

// --- The tags erase ---------------------------------------------------------
// Why the `Equal` assertions above are not a weakening. A tag is an optional unique-symbol
// slot, so a tagged column type and its bare counterpart are mutually assignable: a consumer
// passes a plain value in and gets a plain value out, and never names a tag.
export type _Erase1 = Expect<Equal<Mutual<Entity<User>['email'], string>, true>>;
export type _Erase2 = Expect<Equal<Mutual<Entity<User>['age'], number>, true>>;
export type _Erase3 = Expect<Equal<Mutual<Entity<User>['score'], number | null>, true>>;
export type _Erase4 = Expect<Equal<Mutual<Entity<User>['role'], 'admin' | 'user'>, true>>;
export type _Erase5 = Expect<Equal<Mutual<PrimaryKeyOf<User>, number>, true>>;
// Plain data goes in, with no tag anywhere in sight. This is the shape a consumer writes.
export const _Erase6: CreateDTO<User> = { email: 'a@b.co', age: 30, score: null };
declare const row: Entity<User>;
export const _Erase7: { id: number; email: string; role: 'admin' | 'user' } = row;
