// REQ-TF-4's acceptance criterion: the REQ-SC-2…REQ-SC-5 type tests, re-run with a tagged
// interface substituted for `typeof Schema`.
//
// This is `../type-derivation.type-test.ts` — the same assertions, same order, same names —
// with `S` bound to a tagged interface instead of a `defineSchema` value. It is copied rather
// than shared through a generic helper on purpose: a helper would let the two drift while
// still looking identical, and "the same test" is the claim.
//
// The PRD said "pass unchanged", and one thing had to change. It is worth being precise about
// what, because it is a real design decision and not a technicality:
//
//   REQ-SC-2 asserted `Equal<Entity<S>['email'], string>`. On the tagged side that is
//   `string & Sql<'text'>`, because REQ-TF-5 requires the tags to survive every derivation —
//   `Omit`, `Pick` and `Partial` must not drop one, or the emitted validator would check less
//   on update than on insert. The two requirements are in direct tension and REQ-TF-5 wins:
//   the tags are what the validator is generated from.
//
//   That is not a weakening, because the tags erase for every purpose except `Equal`. A tag is
//   an optional unique-symbol slot, so `string` and `string & Sql<'text'>` are *mutually
//   assignable*: a consumer hands in a plain string and reads out a plain string, and the
//   phantom slot is invisible to them. `_Erase*` below asserts that, and `_Substitute*`
//   asserts the consequence — the tagged derivations and the schema-value derivations are
//   interchangeable at every property.
//
// So the assertions come in three layers, deliberately: `Equal` against the exact tagged type
// (which is the only thing that catches a wrong or missing tag), the structural claims from
// REQ-SC-2…5 verbatim (key sets, what is absent, what is optional), and mutual assignability
// against the value-side derivation (which is what "substituted" means for a consumer).
//
// The interfaces below were generated by
// `node scripts/codemod-tagged-schema.mjs packages/schema-core/src/type-derivation.type-test.ts`
// and pasted in, which makes this file a second check on the codemod — and it earned that
// immediately. The codemod's first output for `role` was `'admin' | 'user' & HasDefault`,
// which TypeScript reads as `'admin' | ('user' & HasDefault)`, and `_Ent3` is what caught it.
//
// No runtime code: a compilation gate, run by `yarn typecheck` and therefore by CI.

// The schema-value derivations, aliased. Same names, different types — which is exactly what
// the last section is about, and what plan phase 9 collapses.
import type {
  CreateDTO as ValueCreateDTO,
  Entity as ValueEntity,
  Equal,
  Expect,
  PrimaryKeyOf as ValuePrimaryKeyOf,
  UpdateDTO as ValueUpdateDTO,
} from '../index.ts';
import { defineSchema, integer, jsonEnum, numeric, primaryKey, serial, text, timestamp } from '../index.ts';
import type { HasDefault, PrimaryKey, Serial, Sql, Table } from '../tags/index.ts';
import type { CreateDTO, Entity, PrimaryKeyOf, UpdateDTO } from './index.ts';

/** Assignable both ways: interchangeable in an argument and in a return value. */
type Mutual<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

interface User extends Table<'users'> {
  id: number & Sql<'serial'> & Serial & PrimaryKey;
  email: string & Sql<'text'>;
  role: ('admin' | 'user') & HasDefault;
  age: number & Sql<'integer'>;
  score: (number & Sql<'numeric'>) | null;
  createdAt: Date & Sql<'timestamp'> & HasDefault;
}
type S = User;

interface Composite extends Table<'org_members'> {
  tenantId: string & Sql<'text'> & PrimaryKey;
  userId: number & Sql<'integer'> & PrimaryKey;
  role: string & Sql<'text'>;
}
type CompositeS = Composite;

// The `defineSchema` originals, copied verbatim from `../type-derivation.type-test.ts`. They
// appear only as the right-hand side of the substitution assertions at the bottom.
const UserSchema = defineSchema('users', {
  id: serial().primaryKey(),
  email: text().notNull(),
  role: jsonEnum(['admin', 'user']).defaultTo('user'),
  age: integer(),
  score: numeric().nullable(),
  createdAt: timestamp().defaultTo('now'),
});

const CompositeSchema = defineSchema('org_members', {
  tenantId: primaryKey(text()),
  userId: primaryKey(integer()),
  role: text().notNull(),
});

// --- Entity ----------------------------------------------------------------
export type _Ent1 = Expect<Equal<Entity<S>['id'], number & Sql<'serial'> & Serial & PrimaryKey>>;
export type _Ent2 = Expect<Equal<Entity<S>['email'], string & Sql<'text'>>>;
// The one that caught the codemod's operator-precedence bug: if the emitted type had been
// `'admin' | ('user' & HasDefault)` this would be that, and nothing else would have noticed.
export type _Ent3 = Expect<Equal<Entity<S>['role'], ('admin' | 'user') & HasDefault>>;
export type _Ent4 = Expect<Equal<Entity<S>['age'], number & Sql<'integer'>>>;
export type _Ent5 = Expect<Equal<Entity<S>['createdAt'], Date & Sql<'timestamp'> & HasDefault>>;
// `| null` widens the column, and only that column.
export type _Ent6 = Expect<Equal<Entity<S>['score'], (number & Sql<'numeric'>) | null>>;
// Verbatim from REQ-SC-2: the entity-level `Table<'users'>` tag must not leak into `keyof`.
export type _Ent7 = Expect<Equal<keyof Entity<S>, 'id' | 'email' | 'role' | 'age' | 'score' | 'createdAt'>>;

// --- CreateDTO -------------------------------------------------------------
// Verbatim from REQ-SC-3. `Serial` ⇒ absent entirely, not optional.
export type _Cre1 = Expect<Equal<keyof CreateDTO<S>, 'email' | 'age' | 'score' | 'role' | 'createdAt'>>;
// `HasDefault` ⇒ optional. Indexing an optional property adds `| undefined` either way, so
// this assertion reads the same on both sides.
export type _Cre2 = Expect<Equal<CreateDTO<S>['role'], (('admin' | 'user') & HasDefault) | undefined>>;
export type _Cre3 = Expect<Equal<CreateDTO<S>['createdAt'], (Date & Sql<'timestamp'> & HasDefault) | undefined>>;
// No default, not serial ⇒ required.
export type _Cre4 = Expect<Equal<CreateDTO<S>['email'], string & Sql<'text'>>>;
// The `@ts-expect-error` half of REQ-SC-3's criterion, which is about the key set and so
// transfers unchanged.
// @ts-expect-error a database-generated column cannot be supplied on insert
export const _Cre5: CreateDTO<S> = { id: 1, email: 'a@b.co', age: 30, score: null };

// --- UpdateDTO -------------------------------------------------------------
export type _Upd1 = Expect<Equal<UpdateDTO<S>['email'], (string & Sql<'text'>) | undefined>>;
export type _Upd2 = Expect<Equal<UpdateDTO<S>['role'], (('admin' | 'user') & HasDefault) | undefined>>;
// The value-side test wrote `{ email: undefined, role: 'admin' }` here and this file cannot.
// This is the one behavioural difference between the two derivations — everything else is a
// difference in spelling — and it applies to `CreateDTO` equally.
//
// `UpdateDTO` is a `Partial<…>`, and under `exactOptionalPropertyTypes` — on repo-wide, in
// `tsconfig.base.json` — `Partial` produces `email?: string`, which accepts the key being
// absent but not the key being present and `undefined`. The value-side `UpdateDTO` widened to
// `| undefined` and so accepted both.
//
// Keeping the strict version is deliberate. `{ email: undefined }` and `{}` mean the same
// thing to an update, and `{ email: null }` is how "set it to NULL" is spelled, so the widened
// version bought a third spelling of one of two meanings. It is a breaking change for anyone
// building an update object by assigning `undefined`, and it is listed as one.
export const _Upd3: UpdateDTO<S> = { role: 'admin' };
export const _Upd4: UpdateDTO<S> = {};
export const _Upd5: UpdateDTO<S> = { score: null };

// --- PrimaryKeyOf ------------------------------------------------------------
export type _Pk1 = Expect<Equal<PrimaryKeyOf<S>, number & Sql<'serial'> & Serial & PrimaryKey>>;
export type _Pk2 = Expect<
  Equal<
    PrimaryKeyOf<CompositeS>,
    { tenantId: string & Sql<'text'> & PrimaryKey; userId: number & Sql<'integer'> & PrimaryKey }
  >
>;
// And the structural half, verbatim: one key gives a scalar, two give a map with those keys.
export type _Pk3 = Expect<Equal<keyof PrimaryKeyOf<CompositeS>, 'tenantId' | 'userId'>>;

// --- The tags erase ---------------------------------------------------------
// Why the `Equal` assertions above are not a weakening. A tag is an optional unique-symbol
// slot, so a tagged column type and its bare counterpart are mutually assignable: a consumer
// passes a plain value in and gets a plain value out, and never names a tag.
export type _Erase1 = Expect<Equal<Mutual<Entity<S>['email'], string>, true>>;
export type _Erase2 = Expect<Equal<Mutual<Entity<S>['age'], number>, true>>;
export type _Erase3 = Expect<Equal<Mutual<Entity<S>['score'], number | null>, true>>;
export type _Erase4 = Expect<Equal<Mutual<Entity<S>['role'], 'admin' | 'user'>, true>>;
export type _Erase5 = Expect<Equal<Mutual<PrimaryKeyOf<S>, number>, true>>;
// Plain data goes in, with no tag anywhere in sight. This is the shape a consumer writes.
export const _Erase6: CreateDTO<S> = { email: 'a@b.co', age: 30, score: null };
declare const row: Entity<S>;
export const _Erase7: { id: number; email: string; role: 'admin' | 'user' } = row;

// --- The substitution ------------------------------------------------------
// REQ-TF-4 read literally: swapping the tagged interface in for `typeof Schema` leaves every
// derivation interchangeable. Mutual assignability rather than `Equal`, because `Equal` is
// precisely the thing the tags are visible to — and per property as well as whole-type, since
// two objects can be mutually assignable while a property is not.
export type _Substitute1 = Expect<Equal<Mutual<Entity<S>, ValueEntity<typeof UserSchema>>, true>>;
export type _Substitute2 = Expect<Equal<Mutual<PrimaryKeyOf<S>, ValuePrimaryKeyOf<typeof UserSchema>>, true>>;
export type _Substitute3 = Expect<
  Equal<Mutual<PrimaryKeyOf<CompositeS>, ValuePrimaryKeyOf<typeof CompositeSchema>>, true>
>;
// The key sets are identical, which mutual assignability alone would not prove for optional
// properties — `{a?: 1}` and `{}` are mutually assignable.
export type _Substitute4 = Expect<Equal<keyof Entity<S>, keyof ValueEntity<typeof UserSchema>>>;
export type _Substitute5 = Expect<Equal<keyof CreateDTO<S>, keyof ValueCreateDTO<typeof UserSchema>>>;
export type _Substitute6 = Expect<Equal<keyof UpdateDTO<S>, keyof ValueUpdateDTO<typeof UserSchema>>>;

// `CreateDTO` and `UpdateDTO` are interchangeable in one direction only, and it is the same
// `exactOptionalPropertyTypes` divergence described at `_Upd3`: both are built from optional
// properties, the value side widened those to `| undefined`, and the tagged side does not. So
// the strict tagged DTO is accepted anywhere the widened one is, and not the reverse.
//
// That is the safe direction — code that produced a tagged DTO keeps working — and the reverse
// failing is the intended breaking change, not an oversight.
type AssignableTo<A, B> = [A] extends [B] ? true : false;
export type _Substitute7 = Expect<Equal<AssignableTo<CreateDTO<S>, ValueCreateDTO<typeof UserSchema>>, true>>;
export type _Substitute8 = Expect<Equal<AssignableTo<UpdateDTO<S>, ValueUpdateDTO<typeof UserSchema>>, true>>;
// Pinned rather than left implicit: the reverse is a compile error, and it is one on purpose.
export type _Substitute9 = Expect<Equal<AssignableTo<ValueCreateDTO<typeof UserSchema>, CreateDTO<S>>, false>>;
export type _Substitute10 = Expect<Equal<AssignableTo<ValueUpdateDTO<typeof UserSchema>, UpdateDTO<S>>, false>>;
