// The two consumer fixtures, built and compared. See `fixtures/README.md`.
//
// `fixtures/consumer-cli/` and `fixtures/consumer-plugin/` are the same program reaching the
// compiled validator by the two supported routes: a checked-in `zmdb-codegen` output, and a
// bundler with `zmdbAot()` in it. What this file is for is the word *same* — the two are
// separate directories, and separate directories drift.
//
// So four claims, in order of what a regression would cost:
//
//  1. They are the same program. Every file that is not generated is byte-identical, and the
//     committed witness makes exactly the calls the plugin fixture's source still makes.
//  2. The committed output is what the CLI produces — `--check`, which writes nothing.
//  3. They behave identically, compared as the bytes each one prints.
//  4. The compiled checks are the same code (REQ-AV-1), and both are measured.
//
// Both fixtures are built by spawning a process rather than by calling into the library. That
// is the point of a fixture: an integration that only ever runs in-process is an integration
// with the test harness. The cost is a compiler session per build, which is why everything
// heavy happens once in `beforeAll`.

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { transformSync } from 'esbuild';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { opsPerSecond } from '../plugin/inline-bench.js';
import { codegen } from './index.js';

const ROOT = new URL('../../../../', import.meta.url).pathname;
const CLI = join(ROOT, 'fixtures', 'consumer-cli');
const PLUGIN = join(ROOT, 'fixtures', 'consumer-plugin');

const read = (path: string): string => readFileSync(path, 'utf8');

/**
 * `--import` for every `node` spawned below.
 *
 * The fixtures import their siblings as `./orders.js`, which is what `tsc` asks for and what
 * plain `node` cannot resolve to `orders.ts`. `scripts/ts-specifier-hook.mjs` is the repository's
 * answer to that, and a fixture standing in for a consumer has to run the way a consumer would.
 */
const HOOK = `--import=${join(ROOT, 'scripts', 'ts-specifier-hook.mjs')}`;

/** Long enough for two `tsgo` sessions and an esbuild run on a loaded machine. */
const BUILD_TIMEOUT = 180_000;

let bundle: string;
let bundled: {
  accepts(value: unknown): boolean;
  acceptsPoint(value: unknown): boolean;
};

beforeAll(async () => {
  bundle = mkdtempSync(join(tmpdir(), 'zmdb-fixture-'));
  execFileSync('node', [HOOK, join(PLUGIN, 'build.mjs'), bundle], { stdio: 'pipe' });
  bundled = (await import(join(bundle, 'orders.mjs'))) as typeof bundled;
}, BUILD_TIMEOUT);

afterAll(() => {
  rmSync(bundle, { recursive: true, force: true });
});

// -----------------------------------------------------------------------------
// 1. The same program
// -----------------------------------------------------------------------------

describe('the fixtures are the same program', () => {
  for (const name of ['model.ts', 'probe.ts']) {
    it(`${name} is byte-identical in both`, () => {
      // Neither of these contains a validation call, so neither is rewritten, so there is no
      // reason for the two copies to differ and a diff means somebody edited one of them.
      expect(read(join(CLI, 'src', name))).toBe(read(join(PLUGIN, 'src', name)));
    });
  }

  it('the committed witness makes exactly the calls the plugin fixture still makes', () => {
    // The tie that stops the CLI fixture from being a stale snapshot. Its `orders.ts` no longer
    // says `is<Order>` — that is the point of it — so the witness is where the type arguments
    // live now, and the witness has to agree with the source the other fixture kept.
    const source = calls(read(join(PLUGIN, 'src', 'orders.ts')));
    const witness = calls(read(join(CLI, 'src', 'orders.zmdb.witness.ts')));
    expect(witness).toEqual(source);
    expect(source.length).toBeGreaterThan(0);
  });
});

/**
 * The `callee<Type>` pairs in a file, sorted.
 *
 * A regex rather than the scanner, because both inputs are known: the plugin fixture is
 * hand-written and its calls are one per line, and the witness's `return is<Order>(value);`
 * lines were generated by `witnessSource` a few hundred lines from here. Neither contains a
 * nested `>` in a type argument, which is the case a regex could not do.
 */
function calls(text: string): string[] {
  const found = [
    ...text.matchAll(/\b(is|equals|assert|assertEquals|validate|random|toJsonSchema|schemaOf)<([^;]*)>\(/g),
  ];
  return found.map(match => `${match[1] ?? ''}<${(match[2] ?? '').replaceAll(/\s+/g, ' ')}>`).toSorted();
}

// -----------------------------------------------------------------------------
// 2. The committed output is up to date
// -----------------------------------------------------------------------------

describe('the CLI fixture is committed in the state the CLI produces', () => {
  it(
    'passes --check, which is what CI runs',
    () => {
      // The same call the `zmdb-codegen --check` step in CI makes, in-process so that a failure
      // names the file. Nothing is written: a stale witness is caught by comparing text, and
      // the compiled pair is derived from files already on disk.
      const result = codegen({ project: join(CLI, 'tsconfig.json'), check: true });
      expect(result.problems).toEqual([]);
      expect([...result.written, ...result.deleted]).toEqual([]);
      expect(result.ok).toBe(true);
    },
    BUILD_TIMEOUT,
  );
});

// -----------------------------------------------------------------------------
// 3. Identical behaviour
// -----------------------------------------------------------------------------

describe('both routes produce the same program', () => {
  it(
    'prints byte-identical output',
    () => {
      // `probe.ts` was written for this: one line per question, nothing non-deterministic on
      // stdout. So "the two fixtures agree" is `diff`, over the whole observable surface at
      // once rather than a hand-written table of expectations that could omit the case that
      // broke.
      const viaCli = execFileSync('node', [HOOK, join(CLI, 'src', 'probe.ts')], { encoding: 'utf8' });
      const viaPlugin = execFileSync('node', [join(bundle, 'probe.mjs')], { encoding: 'utf8' });
      expect(viaPlugin).toBe(viaCli);
      expect(viaCli).toContain('accepts(good): true');
      expect(viaCli).toContain('accepts(badConstraint): false');
    },
    BUILD_TIMEOUT,
  );

  it('runs under plain `node`, with no build tool present (REQ-AV-3)', () => {
    // The whole reason the CLI exists. `src/probe.ts` is TypeScript that Node type-strips, and
    // the validator it calls was compiled at commit time — there is no bundler, no plugin, no
    // transform and no runtime walker anywhere in that sentence. The `--import` the spawn above
    // carries is a resolve hook and only that: it maps `./orders.js` onto `orders.ts` and
    // compiles nothing.
    const generated = read(join(CLI, 'src', 'orders.zmdb.generated.js'));
    expect(generated).toContain('export function zmdbIsOrder(value) {');
    expect(read(join(CLI, 'src', 'orders.ts'))).not.toMatch(/\bis</);
  });
});

// -----------------------------------------------------------------------------
// 4. The compiled checks, and what they cost
// -----------------------------------------------------------------------------

describe('the emitted checks (REQ-AV-1)', () => {
  it('are the same code on both routes', () => {
    // Not byte-identical text, for two reasons that are both fine. The helper suffixes are
    // allocated per file, so the CLI's `_zmdbCheckOrder0` is the bundle's `_zmdbCheckOrder4`;
    // and esbuild re-prints what it bundles, which among other things drops parentheses that do
    // not change the meaning of an `&&` chain.
    //
    // So the CLI's file goes through esbuild too. Its printer is the normaliser — the same
    // printer, over the same input, is what makes the remaining difference *only* the suffixes,
    // and erasing those leaves the check itself. If the two routes emitted different code, this
    // is where it shows.
    const fromCli = checkBody(reprint(read(join(CLI, 'src', 'orders.zmdb.generated.js'))));
    const fromPlugin = checkBody(read(join(bundle, 'orders.mjs')));
    expect(fromPlugin).toBe(fromCli);
    expect(fromCli).toContain('Number.isInteger(_v.total) && _v.total >= 0');
    expect(fromCli).toContain('_zmdbCheckAddress(_v.shipTo)');
  });

  it('inline an anonymous type with no call into zmdb and no allocation', () => {
    // REQ-AV-1's acceptance criterion, on the case it was written about. `acceptsPoint` takes an
    // inline `{ x: number; y: number }`, which the emitter inlines rather than hoisting (a
    // *name* is the signal that a type may recur), so its happy path is one boolean expression.
    //
    // Which is not *no* call: it calls `Array.isArray` and `Number.isNaN`. Those are what the
    // check is — a hand-written version of this predicate would call the same two intrinsics and
    // nothing else — so the assertion is the exact set rather than the absence of a `(`.
    const body = functionBody(read(join(bundle, 'orders.mjs')), 'acceptsPoint');
    expect(callees(body)).toEqual(['Array.isArray', 'Number.isNaN']);
    // Nothing is built to check a value against. No literal, no closure, no temporary.
    expect(body).not.toContain('{');
  });

  it('reach nothing at runtime: the bundle imports no validator', () => {
    const code = read(join(bundle, 'orders.mjs'));
    expect(code).not.toMatch(/^import /m);
    expect(code).not.toContain('require(');
    // The runtime walker's entry points. Their presence would mean a call fell back to
    // interpreting a descriptor, which is the failure REQ-AV-2 exists to make impossible.
    for (const name of ['matches', 'collectIssues', 'refsOf']) expect(code).not.toContain(`function ${name}(`);
  });

  it('measure the same on both routes, because they are the same code', async () => {
    // Phase 8 asks for the CLI's throughput published beside the plugin's. Since the previous
    // test establishes the two run identical code, the honest presentation is both numbers and
    // no ratio assertion: a ratio between two copies of one function measures the machine, and
    // on a thermally throttled one it measures the weather.
    const viaCli = (await import(join(CLI, 'src', 'orders.ts'))) as typeof bundled;
    const good = [
      { id: 1, reference: 'ORD-0001', total: 4250, status: 'shipped', note: null, shipTo: ADDRESS },
      { id: 2, reference: 'ORD-0002', total: 12, status: 'pending', note: 'gift', shipTo: ADDRESS },
    ];
    const at = (index: number): unknown => good[index & 1];

    const N = 200_000;
    const cliOps = opsPerSecond(index => viaCli.accepts(at(index)), N);
    const pluginOps = opsPerSecond(index => bundled.accepts(at(index)), N);
    console.log(
      `consumer fixtures, is<Order>: cli ${cliOps.toLocaleString()} ops/s, plugin ${pluginOps.toLocaleString()} ops/s`,
    );

    // A floor rather than a ratio. Two million a second is far below what either route reads
    // and far above what walking a descriptor achieves, so this fails if — and only if — one
    // of them stopped being the compiled path.
    expect(cliOps).toBeGreaterThan(2_000_000);
    expect(pluginOps).toBeGreaterThan(2_000_000);
  }, 60_000);
});

const ADDRESS = { line1: '1 Example Way', city: 'Bristol', postcode: 'BS1 1AA' };

/** Through esbuild's parser and printer, unchanged, so that both sides were printed once. */
function reprint(code: string): string {
  return transformSync(code, { loader: 'js', format: 'esm', target: 'node26' }).code;
}

/** The `Order` predicate, with the per-file helper suffixes normalised away. */
function checkBody(code: string): string {
  const body = functionBody(code, /_zmdbCheckOrder\d+/.exec(code)?.[0] ?? 'missing');
  return body
    .replaceAll(/(_zmdb[A-Za-z]+)\d+/g, '$1')
    .replaceAll(/\s+/g, ' ')
    .trim();
}

/** Everything called in a fragment of generated code, deduplicated and sorted. */
function callees(body: string): string[] {
  const found = [...body.matchAll(/([\w$]+(?:\.[\w$]+)*)\s*\(/g)].map(match => match[1] ?? '');
  return [...new Set(found)].toSorted();
}

/** One function's body, by name. Both inputs are generated, so brace counting is enough. */
function functionBody(code: string, name: string): string {
  const at = code.indexOf(`function ${name}(`);
  if (at === -1) throw new Error(`no \`${name}\` in the generated code`);
  const open = code.indexOf('{', at);
  let depth = 0;
  for (let i = open; i < code.length; i += 1) {
    if (code[i] === '{') depth += 1;
    else if (code[i] === '}') {
      depth -= 1;
      if (depth === 0) return code.slice(open + 1, i);
    }
  }
  throw new Error(`\`${name}\` is not closed`);
}
