// @generated by zmdb http-client; contract-format=1; generator=fixture-690
import {
  CLIENT_RUNTIME_ABI,
  ClientResponseError,
  createClientRuntime,
  type CallOptions,
  type ClientOperationResponse,
  type ClientOptions,
  type DecodeResult,
  type GeneratedOperation,
} from '@zmdb/client';

export interface Widget {
  readonly id: string;
  readonly name: string;
}

export interface WidgetError {
  readonly code: string;
  readonly message: string;
}

export interface GetWidgetInput {
  readonly id: string;
}

export interface RenameWidgetInput {
  readonly id: string;
  readonly name: string;
}

function property(value: unknown, name: string): unknown {
  return typeof value === 'object' && value !== null ? Reflect.get(value, name) : undefined;
}

function decodeWidget(value: unknown): DecodeResult<Widget> {
  const id = property(value, 'id');
  const name = property(value, 'name');
  const issues = [
    ...(typeof id === 'string' ? [] : [{ path: '$.id', message: 'expected string' }]),
    ...(typeof name === 'string' ? [] : [{ path: '$.name', message: 'expected string' }]),
  ];
  return issues.length === 0 && typeof id === 'string' && typeof name === 'string'
    ? { ok: true, value: { id, name } }
    : { ok: false, issues };
}

function decodeWidgetError(value: unknown): DecodeResult<WidgetError> {
  const code = property(value, 'code');
  const message = property(value, 'message');
  const issues = [
    ...(typeof code === 'string' ? [] : [{ path: '$.code', message: 'expected string' }]),
    ...(typeof message === 'string' ? [] : [{ path: '$.message', message: 'expected string' }]),
  ];
  return issues.length === 0 && typeof code === 'string' && typeof message === 'string'
    ? { ok: true, value: { code, message } }
    : { ok: false, issues };
}

function encoded(value: string): string {
  return encodeURIComponent(value);
}

async function readWidget(response: ClientOperationResponse): Promise<Widget> {
  if (response.status === 200) return response.body.json('application/json', decodeWidget);
  if (response.status === 404) {
    const body = await response.body.json('application/json', decodeWidgetError);
    throw new ClientResponseError('get_widget', 404, body, response.headers);
  }
  return response.unexpectedStatus();
}

const getWidgetOperation: GeneratedOperation<GetWidgetInput, Widget> = {
  abi: CLIENT_RUNTIME_ABI,
  operationId: 'get_widget',
  method: 'GET',
  security: [],
  schemes: {},
  version: { kind: 'none' },
  prepare: input => ({
    path: `/widgets/${encoded(input.id)}`,
    query: [],
    headers: { accept: 'application/json' },
    cookies: [],
  }),
  read: readWidget,
};

const getPrivateWidgetOperation: GeneratedOperation<GetWidgetInput, Widget> = {
  ...getWidgetOperation,
  operationId: 'get_private_widget',
  security: [{ bearerAuth: [] }],
  schemes: { bearerAuth: { type: 'http', scheme: 'bearer' } },
  prepare: input => ({
    path: `/private/widgets/${encoded(input.id)}`,
    query: [],
    headers: { accept: 'application/json' },
    cookies: [],
  }),
  read: async response => {
    if (response.status === 200) return response.body.json('application/json', decodeWidget);
    if (response.status === 404) {
      const body = await response.body.json('application/json', decodeWidgetError);
      throw new ClientResponseError('get_private_widget', 404, body, response.headers);
    }
    return response.unexpectedStatus();
  },
};

const renameWidgetOperation: GeneratedOperation<RenameWidgetInput, Widget> = {
  abi: CLIENT_RUNTIME_ABI,
  operationId: 'rename_widget',
  method: 'PATCH',
  security: [],
  schemes: {},
  version: { kind: 'none' },
  prepare: input => ({
    path: `/widgets/${encoded(input.id)}`,
    query: [],
    headers: { accept: 'application/json', 'content-type': 'application/json' },
    cookies: [],
    body: JSON.stringify({ name: input.name }),
  }),
  read: async response => {
    if (response.status === 200 || response.status === 202) {
      return response.body.json('application/json', decodeWidget);
    }
    if (response.status === 409) {
      const body = await response.body.json('application/json', decodeWidgetError);
      throw new ClientResponseError('rename_widget', 409, body, response.headers);
    }
    return response.unexpectedStatus();
  },
};

export function createApiClient(options: ClientOptions) {
  const runtime = createClientRuntime(options);
  return Object.freeze({
    getWidget(input: GetWidgetInput, callOptions?: CallOptions): Promise<Widget> {
      return runtime.call(getWidgetOperation, input, callOptions);
    },
    getPrivateWidget(input: GetWidgetInput, callOptions?: CallOptions): Promise<Widget> {
      return runtime.call(getPrivateWidgetOperation, input, callOptions);
    },
    renameWidget(input: RenameWidgetInput, callOptions?: CallOptions): Promise<Widget> {
      return runtime.call(renameWidgetOperation, input, callOptions);
    },
  });
}

export type ApiClient = ReturnType<typeof createApiClient>;
