// @generated by zmdb http-client; contract-format=1; generator=fixture-697
import {
  CLIENT_RUNTIME_ABI,
  createClientRuntime,
  type CallOptions,
  type ClientOperationResponse,
  type ClientOptions,
  type DecodeResult,
  type GeneratedOperation,
} from '@zmdb/client';

export interface ProbeResult {
  readonly id: string;
  readonly requestId: string;
  readonly authorization: string;
  readonly tenant: string;
  readonly session: string;
  readonly ignoredHeader: boolean;
  readonly ignoredCookie: boolean;
}

export interface GetProbeInput {
  readonly id: string;
}

function property(value: unknown, name: string): unknown {
  return typeof value === 'object' && value !== null ? Reflect.get(value, name) : undefined;
}

function decodeProbe(value: unknown): DecodeResult<ProbeResult> {
  const id = property(value, 'id');
  const requestId = property(value, 'requestId');
  const authorization = property(value, 'authorization');
  const tenant = property(value, 'tenant');
  const session = property(value, 'session');
  const ignoredHeader = property(value, 'ignoredHeader');
  const ignoredCookie = property(value, 'ignoredCookie');
  const issues = [
    ...(typeof id === 'string' ? [] : [{ path: '$.id', message: 'expected string' }]),
    ...(typeof requestId === 'string' ? [] : [{ path: '$.requestId', message: 'expected string' }]),
    ...(typeof authorization === 'string' ? [] : [{ path: '$.authorization', message: 'expected string' }]),
    ...(typeof tenant === 'string' ? [] : [{ path: '$.tenant', message: 'expected string' }]),
    ...(typeof session === 'string' ? [] : [{ path: '$.session', message: 'expected string' }]),
    ...(typeof ignoredHeader === 'boolean' ? [] : [{ path: '$.ignoredHeader', message: 'expected boolean' }]),
    ...(typeof ignoredCookie === 'boolean' ? [] : [{ path: '$.ignoredCookie', message: 'expected boolean' }]),
  ];
  return issues.length === 0 &&
    typeof id === 'string' &&
    typeof requestId === 'string' &&
    typeof authorization === 'string' &&
    typeof tenant === 'string' &&
    typeof session === 'string' &&
    typeof ignoredHeader === 'boolean' &&
    typeof ignoredCookie === 'boolean'
    ? {
        ok: true,
        value: {
          id,
          requestId,
          authorization,
          tenant,
          session,
          ignoredHeader,
          ignoredCookie,
        },
      }
    : { ok: false, issues };
}

async function readProbe(response: ClientOperationResponse): Promise<ProbeResult> {
  if (response.status === 200) return response.body.json('application/json', decodeProbe);
  return response.unexpectedStatus();
}

const getProbeOperation: GeneratedOperation<GetProbeInput, ProbeResult> = {
  abi: CLIENT_RUNTIME_ABI,
  operationId: 'get_probe',
  method: 'GET',
  security: [],
  schemes: {},
  version: { kind: 'none' },
  prepare: input => ({
    path: `/probes/${encodeURIComponent(input.id)}`,
    query: [],
    headers: { accept: 'application/json' },
    cookies: [],
  }),
  read: readProbe,
};

export function createApiClient(options: ClientOptions) {
  const runtime = createClientRuntime(options);
  return Object.freeze({
    getProbe(input: GetProbeInput, callOptions?: CallOptions): Promise<ProbeResult> {
      return runtime.call(getProbeOperation, input, callOptions);
    },
  });
}

export type ApiClient = ReturnType<typeof createApiClient>;
